### ISSUE TITLE
Improve Accessibility Score in Lighthouse

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#108]
We should get the Accessibility Score of our starter theme to 100! 

![Screen Shot 2019-05-31 at 12 32 23](https://user-images.githubusercontent.com/3305402/58700480-6b513180-83a0-11e9-9c52-e7c403045dfa.png)

Right now it is on 71. The list of things we need to improve are:

![Screen Shot 2019-05-31 at 12 37 04](https://user-images.githubusercontent.com/3305402/58700602-d00c8c00-83a0-11e9-863d-5d75b37aa3fc.png)

These are additional items to check:
1. The page has a logical tab order
2. Interactive controls are keyboard focusable
3. Interactive elements indicate their purpose and state
4. The user's focus is directed to new content added to the page
5. User focus is not accidentally trapped in a region
6. Custom controls have associated labels
7. Custom controls have ARIA roles
8. Visual order on the page follows DOM order
9. Offscreen content is hidden from assistive technology
10. Headings don't skip levels
11. HTML5 landmark elements are used to improve navigation.

**Comment by SantosGuillamot** [comment]
Closed by #85.
