### ISSUE TITLE
How to implement Gutenberg blocks

### ISSUE THREAD

**Issue by davidrhoderick** [frontity/frontity#125]
I apologize if this is a naive but I am experienced with WordPress but haven't worked much with Gutenberg blocks.  How would one approach styling the Gutenberg blocks accordingly?  For example, if I want to use reactstrap to add a carousel element for a gallery block created by Gutenberg, how would one do that?  Feel free to close this if it is not in the scope of this project's documentation.

**Comment by luisherranz** [comment]
We are trying to answer all the questions in our community forum and leave GitHub issues for bugs. But you wouldn't have a way to know so it's absolutely our fault and I'd like to apology for that. We are going to prepare the issues templates explaining precisely that.

This is the topic I've opened for your question. You can follow the conversation there:
https://community.frontity.org/t/how-to-implement-gutenberg-blocks/265

**Comment by luisherranz** [comment]
Closing this now. Please go to the forum post if you have more questions or want to keep the conversation going on :)
