### ISSUE TITLE
Cannot create a new project with a `.` character

### ISSUE THREAD

**Issue by brandondove** [frontity/frontity#128]
Is there a reason for the limitation of characters when creating a new project? When I try to run the following command: `npx frontity create frontity.local` I get the following error: `Error: The name of the package is not valid. Please enter a valid one (only letters and dashes).`

**Comment by luisherranz** [comment]
The truth is that I don't remember why we chose to only allow letters and dashes.

That name is used for both the folder and the package.json name. Both allow other characters like dots and underscores.  For reference, this is what the npm docs say about the name:
https://docs.npmjs.com/files/package.json#name

@orballo could you please take a look? Do you remember the reasoning behind this?

The code is here:
https://github.com/frontity/frontity/blob/dev/packages/frontity/src/utils.ts#L3-L6

**Comment by orballo** [comment]
There is no strong reason behind this. At the moment I just went with that regex because it seemed to be the convention in the NPM ecosystem, but I think we should definitely follow the docs on the `name` field and allow anything NPM allows.

**Comment by luisherranz** [comment]
Candidate for a `good first issue`? ☺️

**Comment by orballo** [comment]
Yes it might, it's just a different regex.

**Comment by cbravobernal** [comment]
I made a PR to fix it #135

**Comment by luisherranz** [comment]
Genius!
