### ISSUE TITLE
Woocommerce API Support

### ISSUE THREAD

**Issue by apvlv** [frontity/frontity#129]
Hello frontity team,

i know it's a very early stage to ask for it, but are there plans to support woocommerce api as well in the future?

Thanks for this amazing project.

**Comment by apvlv** [comment]
Sorry, Going to community with this question, as it's not bug related.

**Comment by adovgun** [comment]
Hope guys who are at the helm of the development will understand.
It would be necessary to compile a map (list) of APIs that are needed in the first place and desirable according to their priority, including WC
