### ISSUE TITLE
`npx frontity create` adds mars-theme's settings even if a different theme has been set

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#132]
By default, `npx frontity create` uses `@frontity/mars-theme` as the project's theme, but when you set a different theme (e.g. `osw-theme-example`), the generated `frontity.settings.js` file doesn't contain the theme package that has been set but the default `mars-theme` and their settings.

The problem is [here](https://github.com/frontity/frontity/blob/frontity%401.0.1/packages/frontity/src/functions/create/steps.ts#L124L141).

**Comment by orballo** [comment]
I fucked up that one miserably 😅We need to make `mars-theme` optional and add a single line for the new one, in the same way `tiny-router` is defined there.

**Comment by michalczaplinski** [comment]
Fixed in #288

**Comment by michalczaplinski** [comment]
@luisherranz I think this was fixed adequately in #288 as indicated earlier. Is there something that we're still missing?

**Comment by luisherranz** [comment]
Yes, it is successfully fixed in #288 but we forgot to assign the issue to you back then.
