### ISSUE TITLE
Add rootMargin to <Image> component

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#139]
Right now `useInView` accepts a `rootMargin`, but `<Image>` doesn't. We should add it to its props and pass it down to `useInView`.

cc: @javiersefer.

**Comment by sagarnasit** [comment]
Hey, @luisherranz I find frontity very interesting as a WordPress and React Developer and want to start contributing to frontity with this good first issue. Let's discuss this issue. :)

**Comment by luisherranz** [comment]
That's awesome Sagar. So glad to hear that :)

@santosguillamot is preparing a guide on how to contribute. Things like how to work with the monorepo and start the example project. Once that's done we'll pass it to you.

Regarding the issue, `<Image />` (from @frontity/components)  is using `useInView` (from @frontity/hooks) which already has support for `rootMargin`.

So it should be as simple as allowing `<Image />` to receive `rootMargin` and pass it down to `useInView`.

`useInView`:
https://github.com/frontity/frontity/blob/dev/packages/hooks/use-in-view.ts#L51

`<Image />` props:
https://github.com/frontity/frontity/blob/dev/packages/components/image.tsx#L32-L39

Use of `useInView` by `<Image />`:
https://github.com/frontity/frontity/blob/dev/packages/components/image.tsx#L98

**Comment by luisherranz** [comment]
Thanks for your first contribution @sagarnasit, and welcome to the Frontity community! ☺️

**Comment by sagarnasit** [comment]
Thank you @luisherranz . I am hoping to contribute more on frontity. Let me know if you have something for me. :slightly_smiling_face:

**Comment by luisherranz** [comment]
Uh, awesome :)

What are you looking for? Core features? Starter themes? Extensions?

**Comment by sagarnasit** [comment]
Didn't think of any specific from above, but whatever you have on react side would be great. :)

**Comment by luisherranz** [comment]
How about adding AMP support to `mars-theme`?

We still need to fix a couple of issues to make it work, but we are working on it right now and it shouldn't take more than one day.

**Comment by sagarnasit** [comment]
@luisherranz Perfect.

**Comment by luisherranz** [comment]
I'm sorry Sagar, we've detected a couple of problems we need to fix first for AMP.

Would you like to work on an official extension? For example, a ContactForm7 extension would be really cool and I think it's a good candidate because it uses the REST API to submit forms and it's not complex at all:
https://github.com/ohze/wp-contact-form-7/blob/master/includes/rest-api.php
https://github.com/ohze/wp-contact-form-7/blob/master/includes/js/scripts.js

If you want, we can do a videocall to walk through the code together and see how it could be approached.

**Comment by luisherranz** [comment]
Oh, it'd also be super cool to have a starter theme made with Reakit :)

I've just opened a new issue to discuss it: https://github.com/frontity/frontity/issues/158
