### ISSUE TITLE
Getting an error while building the project

### ISSUE THREAD

**Issue by wazidshah** [frontity/frontity#141]
Run `npx frontity build && npx frontity` serve on your frontity project

Expected: 
No errors while serving the website.

Actual: 
![Screenshot 2019-06-26 at 3 36 40 PM](https://user-images.githubusercontent.com/16234978/60173543-a07c6280-982c-11e9-9941-e12e2728ce57.png)

Other than that website is served well without any problem

**Comment by luisherranz** [comment]
I think it's the HMR endpoint of a client you were running on dev mode (`/__webpack_hmr`).

Frontity still thinks it's a valid url and tries to resolve it.

I've made a PR (https://github.com/frontity/frontity/pull/144) that returns a 404 instead and should solve the console error.
