### ISSUE TITLE
Misleading usage information

### ISSUE THREAD

**Issue by jamesgeorge007** [frontity/frontity#148]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**
The usage information should be `Usage: frontity <command> [options]` instead.

**Describe the observed behavior**
Misleading usage information shows up. 
![Screenshot from 2019-06-27 21-08-10](https://user-images.githubusercontent.com/25279263/60280134-fbdb4d00-991f-11e9-9a1b-4f647672b827.png)

**Comment by luisherranz** [comment]
You are absolutely right. Thanks for noticing it @jamesgeorge007.

**Comment by luisherranz** [comment]
We should remove `create-package` as well because that functionality is not already there.
