### ISSUE TITLE
Fail gracefully if the Yoast plugin is not installed

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#164]
**Describe the expected behavior**

The package `@frontity/yoast` should fail gracefully if the https://github.com/maru3l/wp-api-yoast-meta plugin is not installed.

It should probably point the user out to the relevant docs.

**Describe the observed behavior**

Write now it only shows this message in the server:
`TypeError: Cannot read property 'yoast_wpseo_social_defaults' of undefined`

**Descriped the steps involved to reproduce the problem**

Install the `@frontity/yoast` plugin, include it in your `frontity.settings.js` file and connect to a WP without the https://github.com/maru3l/wp-api-yoast-meta plugin installed.

**Comment by sagarnasit** [comment]
I have looked through the docs but I don't find relevant doc for frontity/yoast. Would it be just  https://github.com/maru3l/wp-api-yoast-meta to refer in error message?

**Comment by luisherranz** [comment]
Sorry, we've just released it and the docs are coming 😅 

Yes, the plugin we are going to recommend is that one:
https://github.com/maru3l/wp-api-yoast-meta

**Comment by kmiskiewicz** [comment]
Do you know what is the status of the wp-api-yoast-meta project? You recommend forked version which has been forked from another project (https://github.com/ChazUK/wp-api-yoast-meta).

**Comment by DAreRodz** [comment]
You are right, @kmiskiewicz, there are so many forks that we decided to release and maintain our own Yoast Meta plugin (working on it right now, so we expect to release it very soon). Then, this package will be adapted to use it.

**Comment by luisherranz** [comment]
Closed as we are not using this PHP plugin anymore.

**Comment by DAreRodz** [comment]
Just FYI:

We are maintaining now our own WP plugin called [REST API - Head Tags](https://docs.frontity.org/frontity-plugins/rest-api-head-tags), which exposes the meta tags of SEO plugins in the REST API. The way to integrate this plugin with Frontity is simply to install the [`@frontity/head-tags`](https://docs.frontity.org/api-reference-1/frontity-head-tags) package.

**Comment by luisherranz** [comment]
Thanks @DAreRodz 🙂
