### ISSUE TITLE
Expose "fetch" and "URL" in node global

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#166]
**Describe the expected behavior**

`fetch` and `URL` should be available on node `global`.

**Describe the observed behavior**

Right now they are not.

We are using `cross-fetch` but it adds 15kbs of code.

**Solution**

We can import `URL` from the node module `"url"` and fetch from `"node-fetch"`.
Then import them in `/server/index.ts` like this:
```js
(global as any).fetch = fetch;
(global as any).URL = URL;
```

_It will work on TypeScript because it thinks they come from window._

Also, we should get rid of `cross-fetch` on `wp-source` and the regexps that are not using `URL` yet.

**Comment by DAreRodz** [comment]
I'll do this!

**Comment by luisherranz** [comment]
To avoid problem with jest, we can do the opposite: leave things for node and use the client's webpack to exclude those libraries.

```js
externals: {
    "node-fetch": "node-fetch",
    "url": "url";
}
```

Then, export them in `frontity`:
```js
import url from "url"
import nodeFetch from "node-fetch";

export const URL = typeof window !== "undefined" ? window.URL : url.URL;
export const fetch = typeof window !== "undefined" ? window.fetch : nodeFetch; 
```

And finally consume them with frontity:
```js
import { fetch, URL } from "frontity";
```
