### ISSUE TITLE
Images not showing on Safari after navigation

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#169]
**Describe the expected behavior**

Images should show after navigation in all Safari versions.

**Describe the observed behavior**

Right now, in versions lower than 12.1, are only showing at the first render.

**Additional info**

I guess the problem could be that it is not transforming `data-src` and `data-srcset` into `src` and `srcset`.
![Test_Frontity_Blog](https://user-images.githubusercontent.com/34552881/62032718-a928d580-b1ea-11e9-8f69-0f1ea6466a2e.png)

After doing some checks, maybe the problem is at the file https://github.com/frontity/frontity/blob/dev/packages/components/image.tsx#L13-L30. This code may not be executing:

```javascript
// Finds all the images rendered by this component and maps
// their `data-src` and `data-srcset` attributes to `src` and `srcset`
// when the browser doesn't support Proxy or IntersectionObserver.
const noProxyScript = `
  if (typeof window !== "undefined" && (!("Proxy" in window) || !("IntersectionObserver" in window))) {
    document.addEventListener("DOMContentLoaded", function() {
      var images = document.querySelectorAll("img.frontity-lazy-image");
      for (i = 0; i < images.length; ++i) {
        var image = images[i];
        image.setAttribute("src", image.getAttribute("data-src"));
        image.setAttribute("srcset", image.getAttribute("data-srcset"));
        image.removeAttribute("data-src");
        image.removeAttribute("data-srcset");
        image.removeAttribute("style");
      }
    });
  }
`;
````

`IntersectionObserver` is not supported by these Safari versions: https://caniuse.com/#search=IntersectionObserver.

Apart from that, at the same file, `useInView` is being used inside an `if` statement checking for `IntersectionObserver`, so it is not being executed in this case:

```javascript
if (typeof IntersectionObserver !== "undefined") {
      const [onScreen, ref] = useInView({ rootMargin: props.rootMargin, onlyOnce: true });
      if (onScreen) changeAttributes(attributes);
      return (
        <>
          <NoScriptImage {...attributes} />
          <img ref={ref} {...attributes} />
        </>
      );
}
```

**Comment by luisherranz** [comment]
I guess the solution would be to create an `else` here, that handles the case where we are in CSR (`window` exists) but `IntersectionObserver` doesn't:

https://github.com/frontity/frontity/blob/dev/packages/components/image.tsx#L98-L107

```js
// This is for CSR:
  if (typeof window !== "undefined") {
    // Native Lazy Loading
    if (typeof (HTMLImageElement as any).prototype.loading !== "undefined") {
      changeAttributes(attributes);
      return <img {...attributes} />;
    }

    // Lazy Loading via IntersectionObserver
    if (typeof IntersectionObserver !== "undefined") {
      const [onScreen, ref] = useInView({ rootMargin: props.rootMargin, onlyOnce: true });
      if (onScreen) changeAttributes(attributes);
      return (
        <>
          <NoScriptImage {...attributes} />
          <img ref={ref} {...attributes} />
        </>
      );

    // Disable Lazy Loading
    } else {
      // Add an additional case for when IntersectionObserver is undefined:
      changeAttributes(attributes);
      return <img {...attributes} />;
    }
  }
```

What do you think @orballo?

**Comment by orballo** [comment]
Hi guys! @SantosGuillamot your debugging skills are improving a lot! 😁

I opened this PR https://github.com/frontity/frontity/pull/171 to fix the issue and some other wrong things that were happening in the component. Have a look at it and let me know if you need any changes! 😁

**Comment by luisherranz** [comment]
> @SantosGuillamot your debugging skills are improving a lot!

He made both the JS and React guides of the docs! 🤯
https://docs.frontity.org/javascript-and-and-react

> I opened this PR #171 to fix the issue and some other wrong things that were happening in the component.

Thanks for taking a look into this! 😄
