### ISSUE TITLE
Possible problem with code-splitting

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#177]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

Frontity should load even with code splitting and vendors.

**Describe the observed behavior**

Frontity is not loading in this page:
https://goiblas.com/2019/07/28/como-crear-un-bloque-de-restriccion-de-contenido-para-wordpress/

It looks like there was a resolved issue with this problem:
https://github.com/frontity/frontity/issues/21

Maybe there is a problem with vendors created from a code splitted module.

**Descriped the steps involved to reproduce the problem**

- Go to https://goiblas.com/2019/07/28/como-crear-un-bloque-de-restriccion-de-contenido-para-wordpress/
- Frontity doesn't load

We can take a look at the real project with the code here:
https://github.com/goiblas/personal-blog

**Comment by DAreRodz** [comment]
@luisherranz, when you say "frontity is not loading in this page", what do you mean exactly? I just went  to https://goiblas.com/2019/07/28/como-crear-un-bloque-de-restriccion-de-contenido-para-wordpress/ and everything worked fine.

**Comment by SantosGuillamot** [comment]
I think it is because that blog is not using code splitting anymore. You can check it here, a previous version of it: https://personal-blog-gmzhmhbgv.now.sh/2019/07/28/como-crear-un-bloque-de-restriccion-de-contenido-para-wordpress/

**Comment by DAreRodz** [comment]
Oh, I see. Thanks @SantosGuillamot!

**Comment by luisherranz** [comment]
Checkout in the 27 of July commits if you want to take a look: https://github.com/goiblas/personal-blog/commits/master

There's maybe a problem with loadable so I can check it out when I'm back.

**Comment by luisherranz** [comment]
I was able to reproduce it. It looks like it only happens in production when a secondary bundle has been generated.
