### ISSUE TITLE
Image component doesn't load images if height is not present

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#194]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

1. The `<Image>` component should render images even if no `height` is provided.
1. The `<Image>` component should not output a warning if `height` is provided.

**Describe the observed behavior**

1. The `<Image>` component needs a height to work with `loading=lazy`. If it is not provided, the image doesn't load (at all).
1. The `<Image>` component doesn't set the `height` attribute to the `<img>` tag and a warning is sent.

**Describe the steps involved to reproduce the problem**

1. Add an `<Image>` component without height: it should not appear.
1. Add an `<Image>` component with height: the warning should appear.

**Possible solutions**

- Deactivate `loading=lazy` if height is not provided.
- Use IO if height is not provided.
- Add a default `min-height`: this won't remove the warning, but the image will appear.
- Add a default `aspectRatio`: this won't remove the warning but the image will appear. Maybe in the future with `intrinsicSizes`.

**Comment by DAreRodz** [comment]
> Use IO if height is not provided.

I think this is the best solution. This way, images will lazy-load without warnings in those cases Chrome would have _complained_.
