### ISSUE TITLE
More improvements for mars-theme

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#223]
The remaining tasks that weren't implemented in #203:

- [x] Finish adding comments to every line of code. (#232)
- [x] Create a menu that can be opened and closed with state.
- [ ] Add `afterCSR` example (can be dark/light theme).
- [ ] Add `beforeSSR` example.
- [ ] Add derived state example.
- [ ] Add a custom post type and a custom taxonomy.
- [ ] Rename `list` to `archive`.
- [ ] Add "results not found" for searches without results.
- [ ] Add a height to the `Image` component inside `FeaturedMedia` to make it work with native lazy loading.
- [ ] Add `fetchLinks` setting to do a fetch of all the data of all the possible links.
- [ ] Add proper HTML5 semantic tags.
- [x] Add input fields styling. (https://github.com/frontity/frontity/issues/231)
- [ ] Add e2e tests for Mars
- [ ] Comment the file frontity.settings.js

**Comment by luisherranz** [comment]
Quick question: shouldn't we add a `height` to the `<FeaturedImage>` to be able to use the native lazy load?

As far as I can see, it's not working right now (loading is auto, not lazy):

<img width="457" alt="Screen Shot 2019-10-25 at 18 02 38" src="https://user-images.githubusercontent.com/3305402/67586337-ad18b500-f751-11e9-8b87-7d96ec78c4d9.png">

It is still the `Container` the one with `300px` of height. The image has `100%`.

Apart from that... I can't get it to switch to `lazy`, even by adding a `height` to `Image`:
```jsx
    <Container>
      <StyledImage
        alt={media.title.rendered}
        src={media.source_url}
        srcSet={srcset}
        height={300}
      />
    </Container>
```

I'm not sure what I'm doing wrong, but after that change it is still `auto`.

**Comment by luisherranz** [comment]
My mistake, it works when I add a `height`, sorry 🙏 

But no matter what I put in `height`, the image doesn't change. Even if I use `height={1}`:

```html
<img loading="lazy" style="" height="1" src="...">
```

Why is it just a number and does not accept a unit? Why doesn't it affect the final height?

I'm trying to understand the logic behind it :)

**Comment by luisherranz** [comment]
If I add a `height` this warning reappears:
```
[Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions 
specified. Specifying dimensions improves performance. See https://crbug.com/954323
```

**Comment by DAreRodz** [comment]
> Why is it just a number and does not accept a unit? Why doesn't it affect the final height?

We are using the same restriction of the HTML `height` property for `<img>`.
From [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img):

> `height`: The intrinsic height of the image, in pixels. Must be an integer without a unit.

So, it has to be a number. 🙂

---

> If I add a height this warning reappears:

In which case that happens? Can you post some code?

**Comment by luisherranz** [comment]
> height: The intrinsic height of the image, in pixels. Must be an integer without a unit.

Didn't know that, or I guess I did, but I forgot, thanks 😅

> In which case that happens? Can you post some code?

If I add a `height` to the `Image` component of `FeaturedImage` in mars:
```jsx
    <Container>
      <StyledImage
        alt={media.title.rendered}
        src={media.source_url}
        srcSet={srcset}
        height={300}
      />
    </Container>
```

**Comment by jcklpe** [comment]
Another suggestion:

Rename the <Title/> Component to <Meta/> and put the content currently in <Head/> in the <Head/> component inside of the rendered <Head/> component of <Meta/>

Reasons why:
- <Title/> is currenly used to serve title information to the Head component. It's not used in the page to display the title. So that's kind of confusing. Because a Title is conceivably a component that people might make. (in fact in the post.js file there is a component called <Title/> which lead to some of my confusion. )
- It's confusing to have a component that serves title information to the Head that is outside of the <Head/> component on the index.js page. Just put all the metatag type logic in the same component and let that cover it.

**Comment by luisherranz** [comment]
Closing this as this should be opened as a Feature Discussion in the community forum.

@SantosGuillamot, please take a look with @juanmaguitar and @mburridge to decide how's now going to have the responsibility of `mars-theme`.
