### ISSUE TITLE
Review default handlers for WordPress.org & WordPress.com

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#228]
Take a look at [wp-org](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/patterns/wp-org.ts) and [wp-com](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/patterns/wp-com.ts) patterns so we only include the ones that apply to most common cases.

For example, this case may be removed:
https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/patterns/wp-org.ts#L43L48

**Comment by luisherranz** [comment]
Closing this as it doesn't seem like an issue now.
