### ISSUE TITLE
[wp-source] state.source.homepage option not working

### ISSUE THREAD

**Issue by heyimbrucelee** [frontity/frontity#239]
to reproduce :
npx frontity create test
cd test & npx frontity dev

in frontity.setttings.js add homepage parameter to tag/japan/ for exemple
```js
 {
      "name": "@frontity/wp-source",
      "state": {
        "source": {
          "api": "https://test.frontity.io/wp-json",
          "homepage" : "/tag/japan/"
        }
      }
```

 in postType.ts type is undefined :
```js
  const { type, id } = state.source.get(path);
  const data = state.source.get(route);
  Object.assign(data, {
    type,
    id,
    isPostType: true,
    [`is${capitalize(type)}`]: true
  });
};
```
leading to error
```
TypeError: Cannot read property 'split' of undefined
    at __webpack_exports__.default.str (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:73)
```

**Comment by luisherranz** [comment]
Your `homepage` needs to be a valid WordPress page. For example: `/about-us`. You also need to set `postsPage` and have the same configuration on your WordPress (so it won't work with test.frontity.io).

More info here: https://docs.frontity.org/api-reference-1/wordpress-source#state-source-homepage

The next time you have a problem please don't open a GitHub issue, open a new topic in our community forum: https://community.frontity.org/c/dev-talk-questions

**Comment by heyimbrucelee** [comment]
Thanks you,
i missed this point :
have the same configuration on your WordPress
(i see doc have been updated ;) )

Could you please explain what does enforce to have same config on Wordpress ?

**Comment by luisherranz** [comment]
> (i see doc have been updated ;) )

Yes, we have improved our documentation :)

> Could you please explain what does enforce to have same config on Wordpress ?

It looks like the permalink of that page in the REST API is not correct until you match the same configuration in WordPress.
