### ISSUE TITLE
[CLI]: Notify users of an available update

### ISSUE THREAD

**Issue by jamesgeorge007** [frontity/frontity#263]
Users may not be aware about any newer releases being made and would end up using the older versions.

[update-notifier](https://www.npmjs.com/package/update-notifier) serves the purpose here. As from the tagline, `Inform users of your package of updates in a non-intrusive way`.

**Comment by luisherranz** [comment]
Thanks for the suggestion @jamesgeorge007.

I've created a new entry in our roadmap for this feature:
https://community.frontity.org/t/notify-users-about-new-versions-in-cli/1025

The roadmap is not public yet, so you won't be able to access the link right now. We'll make everything public this month. I'm going to close this issue in favor of the roadmap entry.

**Comment by luisherranz** [comment]
The roadmap is public now:
- https://www.notion.so/frontity/Frontity-Roadmap-e6fac9339a474031b2bc9fd90a075b69
- https://community.frontity.org/c/framework-features/33
