### ISSUE TITLE
Frontity shows `&amp;` when ampersand is used in a title

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#268]
**_Bug report_**

- [X] I've searched for existing issues
- [X] I've checked documentation: https://docs.frontity.org
- [X] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

If I use an ampersand in one category of my WordPress, it should display the character `&` instead of `&amp;`.

**Describe the observed behavior**

Frontity is displaying `&amp;` in both twentytwenty-theme and mars-theme for the category `Business & Marketing`.

**twentytwenty-theme**
<img width="1026" alt="Screen Shot 2020-01-17 at 08 23 21" src="https://user-images.githubusercontent.com/34552881/72603756-ed836b80-3919-11ea-9342-a869a6cfc5d8.png">

**mars-theme**
![Screenshot from 2020-01-17 10-51-50](https://user-images.githubusercontent.com/34552881/72603810-04c25900-391a-11ea-9fc2-a79cece29e51.png)

**Comment by SantosGuillamot** [comment]
It seems that, by default, WordPress is showing `&amp;` in the REST API Response.

![Screenshot from 2020-01-17 10-50-56](https://user-images.githubusercontent.com/34552881/72604232-c8dbc380-391a-11ea-9012-c678a445a060.png)

**Comment by luisherranz** [comment]
I wonder which one is better  for things like `category.name`:
- Encourage to use `dangerouslySetInnerHtml`.
```jsx
// Instead of this
<div>{category.name}</div>
// use this
<div dangerouslySetInnerHtml={{ __html: category.name }} />
```
- Expose `decode` in `"frontity"` and encourage to use it.
```jsx
// Instead of this
<div>{category.name}</div>
// use this
<div>{decode(category.name}}</div>
```
- Fix it ourselves in `wp-source`.
```jsx
// Keep using this
<div>{category.name}</div>
// but lose access to the encoded category name
```

**Comment by orballo** [comment]
I think in this case it's something that should be fixed. Only `rendered` fields should have coded text as they are expected to contain `html` in my opinion, and people should choose to insert them or parse them. But it feels more like an error than a feature having encoded text in a field like `name`.

**Comment by luisherranz** [comment]
Thanks for your feedback @orballo.

**Comment by rmartinezduque** [comment]
Hey guys, 

I just realized that this also happens with the UTM tracking links of our blog posts. Frontity displays `&amp;` when the ampersand is used on a tracking link of a post.

For example,

**In WordPress**, a link has these UTM parameters:

![wordpress-tracking-link](https://user-images.githubusercontent.com/20700757/73350772-f109e180-428d-11ea-8139-68b7a776bd5e.png)

**In Frontity** it changes and the same link shows the `&amp`; instead:

![frontity-tracking-links](https://user-images.githubusercontent.com/20700757/73350803-03841b00-428e-11ea-9723-401ce5a3100d.png)

Therefore, it's **not possible to currently track the UTM links of our posts** on Google Analytics.

**Comment by luisherranz** [comment]
Thanks for reporting that Reyes!

Could you please open a new bug for it? It is a different problem than the one outlined in this issue :)

**Comment by rmartinezduque** [comment]
Sure, @luisherranz. I thought it was the same problem, sorry.

This is the new issue: https://github.com/frontity/frontity/issues/294.

**Comment by luisherranz** [comment]
No problem Reyes! Thanks :)

**Comment by michalczaplinski** [comment]
Isn't this something that can be configured in your REST API? I would assume that most of the content should not be escaped, so is there a way to turn it off? (i don't know wordpress well enough to know)

**Comment by michalczaplinski** [comment]
Like @orballo said, actually, I think only the `rendered` fields should be escaped.

**Comment by michalczaplinski** [comment]
@luisherranz 

Isn't escaping of the content configurable in WordPress?
If yes, then can we turn it off for all the content but the `rendered` fields? This should solve the problem if I understand it correctly.

**Comment by luisherranz** [comment]
Unfortunately, it's not. The REST API doesn't have any options.

**Comment by michalczaplinski** [comment]
> Unfortunately, it's not. The REST API doesn't have any options.
ok, that sucks 😅 

In that case I ll change the wp-source to `unescape` in every field that is not a `.rendered`. It's technically double work, but seems like the only solution.

**Comment by michalczaplinski** [comment]
@luisherranz I realized that it's maybe a better idea to implement the unescaping in `@frontity/connect` instead so that we can unescape the content "lazily" so to speak, only if a particular field is actually rendered in a component. Then, in the `get()` handler we can check if the particular field that is accessed is `.rendered` and in that case opt out of unescaping. 

Thoughts? 🙂 

EDIT: Hmm, wait I guess this won't work because this way we might unescape content in some props that should not be unescaped... Unless we can be sure that the particular prop came from `state.source.data`...

**Comment by luisherranz** [comment]
Yeah...   I don't think this should be done at the state manager level, but either in the theme with a `decode` function exposed by frontity or automatically by wp-source.
