### ISSUE TITLE
Headlines fonts display differently on Twenty Twenty Frontity theme

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/frontity#278]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

If I use the Twenty Twenty Frontity theme, it should display the same font style and size for titles / headlines as the Twenty Twenty WordPress theme.

**Describe the observed behavior**

The Twenty Twenty Frontity theme displays fonts of headlines differently than the WordPress theme.

Here are some comparison screenshots between the themes.

![title-comparison](https://user-images.githubusercontent.com/20700757/72885202-bd680e00-3d07-11ea-90ff-bf9ac2e17e61.png)
![heading-comparison](https://user-images.githubusercontent.com/20700757/72885207-bf31d180-3d07-11ea-9839-bb8414e97d9a.png)

**Comment by luisherranz** [comment]
Thanks @rmartinezduque.

**Comment by rmartinezduque** [comment]
**Other observed behavior**

I also realized that the Twenty Twenty Frontity theme looks a bit weird on mobile: the featured image above content is very small and there's too much space between this image and the first paragraph.

Not sure if this helps but I'm using a Xiaomi MI A1 - Android version 9.

![Screenshot_20200123-112640-1](https://user-images.githubusercontent.com/20700757/72979768-56b32500-3dd9-11ea-9ec6-8f06653c9c96.png)

**Comment by DAreRodz** [comment]
> **Other observed behavior**
>
> I also realized that the Twenty Twenty Frontity theme looks a bit weird on mobile: the featured image above content is very small and there's too much space between this image and the first paragraph.

I wasn't able to reproduce this issue so it seems that it could be addressed in a different PR. @rmartinezduque, do you remember which browser you used for your tests?

**Comment by rmartinezduque** [comment]
Hey @DAreRodz, the issue with the featured images was already fixed by Mario - https://github.com/frontity/frontity.org/pull/160.

However, the problem with the fonts it's still happening (see first screenshots). Let me know if I can be of any help!
