### ISSUE TITLE
Implement an iframe component

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#281]
**Feature:** [Lazy load iframes processor](https://community.frontity.org/t/lazy-load-iframes-processor/1116)
**User Story**: Lazy load all iframes

- [x] Create the iframe component.
- [x] e2e tests.
- [x] Update docs.

Branch: `s0-f1-lazy-load-iframe`
[Sprint Card](https://github.com/orgs/frontity/projects/2#card-32042686)

**Comment by iamuchejude** [comment]
I have written more [`e2e tests`](https://github.com/frontity/frontity/blob/iframe-processor/e2e/integration/iframe.spec.js) for the iframe components. However, some of the tests (skipped) are missing for some reasons I don't understand at the moment, I'll need help figuring out why they are failing.

cc: @luisherranz @michalczaplinski @DAreRodz

**Comment by DAreRodz** [comment]
I'll take a look, @iamuchejude.

**Comment by luisherranz** [comment]
I have added the `blocked` label until you decide what to do guys 👍

**Comment by DAreRodz** [comment]
Unblocking this. Following the conversation here: https://github.com/frontity/frontity/pull/280
