### ISSUE TITLE
Implement an iframe processor

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#282]
**Feature:** [Lazy load iframes processor](https://community.frontity.org/t/lazy-load-iframes-processor/1116)
**User Story**: Lazy load all iframes

- [x] Create the iframe processor.
- [x] Unit tests.
- [x] Update docs.

Branch: `s0-f1-lazy-load-iframe`
[Sprint Card](https://github.com/orgs/frontity/projects/2#card-32042686)

**Comment by iamuchejude** [comment]
The e2e tests for the [`iframe component`](https://github.com/frontity/frontity/issues/281) is currently undergoing development, putting this issue on hold.
