### ISSUE TITLE
Changing permalinks may break wp-source

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#290]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

In test.frontity.io we moved from the `/%post%` permalink to the `/%year%/%post%` permalink.

There are some hardcoded links in the content of some posts. Those posts still point to the old `/%post%` link. For example:
- Old link: `"/banff-national-park/"`
- New link:  `"/2016/banff-national-park/"`

When the `postType` handler is checking for the post, it uses the slug `banff-national-park` and it finds the new post, even thought the post link is not the same (it is still the old).

**Describe the expected behavior**

It should return a 404 error message for that post.

**Describe the observed behavior**

It throws an error in the following line because `type` is undefined:
https://github.com/frontity/frontity/blob/d0f3b55ebeaef4c8ed5c0f6ff66719d9b9629bfe/packages/wp-source/src/libraries/handlers/postType.ts#L50 

**Describe the steps involved to reproduce the problem**

You need to use a theme with a processor that turns the anchors found in `content` to `Link` components, like the chakra-theme.

- Go to: "/2016/shinjuku-gyoen-national-garden/"
- Scroll down to the "post about the Banff National Park" link.
- Click on it, you'll get the error.

**Possible solution**

Instead of just checking if `populated` length is higher than 0 at this line https://github.com/frontity/frontity/blob/d0f3b55ebeaef4c8ed5c0f6ff66719d9b9629bfe/packages/wp-source/src/libraries/handlers/postType.ts#L30 we should check if the link exists, like what we are doing here https://github.com/frontity/frontity/blob/d0f3b55ebeaef4c8ed5c0f6ff66719d9b9629bfe/packages/wp-source/src/libraries/handlers/postType.ts#L44

**Comment by DAreRodz** [comment]
Closing in favor of https://github.com/frontity/frontity/issues/366.
