### ISSUE TITLE
Add pagination to twentytwenty-theme

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#292]
**Feature topic**: [Pagination for the TwentyTwenty theme](https://community.frontity.org/t/pagination-for-the-twentytwenty-theme/1229)
**User Story**: Add pagination

[Sprint Card](https://github.com/orgs/frontity/projects/2#card-33013919)

**Comment by luisherranz** [comment]
On hold until this dependency is finished: https://github.com/frontity/frontity/issues/312

**Comment by iamuchejude** [comment]
@luisherranz You added a `waiting-for-dependencies` label to this issue. Do you mean [https://github.com/frontity/frontity/issues/312](https://github.com/frontity/frontity/issues/312)?

**Comment by michalczaplinski** [comment]
> @luisherranz You added a waiting-for-dependencies label to this issue. Do you mean #312?

@iamuchejude I think you're correct.  I have done some work on this before, so let me know if you need help.

**Comment by luisherranz** [comment]
> @luisherranz You added a waiting-for-dependencies label to this issue.

Sorry, my mistake 👍

**Comment by luisherranz** [comment]
@iamuchejude I forgot to include the feature topic of this issue in the description. Here it is: https://community.frontity.org/t/pagination-for-the-twentytwenty-theme/1229

**Comment by luisherranz** [comment]
I've also deleted the branch name (you can use whatever you want) and updated the sprint card link to the new one which only includes pagination and not infinite scrolling.
