### ISSUE TITLE
UTM links are modified in Frontity's blog: they show `&amp;` when ampersand is used

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/frontity#294]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

If I use an UTM link in a Frontity's blog post which contains an ampersand (`&`), it should keep it as it is and not replace the ampersand with `&amp;`.

**Describe the observed behavior**

Frontity displays `&amp;` (instead of `&`) in the UTM links of our blog posts. Therefore, it's not possible to correctly track them on Google Analytics.

For example,

**In WordPress**, a link has these UTM parameters:

![wordpress-tracking-link](https://user-images.githubusercontent.com/20700757/73350772-f109e180-428d-11ea-8139-68b7a776bd5e.png)

**In Frontity** it changes and the same link shows the `&amp`; instead:

![frontity-tracking-links](https://user-images.githubusercontent.com/20700757/73350803-03841b00-428e-11ea-9723-401ce5a3100d.png)

**Comment by luisherranz** [comment]
I've moved this to on-hold until we agree on https://github.com/frontity/frontity/pull/305#issuecomment-586258057.
