### ISSUE TITLE
Spacing issues in Frontity's blog

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/frontity#295]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the observed behavior**

There are some formatting issues in Frontity's posts, specially regarding the space between words. However, I'm not sure if this problem is directly related to Frontity. @SantosGuillamot suggested that it might be an API issue.

A few examples. This is some text in a **WordPress post**:

![wp-space-between-words](https://user-images.githubusercontent.com/20700757/73479166-be4c1000-4397-11ea-9535-bcb1baa88f88.png)

And this is the **same text in Frontity** (there's no space between the latest words):

![frontity-no-space-between-words](https://user-images.githubusercontent.com/20700757/73479181-c5731e00-4397-11ea-8d40-0d34d4a52375.png)

This is another paragraph in Frontity where it happens the contrary, there are more spaces between words:

![frontity-space-words](https://user-images.githubusercontent.com/20700757/73479212-d885ee00-4397-11ea-9a5b-29f002d4863c.png)

**Comment by luisherranz** [comment]
> @SantosGuillamot suggested that it might be an API issue.

Interesting. Maybe it's related to the `html2react` conversion, but we've never seen this in the past as far as I know.

@rmartinezduque please add links to the posts where it happens.

**Comment by rmartinezduque** [comment]
Sure, here you have some of them:

- https://blog.frontity.org/seo-for-headless-wordpress-themes/ (see first paragraph)
- https://blog.frontity.org/building-a-blog-using-frontity-and-wordpress/ (see last phrase)
- https://blog.frontity.org/announcing-frontity-1-0/ (see the "features" part)

In a paragraph in which the are more spaces between words I noticed that:

1. If you edit that paragraph block as HTML you can see a non breaking space (`&nbsp;`) in the text. In Visual mode, the non breaking space is invisible.
2. If `&nbsp;` is removed from the HTML, the content on Frontity is shown correctly again.

**Comment by SantosGuillamot** [comment]
Could it be related to the fact that we converted the posts from Classic Editor to Gutenberg in the blog? Does it happen in the new ones you wrote directly using Gutenberg?

**Comment by rmartinezduque** [comment]
>Does it happen in the new ones you wrote directly using Gutenberg?

There's only one new post (https://blog.frontity.org/introducing-frontity-chakra-theme/) but no, it doesn't happen on it.

**Comment by luisherranz** [comment]
Closed because it doesn't seem to happen anymore. 

@rmartinezduque feel free to reopen it if you observe this problem again.
