### ISSUE TITLE
Brand new install results in "Error: post type from endpoints " 

### ISSUE THREAD

**Issue by jcklpe** [frontity/frontity#320]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

I install and run a new frontity server and it does not throw any errors. 

**Describe the observed behavior**

I run a brand new install using `npx frontity create frontity-server`

I git clone my theme into the packages folder. 

I install it from path using `npm install ./packages/desert-jackalope`

I run `npx frontity dev`

And it compiles and runs but also throws the following error:

```
Error: post type from endpoints "posts,pages,media" with slug "7e13900faccac92c70fc.hot-update.json" not found
    at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:8:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have no clue what this is. I haven't even changed the frontity.settings.js to point to a different rest endpoint (it's pulling from the default frontity source" nor have I changed it to use anything but the default theme. So... not sure what gives. 

**Describe the steps involved to reproduce the problem**
see above

**Add info about your system**

```
## System:
 - OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
 - Memory: 6.71 GB / 15.93 GB
 - Shell: 5.4.2 - /usr/bin/zsh
## Binaries:
 - Node: 10.19.0 - /usr/bin/node
 - npm: 6.13.7 - /usr/local/bin/npm
## Browsers:
 - Chrome: Not Found
 - Firefox: Not Found
## npmPackages:
 - @frontity/core: ^1.4.1 => 1.4.1
 - @frontity/html2react: ^1.1.15 => 1.1.15
 - @frontity/mars-theme: ./packages/mars-theme => 1.3.0
 - @frontity/tiny-router: ^1.0.18 => 1.0.18
 - @frontity/wp-source: ^1.5.0 => 1.5.0
 - desert-jackalope: file:packages/desert-jackalope => 1.3.0
 - frontity: ^1.4.4 => 1.4.4
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found
```

**Comment by luisherranz** [comment]
Thanks for reporting @jcklpe.

This error appears when you restart Frontity and a browser with localhost:3000 is open and trying to reconnect. It only happens in development mode, so it's no serious, but we should remove the error from the console.log.

**Comment by luisherranz** [comment]
Solved in https://github.com/frontity/frontity/pull/344.
