### ISSUE TITLE
If a handler pattern isn't matched we should return a Server Error

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#331]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**
If I navigate to a url where a handler pattern is not matched, I expect to receive a Server Error explaining the case, something similar as [this one](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/postType.ts#L39-L42), explaining that no handler was matched.

**Describe the observed behavior**
Right now, we receive an "Internal Server Error" without detailed explanation because the `getMatch` function inside `wp-source` returns null at [this line](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/actions.ts#L57).

**Comment by luisherranz** [comment]
It should be a 404 error because the URL was not found.

**Comment by luisherranz** [comment]
test
