### ISSUE TITLE
actions.source.fetch with "force: true" doesn't work as expected [3pt]

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#340]
**Describe the expected behavior**

If I use `actions.source.fetch("/some-link", { force: true })`:
- The data object property `isReady` is not reset to `false` because it is still ready even though we are fetching again to see if there are any updates in the content.
- The data object custom properties (like `items`, `isCategory`...) are not removed.
- The entities I get from the new fetch overwrite the old ones.

**Describe the observed behavior**

If I use `actions.source.fetch("/some-link", { force: true })`:
- The data object property `isReady` resets to `false`.
- The data object custom properties (like `items`, `isCategory`...) are removed.
- The entities I get from the new fetch don't overwrite the old ones.

**Possible solution**

Don't reset `data` when it exists, even if `force` is true (https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/actions.ts#L34-L41).

Modify all the handlers so they pass down `force` to `populate`.

**Comment by michalczaplinski** [comment]
> The entities I get from the new fetch overwrite the old ones.

@luisherranz Could you clarify with an example? Which entities are you referring to specifically?

**Comment by luisherranz** [comment]
You have to pass down `force: true` to populate so it overwrites the old entities with the new ones: https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/populate.ts#L98

Imagine that the title of a post has changed for example.
