### ISSUE TITLE
Can not run project after npx frontity create, cd and npx frontity dev

### ISSUE THREAD

**Issue by concalahan** [frontity/frontity#347]
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [ ] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

The project should be running after npx frontity create pj, cd pj and npx frontity dev (pj is the name)

**Describe the observed behavior**

localhost:3000 return "ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
ValidationError: Invalid configuration object. Babel loader has been initialized using a configuration object that does not match the API schema."

https://i.imgur.com/4QCODCR.png

**Describe the steps involved to reproduce the problem**

**Add info about your system**

## System:
 - OS: macOS Mojave 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
 - Memory: 114.68 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - npm: 6.9.0 - /usr/local/bin/npm
## Browsers:
 - Chrome: 80.0.3987.149
 - Firefox: 74.0
 - Safari: 12.1.1
## npmPackages:
 - @frontity/core: ^1.5.0 => 1.5.0 
 - @frontity/html2react: ^1.3.0 => 1.3.0 
 - @frontity/mars-theme: ./packages/mars-theme => 1.4.0 
 - @frontity/tiny-router: ^1.1.1 => 1.1.1 
 - @frontity/wp-source: ^1.6.1 => 1.6.1 
 - frontity: ^1.5.2 => 1.5.2 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Comment by luisherranz** [comment]
I'm sorry about that.

It looks like the `babel-loader` package was updated and now it throws an error when the configuration property `cacheIdentifier` is not a string. We were using a number until now.

I have fixed it in this PR: #348
I'll let you know once it's merged.
