### ISSUE TITLE
Improve types for Html2React processors

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#352]
# Description

Right now, using TypeScript when declarating a processor for the Html2React package has some problems (see discussion here: https://github.com/frontity/frontity/commit/f7f2e6eab85889465764ae70d1fe73364db5b0ad#r37684196):

- `node` type is not inferred correctly and a type guard is needed to consider it of type `Element`.
- `parent` and `children` nodes cannot be typed with the current implementation. Also, the default props type of this nodes is `unknown` which is not a good default type.

# Possible solution

To solve this issue, the idea is to pass not only the types of the props but the type of the element as well and its `parent` and `children` attributes. Some of this attributes could be optional and the final types would be the passed types merged with a default type.

E.g.

```ts
type LazyImgWrapper = {
  type: "element";
  component: "figure";
  children: [LazyImg];
}

type LazyImg = {
  type: "element";
  component: "img";
  props: { "data-src": string };
  parent: LazyImgWrapper;
};

const myProcessor: Processor<LazyImg> = {
  test: ({ node }) => { },
  processor: ({ node }) => {
    node.props["data-src"] // <- this should be of type `string`
    node.parent.component // <- this should be of type `"figure"`
  }
};
```

**Comment by SantosGuillamot** [comment]
Will we need to adapt the current processors to this? Should we do a release for this in order to use it in the `frontity.org` repo?

**Comment by luisherranz** [comment]
Yes, we would need a release and yes, we would need to update the processors.

I have edited the OP to add "Tasks". @DAreRodz (or anyone else) feel free to add more tasks if needed.

I don't know how important this is and if it justifies a release.
I guess @DAreRodz, @michalczaplinski, and @iamuchejude can answer you that.

**Comment by luisherranz** [comment]
@darerodz, I have assigned this to you as well, as you are going to work on this together.

Could you please keep here a record of what's going on?
- The problems you're facing.
- The approach that you tried and it's not working, and why it's not working.
- The ideas you have in mind to solve it.

**Comment by DAreRodz** [comment]
> * The problems you're facing.
> * The approach that you tried and it's not working, and why it's not working.
> * The ideas you have in mind to solve it.

The problem was mostly an implementation problem that was producing an error when inferring the types for the `parent`'s props, but I think it's solved now. I've done some changes in the code and it works, so the next steps would be to add more TypeScript tests (fixing new problems if they appear), and change other packages that are using processors.

I'm going to unblock the issue. @iamuchejude, I can help you with the implementation or the tests if you need so.

Any further conversation I guess it should be on the PR.

**Comment by luisherranz** [comment]
Thanks for the update @DAreRodz! 👍

**Comment by iamuchejude** [comment]
I'm moving this issue to the `blocked` column until I'm certain about some questions I've about the structure of some of the interface and also when some new bugs are fixed.

**Comment by luisherranz** [comment]
Could you please share the questions here in case we can help you out?

**Comment by iamuchejude** [comment]
The current issue with this task is; fixing the type definition for `processor` broke some internal HTML2React type definitions.

Some of these broken types can be seen in [`libraries/parse/index.tx`](https://github.com/frontity/frontity/blob/improve-processor-types/packages/html2react/src/libraries/parse/index.ts) and [`libraries/components.tsx`](https://github.com/frontity/frontity/blob/improve-processor-types/packages/html2react/src/libraries/components.ts) in the `Html2React` package.

**Comment by iamuchejude** [comment]
We'd have to refractor the definition of some of the interfaces. The reason is that we have a problem with inferring the types of.

The proposed approach to solving this issue include replacing the default type definitions, exposing the interfaces for `Element`, `Text` and `Comment` so users can define custom interface be made by extending them.

```js
import { Element, ElementProps, Processor } from "@frontity/html2react/types.ts";

// You could create a new interface that extends `Element`:
interface CustomElement extends Element {
	props: ElementProps & {
		isAuthenticated: boolean;
	}
}

const userProcessor: Processor<CustomElement> = {
	...
	processor: ({ node }) {
		node.props.css = css``; // this is available as a result of the union with the ElementProps
		node.props.isAuthenticated = true;
		return node;
	} 
}

// Or you could pass a custom element definition
type CustomElementType = {
	type: "element";
	props: ElementProps<HTMLIFrameElement> & {
		src: string;
	}
}


const iframeProcessor: Processor<CustomElementType> = {
	...
	processor: ({ node }) {
		node.iframe.title = "Hello"; // title is an HTML iframe prop
		node.props.css = css``; // this is also going to be available
		return node;
	} 
}
```

@DAreRodz is currently working on these features and will keep working on it till it's done. So, if you have any questions, please, do ask him.

**Comment by luisherranz** [comment]
Thanks for the update @iamuchejude.

By the way, you can access properties of an interface using `Type["property"]` so we don't have to export `ElementProps`. Something like this:

```ts
interface CustomElement extends Element {
	props: Element["props"] & {
		isAuthenticated: boolean;
	}
}
```

**Comment by DAreRodz** [comment]
The `ElementProps` would be just a tiny utility to make writing types simpler when you want to use props from an specific `HTMLElement`, like `HTMLIFrameElement`. So, instead of writing:

```ts
import { Element } from "@frontity/html2react/types";
import { React } from "react";

interface IframeElement extends Element {
  props: Element["props"] &
    React.HTMLProps<HTMLIFrameElement> & {
      "data-src"?: string;
    };
}
```

you could write 

```ts
import { Element, ElementProps } from "@frontity/html2react/types";

interface IframeElement extends Element {
  props: ElementProps<HTMLIFrameElement> & {
    "data-src"?: string;
  };
}
```

which makes it look a bit nicer, in my opinion.

Ah, you could use both approaches, by the way.

**EDIT:** I realized that the param that `React.HTMLProps` receives is just to type the element that event handlers (`onClick`, `onScroll` and so on) will use.

**EDIT 2:** Being said that, I was wondering if it makes sense to just define the `Element`'s `props` attribute as
```ts
export interface Element {
  props: React.HTMLProps<any> & {
    css?: SerializedStyles;
  };
}
```
for one reason: we won't receive any type when defining an event handler, we will have to specify them anyway.

**Comment by luisherranz** [comment]
Sounds fine to me. Whatever you feel it's the best option @DAreRodz 🙂
