### ISSUE TITLE
Get rid of ts-node in our CLI [5pt]

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#355]
**Description**

Most commands on our CLI are simply dev tools, so performance is not important. But `frontity serve` is the command that will be run in production, so it's critical that it is a lean as possible. Right now, we are using `ts-node` internally in our whole CLI, which is fine for most commands, but it's unnecessary for `frontity serve` and it degrades its performance.

We added `ts-node` to be able to use the `frontity.settings.js` with ES modules (import & export) and to be able to use `frontity.settings.ts`. Those two files are outside Webpack.

It may also cause bugs, like the described in here: https://community.frontity.org/t/error-did-you-forget-to-run-frontity-build/1426/11

**Steps to reproduce the issue**

- Clone https://github.com/luisherranz/frontity-react-slick
- Run `npx frontity build`
- Run `npx frontity serve`

**Possible solution**

I think the best solution is to move `ts-node` inside the commands that need it: `dev` and `build` (they belong to `core`).

Apart from that, it'd be interesting to see if thanks to `ts-node`, we could get rid of the build step of `core`. Of course, that means that `ts-node` needs to be required a file before using commonjs, and that the code of `serve` must also be commonjs (no ES modules).

**Comment by RiodeJaneiroo** [comment]
i have the same problem

and now I can not deploy in Vercel
