### ISSUE TITLE
actions.source.fetch should populate link, route, page and query even if data exists [3pt]

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#365]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When calling `actions.source.fetch`, it should populate data with `link`, `route`, `page` and `query`, even if data already exists.

**Observed behavior**

Right now, if data exists, none of those values are populated and a Frontity theme expecting them fails.

**Steps involved to reproduce the problem**

I have added a failing test in the  `populate-link-route-page-and-query-even-if-data-exists` branch: https://github.com/frontity/frontity/blob/populate-link-route-page-and-query-even-if-data-exists/packages/wp-source/src/__tests__/actions.tests.ts#L82-L98

**Possible solution**

Change the logic of `fetch` at this point: https://github.com/frontity/frontity/blob/populate-link-route-page-and-query-even-if-data-exists/packages/wp-source/src/actions.ts#L32 so it doesn't matter if data exists or not.

Use the https://github.com/frontity/frontity/tree/populate-link-route-page-and-query-even-if-data-exists branch.

**Comment by luisherranz** [comment]
@SantosGuillamot test mention.

**Comment by orballo** [comment]
~@luisherranz Can I work on this? I'm relying on this fields for infinite scroll to work~
Nevermind, I just saw that it's in progress already

**Comment by luisherranz** [comment]
Can you rebase your work onto the `source-fetch-force-true-bug` (https://github.com/frontity/frontity/pull/389) branch until this is merged?

**Comment by orballo** [comment]
I'm already building upon two other branches: `use-connect` and `use-in-view`.
I can still develop over the home route. That one works fine, so it shouldn't be a problem, it will work just fine with other routes once this is fixed.
