### ISSUE TITLE
Unexpected URL should return 404 page [5pt]

### ISSUE THREAD

**Issue by concalahan** [frontity/frontity#366]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org
- There is a related issue (https://github.com/frontity/frontity/issues/290), closed in favor of this one.

**Expected behavior**

Some URL should return 404 instead of 500.

**Observed behavior**

My Google Search Console report that the server is return 500.

![bug](https://i.imgur.com/wR87Zuf.png)

For example: 
https://stream-hub.com/undefined/nap-he-dieu-hanh
https://stream-hub.com/kiem-tra-toc-do-mang/kiem-tra-toc-do-mang

When I run at localhost, the message is somehow unclear to me.

![localhost](https://i.imgur.com/P3KED29.png)

The actual error in development is this one:
```
  TypeError: Cannot read property 'split' of undefined
      at __webpack_exports__.default.str (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:107)
      at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:10:205)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

The error is thrown in the following line because `type` is undefined:
https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/handlers/postType.ts#L46 

**Steps involved to reproduce the problem**

Navigate at link http://localhost:3000/undefined/nap-he-dieu-hanh

https://gitlab.com/concalahan/stream-hub-frontity

**Info about your system**

**Possible solution**

It's a problem in the `@frontity/wp-source` package, specifically in the `postType` handler, but it's also happening with every handler that has a similar pattern (like for categories).

We can either:

* Add here a condition that would check if the fetched link and the link of the received post are the same:
  https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/handlers/postType.ts#L38

* Change the pattern for that handler to make it more restrictive (right now, the pattern would match almost every link) and let `actions.router.fetch` to throw a 404 error when #331 has been implemented.

---

Thank you very much :D

**Comment by DAreRodz** [comment]
We are taking a look at this issue. Thanks for reporting, @concalahan. :slightly_smiling_face:

**Comment by DAreRodz** [comment]
The error you posted seems like a temporary network error, but I tested your project locally running `npx frontity dev` and it's actually failing. This is the error I received, could you confirm that you are getting the same error?

```
  TypeError: Cannot read property 'split' of undefined
      at __webpack_exports__.default.str (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/utils/capitalize.ts:2:107)
      at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:10:205)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by concalahan** [comment]
Yes, it is.

![bug](https://i.imgur.com/HSpZrj5.png)

**Comment by DAreRodz** [comment]
Thanks, @concalahan!

It seems to be a problem with the handler that fetches posts. That handler actually finds a post getting the post's slug from the URL, even tho that URL is not a valid one. After that, the handler fails trying to get data from the store using the invalid URL.

I'm going to mark this as a bug. :beetle: 

We'll let you know when it's fixed!

**Comment by luisherranz** [comment]
@DAreRodz is this related to https://github.com/frontity/frontity/issues/331?

**Comment by DAreRodz** [comment]
@luisherranz, not in this case, I think.

What is happening here is that the `postType` handler is matching the link and getting the post slug from it, even when the link is wrong.

For example, it would match both links and get the same slug (`nap-he-dieu-hanh`):
* https://stream-hub.com/nap-he-dieu-hanh
* https://stream-hub.com/undefined/nap-he-dieu-hanh (wrong link)

For the second one, it will fail in [this line](https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/handlers/postType.ts#L46), when the handler is trying to get `type` and `id` using the wrong link.

We can either:
* make the handler throw a 404 error when it detects that the fetched link and the post link are not the same, or
* change the pattern for that handler to make it more restrictive (right now, [the pattern](https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/patterns/wp-org.ts#L64) would match almost every link) and let `fetch` to throw a 404 error when #331 has been implemented.

**Comment by luisherranz** [comment]
Oh, I see, thanks @DAreRodz. Then I think it's related to this one https://github.com/frontity/frontity/issues/290 right?

**Comment by DAreRodz** [comment]
Yes, that one is related, actually.

PS: I've updated the links to the lines of code in #290, now they point to the specific commit when the issue was open.

**Comment by luisherranz** [comment]
Awesome.

Do you think we need both issues or only one of them is necessary?

**Comment by DAreRodz** [comment]
One issue is enough, I'll close #290 and keep a reference to it here. Apart from that, I think we have to review the priority again, (I'm going to leave the `awaiting-priority` label on).

**Comment by luisherranz** [comment]
Great, thanks @DAreRodz.

**Comment by michalczaplinski** [comment]
There's another person reporting the same issue in the forum: https://community.frontity.org/t/error-in-capitalize/1238/10

@SantosGuillamot Do you want to bump up the priority on this one?

**Comment by SantosGuillamot** [comment]
>@SantosGuillamot Do you want to bump up the priority on this one?

I took a look at our own Google Search Console and it seems it's happening something similar with mars theme. If you go to https://mars.frontity.org/iceland (it's supposed to be https://mars.frontity.org/2016/iceland), you get an Internal Server Error instead of a 404.

As previously mentioned, I've run a quick test and just checking if the fetched link and the current link match, solves the problem. Adding something like this to[ this line of code](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/postType.ts#L31): 
```js
if (populated.length > 0 && populated[0].link === route) {
  isHandled = true;
  break;
}
```

@DAreRodz Is there any problem with that approach?

**Comment by DAreRodz** [comment]
The only thing would be that you may want to support links with queries, in the case you added a utm campaign or something similar.

For that comparison, I would use the path from `route`:

```ts
const { path } = libraries.source.parse(route);

​if​ (​populated​.​length​ ​>​ ​0​ ​&&​ populated[​0​].​link​ ​===​ path) {
  isHandled ​=​ ​true​;
  ​break​;
}
```

**Comment by Koli14** [comment]
I also have this problem. My home page is set to` "/kezdooldal"` (homepage in hungarien). If somebody visits my site like: `mysite.com/`, then it's working of course, but if I visit `mysite.com/kezdooldal`, then I get the error above. Although I set in `frontity.setting.js` for  `@frontity/wp-source` my homepage to "/kezdooldal".

**Comment by Koli14** [comment]
An other case, Google find, when the url contains a special character, like `♯` -> https://szinhaz.online/%E2%99%AFegyuttsirunk-tovabbra-is-fizet-szineszeinek-a-golem-szinhaz/

**Comment by luisherranz** [comment]
> but if I visit mysite.com/kezdooldal then I get the error above.

Isn't that the way it is supposed to work? Your page is not a page anymore, but the home. What does WordPress in that case? A redirect?

> An other case, Google find, when the url contains a special character

I guess that is a separete bug, isn't it? If so, would you mind opening a new bug?

**Comment by Koli14** [comment]
> What does WordPress in that case? A redirect?

Yes, it's redirect to the home.

> I guess that is a separete bug, isn't it? If so, would you mind opening a new bug?

I will! Thanks!

**Comment by SantosGuillamot** [comment]
I'm going to bump up the priority of this bug as it could affect the SEO and it's happening to more users. For example -> https://community.frontity.org/t/my-personal-blog-site/1962
