### ISSUE TITLE
301 response when fetching posts

### ISSUE THREAD

**Issue by mody-ydom** [frontity/frontity#373]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

when uploading image to the media and then use it as featured image in a post everything should be normal

**Observed behavior**

the end point `/wp-json/wp/v2/posts?_embed=true` redirects to the uploaded image instead of the json of the posts

but if we remove the `_embed=true` part it works again

**Steps involved to reproduce the problem**

you actually dont need frontity project

all you need is a wordpress with these two plugins
- [REST API – Head Tags v1.1.2](https://wordpress.org/plugins/rest-api-head-tags/) 
- [Yoast SEO v13.4.1](https://wordpress.org/plugins/wordpress-seo/)

1. open media tab
2. upload an image
3. create new post and add this image as a featured image
4. save the post
5. go to the endpoint `/wp-json/wp/v2/posts?_embed=true` 

**Possible solution**

any of these alone will fix it

- disable REST API – Head Tags
- disable Yoast and then re-enable it
- upload the image from the featured image dialog within the post itself NOT from the media tab
- remove `_embed=true` from the endpoint

**Comment by mody-ydom** [comment]
I don't know if this is the right place to report issues related to wp-plugins

**Comment by mody-ydom** [comment]
I created one in the right place I think so I will close this one in favor for the other ticket
https://github.com/frontity/wp-plugins/issues/28

**Comment by luisherranz** [comment]
Yes, the other repo is the right place, thanks @mody-ydom :)
