### ISSUE TITLE
Release GitHub action not working

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#386]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When you merge to `master` the PR created by [this GitHub Action](https://github.com/frontity/frontity/blob/dev/.github/workflows/release.yml), it should do the release of the packages automatically.

**Observed behavior**

It doesn't do the release because the GitHub action is failing at [this point](https://github.com/frontity/frontity/runs/615078678?check_suite_focus=true#step:6:12). It seems like the `&&` isn't understood by the CLI.

This is the error:
```sh
$ npx changeset publish && git checkout dev && git rebase master && git push origin dev
resize:  can't open terminal /dev/tty
tput: No value for $TERM and no -T specified
🦋  error Too many arguments passed to changesets - we only accept the command name as an argument
```

**Comment by luisherranz** [comment]
Fixed in https://github.com/frontity/frontity/commit/f22432ceefac97caf8cf8da6aedf9bad4c49efb9. 

I have removed the git rebase because it won't work anyway, `dev` is a protected branch.
