### ISSUE TITLE
Add ENV variables for the build, dev and serve commands. [3pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#394]
**Feature:** [Change publicPath](https://community.frontity.org/t/change-publicpath/1461).
**User Story**: Change the publicPath at build time.

[**Sprint Card**](https://github.com/orgs/frontity/projects/4#card-36476088)

**Comment by luisherranz** [comment]
Blocked because of https://github.com/frontity/frontity/pull/458#issuecomment-639382307.

**Comment by luisherranz** [comment]
Unblocked based on the decision made at https://community.frontity.org/t/change-publicpath/1461/13.
