### ISSUE TITLE
SmartAd component [5pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#401]
**Feature:** [Smart Adserver](https://community.frontity.org/t/smart-adserver/1586).
**User Stories**: 
  - Create fills (see [Slot and Fill](https://community.frontity.org/t/slot-and-fill/895))with ad components.
  - Use the Ad component directly.

[**Sprint Card**](https://github.com/orgs/frontity/projects/4#card-37072939)

**Comment by DAreRodz** [comment]
Hey, I just saw that the `SmartAd` component is already being implemented in this PR: https://github.com/frontity/frontity/pull/569

@michalczaplinski, I'll assign this issue to you and move it to **In progress**.

**Comment by michalczaplinski** [comment]
> Hey, I just saw that the `SmartAd` component is already being implemented in this PR: #569
> 
> @michalczaplinski, I'll assign this issue to you and move it to **In progress**.

👍 thanks @DAreRodz !
