### ISSUE TITLE
Frontity CLI fails silently when passing a --typescript flag [5pt]

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/frontity#407]
**Expected behavior**

`npx frontity create --typescript my-app` should create a new project with typescript enabled.

**Observed behavior**

```
npx frontity create --typescript my-app
``` 
exits without an error message and not even creating a a project folder. However, 
```
npx frontity create my-app --typescript
``` 
works fine. The problem is the order of the flags.

**Steps involved to reproduce the problem**

```
npx frontity create --typescript my-app
```

**Possible solution**

1. A solution should ensure that: 
  - `frontity create` accepts the `--typescript` flag **before** the name of the new project.
  -  Alternatively, we could only accept the options **after** the `create` keyword and throw 
2. We need to check which other commands / CLI options are affected
3. Update the CLI help (if necessary), for the moment it shows:
```
Commands:
  create [options] [name]          Creates a new Frontity project.
  create-package [options] [name]  Creates a new Frontity package in a project.
```

But at the moment the if the `[options]` come **before** `[name]` the command fails.

**Comment by luisherranz** [comment]
I have a question due to my lack of knowledge of CLIs in general.

Isn't `name` in the case of `cmd --arg name` the value of `arg`? I'm asking because, for example:

```bash
> npx frontity dev --port 3000 --target es5
```

How would the CLI determine that neither `3000` or `es5` are not the values of `port` and `target` but of the `name` of the `dev` command?

Is that the normal behavior? Is this somehow a missconfiguration of `--typescript` in [`commander`](https://www.npmjs.com/package/commander) that should be intelligent enough to know that `--typescript` is a boolean and doesn't have a value so `name` must belong to `create`?

**Comment by michalczaplinski** [comment]
I had to refresh my knowledge here a bit as well 😄 

There are three types of command line argument: positional arguments, named arguments, and flags.

- A positional argument is a bare value, and its position in a list of arguments identifies it. LIke `create` and `app-name` in `npx frontity create app-name`
- A named argument is a (key, value) pair, where the key identifies the value. Like `--port 3000`
- A flag is a stand-alone key, whose presence or absence provides information to the application. Like `--typescript`

If the CLI encounters a `--someArgument` (in whatever position), it knows that it's either a named argument or a flag.

I'm not sure if this answers your question, but the bottom line is that the CLI should be "intelligent" enough to know that if it encounters `--someArgument <value>`,  the `<value>` should be interpreted as a the value of the named argument.

Actually commander.js mentions it in the docs: https://github.com/tj/commander.js/#options
> Options on the command line are not positional, and can be specified before or after other command arguments.

**Comment by michalczaplinski** [comment]
I had to refresh my knowledge here a bit as well 😄 

There are three types of command line argument: positional arguments, named arguments, and flags.

- A positional argument is a bare value, and its position in a list of arguments identifies it. LIke `create` and `app-name` in `npx frontity create app-name`
- A named argument is a (key, value) pair, where the key identifies the value. Like `--port 3000`
- A flag is a stand-alone key, whose presence or absence provides information to the application. Like `--typescript`

If the CLI encounters a `--someArgument` (in whatever position), it knows that it's either a named argument or a flag.

I'm not sure if this answers your question, but the bottom line is that the CLI should be "intelligent" enough to know that if it encounters `--someArgument <value>`,  the `<value>` should be interpreted as a the value of the named argument.

Actually commander.js mentions it in the docs: https://github.com/tj/commander.js/#options
> Options on the command line are not positional, and can be specified before or after other command arguments.

**Comment by luisherranz** [comment]
Awesome, thanks for the explanation @michalczaplinski.

So, if I understood correctly, this seems like a missconfiguration of `--typescript`, which is a flag and not a named argument because it shouldn't "absorb" `app-name` when used this way:

```
npx frontity create --typescript my-app
```

Is that right?

**Comment by michalczaplinski** [comment]
> So, if I understood correctly, this seems like a missconfiguration of --typescript, which is a flag and not a named argument because it shouldn't "absorb" app-name when used this way:

From the looks of it, `--typescript` should be just a boolean flag when we configure it as we do:
 https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/frontity/src/cli/index.ts#L51-L52

So the issue is different, I think. I ll have to take a deeper look

**Comment by luisherranz** [comment]
Oh, ok. Thanks @michalczaplinski.

**Comment by juanmaguitar** [comment]
There's this option in `create-package` that seems to do nothing → https://community.frontity.org/t/purpose-of-no-prompt-option-in-frontity-create-package-command/1820

**Comment by cristianbote** [comment]
Had a closer look into why this is happening and the `--typescript` flag and `name` value are parsed correctly, meaning I can see their value reflected in the `create` function. What is happening is that we have the `program.help()` if there are no arguments based on `program.args.length` check in here:

https://github.com/frontity/frontity/blob/9d54e33d05ce4ab3a2077a11e8e804d7b192dcc0/packages/frontity/src/cli/index.ts#L101

Now, we could tackle this in two ways:

1. Even though `program.args` has no length, I guess dues to a bug in commander, the `program.rawArgs` does have the arguments. So something like:
```js
// If the args are parsed and available and rawArgs contain any arguments
if (!program.args.length && program.rawArgs.length < 3) program.help();
```

2. Update `commander`. We currently rely on version `2.x.x` and the latest version of `commander` is `6.x.x`. Tried it locally and these are backward compatible. Tried to scrape through their release notes and did not notice anything that caught my eye.

Safest in my opinion is version 2. But, I do not know the whole in and outs of the cli commands and if there are custom things that we are doing and are not that straight forward to migrate away.

**Comment by cristianbote** [comment]
I believe @luisherranz has this covered in this opened PR to update dependencies, in here https://github.com/frontity/frontity/pull/640/files#diff-27828c6f14cb3a24214abe1c3c83a99564fcefd57a79074313239712599a63cbR46.

**Comment by cristianbote** [comment]
This one got fixed I believe, in this PR https://github.com/frontity/frontity/pull/640

**Comment by SantosGuillamot** [comment]
Is there a way to ensure if this has been fixed or do we have to wait until the next release to test it?

**Comment by cristianbote** [comment]
I don't think we can programatically, via a test, check for this, sadly 😞. This was an issue in the `commander` package, that is in charge of parsing the `argv` and it got fixed in the next versions. So using an updated version of `commander` is what ensures that this issue is fixed.

Otherwise only by manually testing it I am afraid.

**Comment by luisherranz** [comment]
I've just tested this locally in `dev` (which has now commander v6) and it seems to be working fine, as Cristian said 🙂

<img width="572" alt="Screenshot 2021-01-26 at 17 51 42" src="https://user-images.githubusercontent.com/3305402/105876327-295a1200-5fff-11eb-88d6-8fe0cbfc69d9.png">

We can test it tomorrow again once it's published in npm and if it works we can close the issue.

**Comment by SantosGuillamot** [comment]
I've tested this after the latest release and it's working now :clap: I'm closing the issue.
