### ISSUE TITLE
Scroll restoration when going back in history doesn't work in Firefox

### ISSUE THREAD

**Issue by orballo** [frontity/frontity#427]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When clicking on a post in a Frontity site and then going back to the archive, the scroll should be restored properly.

**Observed behavior**

The scroll only restores to a certain point, and if you had scrolled down the Antelope Canyon post on home, when you visit a post and come back, the scroll will restore to the wrong point.

**Steps involved to reproduce the problem**

You can reproduce this issue visiting https://mars.frontity.org and https://twentytwenty.frontity.org.

**Info about your system**

## System:
 - OS: macOS 10.15.3
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 7.36 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
 - npm: 6.14.4 - ~/.nvm/versions/node/v12.13.1/bin/npm
## Browsers:
 - Chrome: 81.0.4044.138
 - Edge: Not Found
 - Firefox: 76.0
 - Safari: 13.0.5
## npmPackages:
 - @changesets/changelog-github: ^0.1.1 => 0.1.1 
 - @changesets/cli: ^2.4.0 => 2.4.0 
 - @types/jest: ^24.0.25 => 24.9.1 
 - @typescript-eslint/eslint-plugin: ^2.0.0 => 2.0.0 
 - @typescript-eslint/parser: ^2.0.0 => 2.0.0 
 - cross-env: ^5.2.1 => 5.2.1 
 - eslint: ^6.2.2 => 6.2.2 
 - eslint-import-resolver-typescript: ^2.0.0 => 2.0.0 
 - eslint-plugin-cypress: ^2.6.1 => 2.6.1 
 - eslint-plugin-import: ^2.18.2 => 2.18.2 
 - eslint-plugin-jest: ^22.15.2 => 22.15.2 
 - eslint-plugin-jsx-a11y: ^6.2.3 => 6.2.3 
 - eslint-plugin-react: ^7.14.3 => 7.14.3 
 - husky: ^1.3.1 => 1.3.1 
 - jest: ^24.9.0 => 24.9.0 
 - lerna: ^3.15.0 => 3.15.0 
 - lint-staged: ^8.1.4 => 8.1.4 
 - memo-parser:  0.2.0 
 - prettier: ^2.0.1 => 2.0.2 (1.19.1)
 - ts-jest: ^24.0.2 => 24.3.0 
 - typescript: ^3.8.2 => 3.8.2 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

No idea.

**Comment by luisherranz** [comment]
@orballo, can you still reproduce this error?
