### ISSUE TITLE
Write error handler for `frontity` when `@frontity/core` is not installed

### ISSUE THREAD

**Issue by orballo** [frontity/frontity#43]
Currently this is handled within the `dev`, `build` and `serve` commands.
But, now that we need to use `ts-node` in order to import `frontity.settings.ts` we should check before `ts-node` is required and throws.

**Comment by luisherranz** [comment]
![Screen Shot 2019-05-22 at 13 28 22](https://user-images.githubusercontent.com/3305402/58171110-7d8ee980-7c95-11e9-8f38-282097980315.png)

👆 isn't this already solved?

**Comment by orballo** [comment]
It looks like it is solved.
