### ISSUE TITLE
`npx frontity create-package <packageName> --no-prompt` should not prompt user for input

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/frontity#434]
**Expected behavior**
When running `frontity create-package <packageName> --no-prompt`, it should not prompt user for any input but use the defaults for the package namespace.

**Observed behavior**

Despite the flag, the CLI still prompts the user for input: 

```
⬢  npx frontity create-package my-custom-theme --no-prompt
? Enter the namespace of the package: theme
✔ Adding package.json.
✔ Adding src/index.js.
✔ Installing package my-custom-theme.

New package "my-custom-theme" created.

⬢  npx frontity create-package my-custom-theme2
? Enter the namespace of the package: theme
✔ Adding package.json.
✔ Adding src/index.js.
✔ Installing package my-custom-theme2.

New package "my-custom-theme2" created.
```

**Steps involved to reproduce the problem**
```
> npx frontity create my-app
> cd my-app
my-app> npx frontity create-package my-package --no-prompt
```

**Possible solution**

The `create-package` command should take into account the default value for the package namespace

**Comment by luisherranz** [comment]
@michalczaplinski I have assigned @SantosGuillamot to add priority to this. You can do so yourself next time 🙂

**Comment by SantosGuillamot** [comment]
I'd consider this `priority: medium` as it's something pretty confusing but I think it's not a big deal. Is it affecting somehow the Frontity CLI apart from the user experience? Would you consider this a `good-first-issue`?

**Comment by luisherranz** [comment]
> Would you consider this a good-first-issue?

I think it's a bit difficult. What do you think @michalczaplinski?

**Comment by michalczaplinski** [comment]
I don't think it's a good first issue mostly because testing this is not straightforward for a beginner. I would say `priority: medium` sounds about right to me.

**Comment by SantosGuillamot** [comment]
Great, let's keep it like that then :+1:

**Comment by michalczaplinski** [comment]
The exact issue is not that complicated actually, I think. 

We just need add a check here: https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/frontity/src/cli/create-package.ts#L80-L80 to make sure that we are checking that `promptUser` is true before we ask for the namespace. 

We are doing already doing something similar e.g in the `create` command here: https://github.com/frontity/frontity/blob/0636532b948a8a8aaaca2a25c9b89b5ea4891b97/packages/frontity/src/cli/create.ts#L51-L53 so we could copy this pattern.

The question now is: What is a reasonable default for the value of `namespace` when running `frontity create-package my-package-name --no-prompt`? I think the most reasonable behaviour would be to just throw an error if the either `name` or `namespace` are not provided and say that you need to provide `name` and `namespace` when running with `--no-prompt`.

**Comment by michalczaplinski** [comment]
> But writing the fix, I'm wondering if name is really mandatory when --no-prompt option is set, as the code provides a default value for it : "my-frontity-project".
Let me know. I'll adjust the code and the tests following your answer.

@luisherranz @DAreRodz Would you like to weigh in here?

I think that the most reasonable behaviour would be to require the user to provide both the `--name` and `--namespace` when running with `--no-prompt`. I feel like having a default that is not transparent to the user is not a good idea. Some might not even realize that there is a default at all.

> As i'm fixing both, #434 and #538 do you wish a PR by issue or only one for both?

No preference, whatever makes more sense to review together 🙂

**Comment by luisherranz** [comment]
I agree with @michalczaplinski.

@hexaltation, please get rid of the `my-frontity-project` default to avoid confusion 🙂

By the way, the logic it should follow is represented by the graph found in https://docs.frontity.org/frontity-cli/environment-variables – [(Image)](https://gblobscdn.gitbook.com/assets%2F-LZ-alQBwUYv-HkbN8zV%2Fsync%2F0e42f79d4b3ba53518fae46167d349135cb00cb1.png?alt=media)

**Comment by luisherranz** [comment]
@hexaltation I'm currently working on a PR that affects those files so I think I can do the fix myself. I'll let you know if I finally fix it 🙂

**Comment by luisherranz** [comment]
It will be fixed in https://github.com/frontity/frontity/pull/545. I left `--namespace` as optional for now.
