### ISSUE TITLE
Add action to create new comments [13pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#439]
**Feature:** [WordPress comments package](https://community.frontity.org/t/wordpress-comments-package/1267).
**User Story**: Call an action to post a new comment.

[**Sprint Card**](https://github.com/orgs/frontity/projects/6#card-38657393)

**Comment by DAreRodz** [comment]
Blocked. See https://github.com/frontity/frontity/pull/495#issuecomment-645242084

**Comment by DAreRodz** [comment]
I wrote an [implementation proposal](https://community.frontity.org/t/wordpress-comments-package/1267/41) for the missing part so I removed the `blocked` tag.

I'm going to start with the implementation anyways, but if you don't agree with some things of my proposal we can change them on the progress.

Any feedback is welcome. :slightly_smiling_face:

**Comment by SantosGuillamot** [comment]
As we have to implement it in a different way, and the current one isn't working, I reopen the issue.

**Comment by luisherranz** [comment]
@SantosGuillamot any idea why this is not closed?

**Comment by SantosGuillamot** [comment]
Mmm I think it wasn't closed because in the [Pull Request](https://github.com/frontity/frontity/pull/542) that solved this, it was linked after the PR got merged, so the automation didn't work.

I am closing it now.
