### ISSUE TITLE
Internal Server Error on POSTS ONLY using Chakra UI

### ISSUE THREAD

**Issue by warlockeg** [frontity/frontity#442]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Frontity Chakra Theme should work with posts.

**Observed behavior**

Posts page should open but instead its showing INTERNAL SERVER ERROR.

The following error appears in the logs:

```
TypeError: Cannot read property '96' of undefined
      at Post (webpack-internal:///./node_modules/frontity-chakra-theme/src/components/post/post.js:23:1812)
      at runAsReaction (webpack-internal:///./node_modules/@frontity/connect/src/reactionRunner.js:16:45)
      at reaction (webpack-internal:///./node_modules/@frontity/connect/src/observer.js:7:131)
      at eval (webpack-internal:///./node_modules/@frontity/connect/src/connect.js:18:8)
      at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:397:2319)
      at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:396:122)
      at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:1199)
      at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:55)
      at renderToString (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:470:116)
      at eval (webpack-internal:///./node_modules/@frontity/core/src/server/index.tsx:46:243)
```

**Steps involved to reproduce the problem**

You need to use Chakra UI theme and this issue will happen, it wont happen with other themes.

**Related topic in the community**

- https://community.frontity.org/t/internal-server-error-on-posts-only-using-chakra-ui-442/1913/

**Comment by DAreRodz** [comment]
Thanks for opening the issue, @warlockeg! Taking a look at it right now.

**Comment by DAreRodz** [comment]
Hey @warlockeg, could you share the content of your `frontity.settings.js` file? Just to reproduce the issue.

**Comment by warlockeg** [comment]
> Hey @warlockeg, could you share the content of your `frontity.settings.js` file? Just to reproduce the issue.

```js
const settings = {
  name: "visit-guide",
  state: {
    frontity: {
      url: "https://www.visit.guide",
      title: "دليل السفر",
      description: "دليل المسافر العربي",
    },
  },
  packages: [
    {
      name: "frontity-chakra-theme",
      state: {
        theme: {
          // The logo can be a text or an image url
          logo: "دليل السفر",
          // show background pattern
          showBackgroundPattern: false,
          // show social links
          showSocialLinks: false,
          // the top-level navigation labels and links

          menu: [
            ["الرئيسية", "/"],
            ["وجهات", "/category/destinations/"],
            ["مصر", "/category/egypt/"],
            ["شرم الشيخ", "/category/egypt/sharm-el-sheikh/"],
            ["القاهرة", "/category/egypt/cairo/"],
          ],

          // the social links
          socialLinks: [
            ["pinterest", "https://www.pinterest.com/frontity/"],
            ["facebook", "https://www.instagram.com/frontity/"],
            ["twitter", "https://www.twitter.com/frontity/"],
          ],

          // color shades to use in the blog
          colors: {
            primary: {
              "50": "#e9f5f2",
              "100": "#d4dcd9",
              "200": "#bbc3be",
              "300": "#a1aba5",
              "400": "#87938b",
              "500": "#6d7972",
              "600": "#555f58",
              "700": "#323c34",
              "800": "#232924",
              "900": "#272727",
            },
            accent: {
              "50": "#ede4d3",
              "100": "#fbe3b2",
              "200": "#f6d086",
              "300": "#f1be58",
              "400": "#eca419",
              "500": "#d49212",
              "600": "#a5710b",
              "700": "#775105",
              "800": "#483100",
              "900": "#1d0f00",
            },
          },
        },
      },
    },
    {
      name: "@frontity/wp-source",
      state: {
        source: {
          api: "https://www.visit.guide/wp-json",
        },
      },
    },
    "@frontity/tiny-router",
    "@frontity/html2react",
    "@frontity/head-tags",
  ],
};

export default settings;
```

**Comment by DAreRodz** [comment]
Hi again @warlockeg!

Well, this is actually a bug, not in Frontity but in `frontity-chakra-theme`.

The problem is that authors in your site don't have avatars and thus they are missing the property `avatar_urls` when they come from the REST API. Then, the Chakra theme fails in this line trying to read the property `"96"` from `author.avatar_urls`, given the error you mentioned above.

https://github.com/chakra-ui/frontity-chakra-ui-theme/blob/master/packages/frontity-chakra-theme/src/components/post/post.js#L71

If you created your frontity project using `npx frontity create --theme frontity-chakra-theme`, and you have the theme code in `packages/frontity-chakra-theme` you can modify the code and remove the image prop as it is not needed in your case.

Anyways, it would be a good idea if you open an issue in the Chakra theme repository so it would be fixed for everybody: https://github.com/chakra-ui/frontity-chakra-ui-theme

Cheers! :wave: 

---

PS: to get help it is better if you go first to our community: https://community.frontity.org

**Comment by DAreRodz** [comment]
I just saw that you opened a topic in the community. Let's continue the conversation there!

https://community.frontity.org/t/internal-server-error-on-posts-only-using-chakra-ui-442/1913/
