### ISSUE TITLE
publicPath option not working with absolute urls

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#445]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Users should be able to use absolute urls for WebPack publicPath.

**Observed behavior**

It returns and Internal Server Error. 

After running `npx frontity dev --publicPath="https://externaldomain.com/static" I get the following message:
```
AssertionError [ERR_ASSERTION]: mount path must begin with "/"
      at mount (webpack-internal:///./node_modules/koa-mount/index.js:14:90)
      at app.use (webpack-internal:///./node_modules/@frontity/core/src/server/index.tsx:28:372)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
After running the same in `build` I get this one:
```
AssertionError [ERR_ASSERTION]: mount path must begin with "/"
      at e.exports (/home/mario/Desktop/Code/Frontity/frontity.org/build/server.js:47:21764)
      at t.default.t.use (/home/mario/Desktop/Code/Frontity/frontity.org/build/server.js:230:15093)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Steps involved to reproduce the problem**

* Create a new Frontity project
* Run the command ``npx frontity dev --publicPath="https://externaldomain.com/static"`

**Comment by luisherranz** [comment]
@DAreRodz I'd say, extract the path instead of removing it, just in case someone sets it as an external domain but points to the Frontity installation.

**Comment by DAreRodz** [comment]
I'm not sure I've understood you. You mean get the path from the external URL and use it to mount the static files instead of not mounting the files?

**Comment by luisherranz** [comment]
Yes, that's it :)
