### ISSUE TITLE
Missing terms from source.tag that are assigned to the current post

### ISSUE THREAD

**Issue by igmoweb** [frontity/frontity#497]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Whenever a single post is displayed, all tags/categories in it should be also loaded in `source.tag`

**Observed behavior**

This doesn't seem to be the case. Sometimes (pretty randomly at a first glance at least). There seem to be some sort of, race condition? that makes `source.tag` or `source.category` missing some of the tags that are assigned to the current post in `post.tags` or `post.category`

**Steps involved to reproduce the problem**

I think it's difficult to test it but I've left a piece of code here that should help: https://github.com/igmoweb/igmoweb.com/blob/tags-debug/packages/igmoweb-theme/src/components/single/post-tags.js#L22-L33 so you'll need to download my project.

Once, you are using my project and **switched to `tags-debug` branch**, follow these steps:

1. Go to the main page `localhost:3000` and open the Chrome Dev Tools.
2. Most of the times, you need to go fast: Do a hard refresh in the homepage (Cmd + Shift + R), then click on a post that will trigger the error, in my site, this is a good one as it contains several tags:
![Captura de pantalla 2020-06-15 a las 13 19 29](https://user-images.githubusercontent.com/1516569/84651843-dff30180-af0a-11ea-9d19-18bd928c5471.png)
3. If any of the tags are `undefined`, the source tab should stop at the `debugger;` line. I've solved this error in the `master` branch so make sure that you are in `tags-debug`.
4. If it doesn't stop, go back to the homepage, hard refresh and click on the same post again, try to do it as fast as you can. After 3-4 attempts you should see the error.

Worths mentioning that it always happens with the same tag and that I haven't installed the dev Frontity version to do a proper debug (I really haven't had time though I'd like to and this seems like a time-consuming issue).

**Info about your system**

```
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
 - Memory: 319.46 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
## Browsers:
 - Chrome: 83.0.4103.97
 - Edge: Not Found
 - Firefox: 77.0.1
 - Safari: 12.1.2
## npmPackages:
 - @fortawesome/fontawesome-svg-core: ^1.2.28 => 1.2.28 
 - @fortawesome/free-brands-svg-icons: ^5.13.0 => 5.13.0 
 - @fortawesome/free-regular-svg-icons: ^5.13.0 => 5.13.0 
 - @fortawesome/free-solid-svg-icons: ^5.13.0 => 5.13.0 
 - @fortawesome/react-fontawesome: ^0.1.10 => 0.1.10 
 - @frontity/core: ^1.7.0 => 1.7.0 
 - @frontity/html2react: ^1.3.3 => 1.3.3 
 - @frontity/tiny-router: ^1.2.0 => 1.2.0 
 - @frontity/twentytwenty-theme: ^1.2.0 => 1.2.0 
 - @frontity/wp-source: ^1.7.1 => 1.7.1 
 - @wordpress/components: ^9.8.0 => 9.7.0 
 - @wordpress/date: ^3.9.0 => 3.9.0 
 - @wordpress/prettier-config: ^0.2.0 => 0.2.0 
 - babel-eslint: ^10.1.0 => 10.1.0 
 - eslint: ^7.2.0 => 6.8.0 
 - eslint-config-prettier: ^6.11.0 => 6.11.0 
 - eslint-config-wordpress: ^2.0.0 => 2.0.0 
 - eslint-plugin-prettier: ^3.1.4 => 3.1.4 
 - eslint-plugin-react: ^7.20.0 => 7.20.0 
 - eslint-plugin-react-hooks: ^4.0.4 => 4.0.4 
 - eslint-plugin-sort-destructure-keys: ^1.3.4 => 1.3.4 
 - frontity: ^1.8.0 => 1.8.0 
 - frontity-social-previews: ^1.0.1 => 1.0.1 
 - highlight.js: ^10.1.0 => 10.1.0 
 - highlightjs-line-numbers.js: ^2.8.0 => 2.8.0 
 - igmoweb-theme: ./packages/igmoweb-theme => 1.0.0 
 - lodash: ^4.17.15 => 4.17.15 
 - polished: ^3.6.5 => 3.6.5 
 - pretty-quick: ^2.0.1 => 2.0.1 
 - prismjs: ^1.20.0 => 1.20.0 
 - react-ga: ^3.0.0 => 2.7.0 
 - react-share: ^4.2.0 => 4.2.0 
 - wp-prettier:  1.19.1 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found
```

**Possible solution**

The problem is that `populate` doesn't recognize different terms with the same ID: https://github.com/frontity/frontity/issues/497#issuecomment-644689264

We didn't expet that situation to happen in `wp.org` but it's something that `wp.com` does for its sites.

We must add different schemas for categories and tags or change all the schemas implementation.

This is the current schema for taxonomies:

- [packages/wp-source/src/libraries/schemas/taxonomies.ts](https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/schemas/taxonomies.ts)

**Comment by DAreRodz** [comment]
Hi, @igmoweb :wave:

Thanks for opening this issue, I'm looking at it right now.

**Comment by DAreRodz** [comment]
I thought it could be related to the WordPress REST API limitation that only adds up to ten entities for each kind of embedded entity (i.e. attachments, categories, tags, etc.), but you only have 6 tags for that post, right? :thinking: 

I'll try to reproduce the problem with the steps you described.

**Comment by luisherranz** [comment]
Maybe the race condition is with the fetch of the `"/page/2"`? It's the only thing that is changing after CSR. But that would mean that the fetch of `"/"` hasn't included the tag, which is wrong.

**Comment by igmoweb** [comment]
@luisherranz @DAreRodz Did you manage to reproduce it? I don't think it has anything to do with pagination, the issue doesn't happen during switching pages but just when fetching certain terms and it always happen with the same term. 

There is another case where some categories are missing from the categories list. I think I've seen it while loading this post https://igmoweb.com/2020/06/01/headless-wordpress-con-frontity-react-y-wordpress-com/ but it's not happening anymore though sometimes the `JavaScript` category wasn't appearing, I think it could be the same issue, however, my categories component [was checking already](https://github.com/igmoweb/igmoweb.com/blob/2dbe2f465baef0905eee2cdbd9e7ed7da06edae0/packages/igmoweb-theme/src/components/single/post-categories.js#L23-L25) if the category was `falsey` or not, so I wasn't getting the same error, it was just that the category wasn't appearing

**Comment by luisherranz** [comment]
Oh, no, I don't mean this has something to do with pagination, but if it is a race condition maybe it is related to the fetch of page 2, which is done after your homepage loads: https://public-api.wordpress.com/wp/v2/sites/igmoweb.com/posts?_embed=true&page=2

Hypothetically, the tag wouldn't be included in the homepage fetch (https://public-api.wordpress.com/wp/v2/sites/igmoweb.com/posts?_embed=true&page=1) but in the page-2 fetch, and for that reason sometimes it appears and sometimes it doesn't.

Maybe this is not the reason but I can't think of any other possible race condition right now.

**Comment by DAreRodz** [comment]
I was able to reproduce it but I don't know what's causing the problem yet. Still investigating. :mag:

**Comment by DAreRodz** [comment]
I think I've found the problem (almost 99% sure) :beetle: 

There are two terms with the same id in your blog:

![2020-06-16_12-20](https://user-images.githubusercontent.com/6917969/84762999-d8476180-afcb-11ea-81b7-747f060f214f.png)

In `wp-source` the same schema is used to normalize all taxonomies that come from the WP REST API in the moment that `libraries.source.populate` is executed. If both terms with the same id are included in the same REST API response, the normalization will take only one of them as the term with that id.

It just so happens that for the first page of the home (`"/"`) it is the category the one included in the state and for the second page (`"/page/2"`) is the tag. That's why it doesn't work until the request for the second page has finished.

I'm going to check if I'm right, but it looks like a bug for sure!

**Comment by DAreRodz** [comment]
Confirmed.

This is the code failing: 

https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/populate.ts#L41-L46

This is what happens when `libraries.source.populate` is called with the first page:

- The parsed response is stored in `json`. Both terms with id `209196` are included.
- The `normalize` call returns the `entities` object, which contains a prop called `taxonomyEntities`. The terms included in the response are stored there by ID. Now, only the category with id `209196`  is included.

**Comment by igmoweb** [comment]
@DAreRodz Thanks for the investigation. It seems that .com shares terms IDs with the same slug. I don't see this happening in a .org install. Is there any workaround in Frontity to treat them different?

**Comment by igmoweb** [comment]
Here's another sample:

https://public-api.wordpress.com/wp/v2/sites/igmoweb.com/categories/457
https://public-api.wordpress.com/wp/v2/sites/igmoweb.com/tags/457

And this was the category that was missing sometimes from the category list.

Now, why does this happen just sometimes?

**Comment by DAreRodz** [comment]
> Is there any workaround in Frontity to treat them different?

I don't think so, unless you use your own implementation of `libraries.source.populate`. :slightly_frowning_face: 

> Now, why does this happen just sometimes?

It must be related with `populate` adding one term or another depending on their position in the REST API response.

When Frontity fetches any list of posts (regardless of whether it is a post archive, a category, a tag, etc.) the fetch request includes `_embed=true` that tells WP to add all the entities that are related to each post (its author, categories, tags...) in the response.

I guess, when `populate` normalizes that response

https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/populate.ts#L43-L46

the last (or the first) term found with a specific ID is the one returned inside `entities`, and the one added to the state.

As the term added could change depending on the response, a missing term could be added later with a different request.

**Comment by DAreRodz** [comment]
@SantosGuillamot would you set the priority for this bug? :slightly_smiling_face:

**Comment by SantosGuillamot** [comment]
As it's only affecting WP.com, and it's a pretty specific case where you have to name the category and the tag with the same slug, I'd label it as medium priority.

@DAreRodz Could you share your thoughts about how to solve it here?

**Comment by DAreRodz** [comment]
I would solve this adding two new schemas (`categoryEntity` and `tagEntity`) before `taxonomyEntity`.

https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/schemas/index.ts#L19

That way, when calling the `normalize` function inside `populate`, here:

https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/populate.ts#L43-L46

instead of returning `entities` with `taxonomyEntity`, which is a map with all taxonomies by ID (thus failing when a taxonomy and a tag have the same ID), it will contain also `categoryEntity` and `tagEntity`. Then, we  would have to replace this line

https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/wp-source/src/libraries/populate.ts#L75

by something like

```ts
      } else if (
        schema === "taxonomyEntity" ||
        schema === "categoryEntity" ||
        schema === "tagEntity"
      ) {
```
