### ISSUE TITLE
babel-plugin-lodash not working in node

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#5]
`babel-plugin-lodash` works great in the client but for some reason, I can't make it work in node.

The import comes from this line: https://github.com/smooth-code/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L4

But it ends up with the whole lodash bundle inside `main.node.js`:
<img width="200" alt="screen shot 2019-03-06 at 13 35 59" src="https://user-images.githubusercontent.com/3305402/53881799-db0b8680-4014-11e9-92fe-774e1fa6f602.png">

**Comment by DAreRodz** [comment]
Working on that!

**Comment by luisherranz** [comment]
I've made a PR to loadable-components because that's the package importing the whole `lodash` to at least solve this for the moment:
https://github.com/smooth-code/loadable-components/pull/298

They've just merged it :)

**Comment by luisherranz** [comment]
This is about to be solved by this PR: https://github.com/frontity/frontity/pull/456
