### ISSUE TITLE
Frontity fails if custom package name starts with numbers.

### ISSUE THREAD

**Issue by nicholasio** [frontity/frontity#524]
**_Bug report_**
Frontity does not work with package names such as `@10up/frontity-elasticpress` even though it is a valid npm package.

![image](https://user-images.githubusercontent.com/6104632/88456200-2284f380-ce52-11ea-8053-78f7a2f1ccf8.png)

**Expected behavior**

Any valid npm package name would work.

**Observed behavior**

Valid npm packages that start with a number does not work with frontity.

**Steps involved to reproduce the problem**

**Info about your system**

**Possible solution**

I think the solution can be as simple as prefixing all packages with a valid variable name prefix when referencing them:

`import frontity_package_{normalized_package_name} from "@npm/package-name`

**Comment by DAreRodz** [comment]
Hello, @nicholasio.

I think it is a problem with JavaScript language, not Frontity. When you import packages in JavaScript, what it happens is that you assign a name to the module object you are importing, and that name must be a [valid variable name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Variables), not a valid package name, so it cannot start with a number.

From the MDN guides:

> A JavaScript identifier must start with a letter, underscore (_), or dollar sign ($). Subsequent characters can also be digits (0–9).

To fix that, you can modify the `10up__frontity_elasticpress_default` name so it starts with `_10up`, `ten_up`, `tenUp`, etc. Whatever you want (as long as it doesn't start with a number :wink:).

**Comment by nicholasio** [comment]
@DAreRodz the `10up__frontity_elasticpress_default` was generated by frontity, not me, If I were importing this manually I could just use a valid variable name, but I believe frontity is generating those imports dynamically based on the packages included in frontity.settings.js.

So I don't think this is a problem with the JavaScript language, it's just frontity that is not ensuring those import statements are valid.

**Comment by DAreRodz** [comment]
Oops, sorry @nicholasio, I've closed the issue too fast. I hadn't noticed that those imports are written by Frontity when generating the bundles. :sweat_smile:

I guess it should be easy to fix, though.

**Comment by luisherranz** [comment]
Uh, I didn't know scopes starting with numbers were possible :)

I've done a PR to fix this: https://github.com/frontity/frontity/pull/525

**Comment by nicholasio** [comment]
Thanks for the quick fix @luisherranz
