### ISSUE TITLE
e2e tests for the Google Analytics package fail in a random way

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#535]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

*NOTE: This is not exactly a bug because the code seems to be fine but it prevents some PRs to be merged as it randomly makes e2e workflows to fail, having to re-run workflows until the tests pass.*

**Expected behavior**

The e2e tests for the Google Analytics package should pass as expected if the code is fine.

**Observed behavior**

They fail sometimes in a random way.

**Steps involved to reproduce the problem**

It can be reproduced in a local environment:

- Clone the `frontity` repo.
- Go to `e2e` and run `npm run e2e:open`.
- Once the Cypress app is open, run google-analytics spec file.
- Re-run that spec until it fails (it can take a long time).

**Possible solution**

I found out that the problem is the implementation of the e2e tests. I assumed that the `analytics.js` library always uses an `Image` element to create the request to Google Analytics. The thing is that it sometimes does an `XMLHTTPRequest` instead of using an `Image` and, as the tests are not expecting that case, it fails.

We could mock an `analytics.js` function instead of `Image` constructor for these tests.

**Comment by DAreRodz** [comment]
Just mention that I did some tests in this PR: https://github.com/frontity/frontity/pull/532, but I didn't try to change the implementation of the tests yet.

**Comment by SantosGuillamot** [comment]
Do we know how often are these tests randomly failing?

**Comment by DAreRodz** [comment]
They were failing quite often during the last week.

**Comment by SantosGuillamot** [comment]
I'll mark it as `high` then. If it's blocking all the Pull Request I guess we'll have to consider it `critical`.

**Comment by luisherranz** [comment]
> I assumed that the analytics.js library always uses an Image element to create the request to Google Analytics. The thing is that it sometimes does an XMLHTTPRequest instead of using an Image

Nice catch! 🙂

**Comment by luisherranz** [comment]
I'll take care of this.
