### ISSUE TITLE
Cannot fetch subcategories in category page

### ISSUE THREAD

**Issue by mymakarim** [frontity/frontity#539]
I have a website [https://componentity.com](https://componentity.com), where in the category page [https://componentity.com/category/tailwindcss/](https://componentity.com/category/tailwindcss/) I want to show subcategories in the sidebar. I could not find a way to do it!

github: [https://github.com/componentity/componentity-website](https://github.com/componentity/componentity-website)

**Comment by luisherranz** [comment]
Hey @mymakarim, we've moved all the questions to the community forum. That way, other community members can learn or answer them. Please open a thread in the [Dev Questions](https://community.frontity.org/c/dev-talk-questions/3) category 🙂
