### ISSUE TITLE
Expose the HTML template, the render function and the App in libraries. [5pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#557]
This is part of the [AMP feature](https://community.frontity.org/t/amp-package/388/). For full context please check out the [final Implementation proposal](https://community.frontity.org/t/amp-package/388/10?u=santosguillamot).

---

## HTML template

The Google AMP framework needs a specific HTML template because a normal HTML document doesn't validate.

For that reason, the `@frontity/amp` package needs to be able to overwrite the hardcoded HTML template.

This can be done with a `beforeSSR` function but needs the `template` to be exposed in `libraries.frontity`.

## Render to Static Markup

The Google AMP framework doesn't need the custom `data-` attributes added by React, so instead of using `renderToString`, the `@frontity/amp` package needs to make Frontity use `renderToStaticMarkup`.

This can be done with a `beforeSSR` function. It'll be necessary to create a separate `server.js` file because we don't want to add `react-dom/server` to the client bundle.

```js
// packages/amp/src/server.js
import { renderToStaticMarkup } from "react-dom/server";

export default {
  actions: {
    amp: {
      beforeSSR: ({ libraries }) => {
        libraries.frontity.render = renderToStaticMarkup;
      },
    },
  },
};
```

It needs the `render` function to be exposed in `libraries.frontity`.

**Comment by luisherranz** [comment]
@SantosGuillamot I've just noticed that the Sprint Card links get outdated. Maybe that's another good option to remove them in favor of the Feature Boards (the less work the better).

**Comment by SantosGuillamot** [comment]
You are totally right. They change per project and we usually move them from 1 project to another, so it would be better handle in a GitHub board.
