### ISSUE TITLE
Overwrite the HTML template. [5pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#558]
This is part of the [AMP feature](https://community.frontity.org/t/amp-package/388/). For full context please check out the [final Implementation proposal](https://community.frontity.org/t/amp-package/388/10?u=santosguillamot).

---

The Google AMP framework needs a specific HTML template because a normal HTML document doesn't validate.

For that reason, the `@frontity/amp` package needs to be able to overwrite the hardcoded HTML template.

This can be done with a `beforeSSR` function but needs the `template` to be exposed in `libraries.frontity`.

```js
// packages/amp/src/index.js
import ampTemplate from "./templates/amp";

export default {
  actions: {
    amp: {
      beforeSSR: ({ libraries }) => {
        libraries.frontity.template = ampTemplate;
      },
    },
  },
};
```

The template should be something like this: https://github.com/frontity/frontity/blob/31d34e4d16042ebc73b4c30a9f53dfae36c633a2/packages/core/src/server/templates/amp.ts

**Comment by luisherranz** [comment]
Blocked until #685 and #557 are finished.

**Comment by SantosGuillamot** [comment]
This issue wasn't closed automatically after merging the linked [Pull Request](https://github.com/frontity/frontity/pull/722) because we merged it in a branch different than `dev`, so I'm closing this manually.
