### ISSUE TITLE
Move all the CSS to the <head>. [5pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#559]
This is part of the [AMP feature](https://community.frontity.org/t/amp-package/388/). For full context please check out the [final Implementation proposal](https://community.frontity.org/t/amp-package/388/10?u=santosguillamot).

---

The Google AMP framework requires that all the CSS is placed in a `<style>` tag of the head.

For that reason, the `@frontity/amp` package needs to use Emotion's `extractCritical` API and move the extracted CSS to the `<head>`.

This can be done with a `beforeSSR` function. It'll be necessary to create a separate `server.js` file because we don't want to add `create-emotion-server` and `react-dom/server` to the client bundle.

```js
// packages/amp/src/server.js
import { CacheProvider } from "@emotion/core";
import createEmotionServer from "create-emotion-server";
import createCache from "@emotion/cache";
import { renderToStaticMarkup } from "react-dom/server";
import ampTemplate from "./templates/amp";

export default {
  actions: {
    amp: {
      beforeSSR: ({ libraries }) => {
        // Create an Emotion instance for this SSR.
        const cache = createCache();
        const { extractCritical } = createEmotionServer(cache);

        libraries.frontity.render = (App) => {
          // Add the Provider to the App.
          App = (
            <CacheProvider value={cache}>
              <App />
            </CacheProvider>
          );

          // Run extract critical.
          const { html, css, ids } = extractCritical(
            libraries.frontity.render(App)
          );

          // Replace the template injecting the CSS in the `<head>`.
          libraries.frontity.template = ampTemplate(css, ids);

          return html;
        };
      },
    },
  },
};
```

We also need to be able to add the `CacheProvider` to the client. That can be done with a `beforeCSR` function.

```js
// packages/amp/src/client.js
import createCache from "@emotion/cache";

export default {
  actions: {
    amp: {
      beforeCSR: ({ libraries }) => {
        const cache = createCache();

        libraries.frontity.App = () => (
          <CacheProvider value={cache}>
            <libraries.frontity.App />
          </CacheProvider>
        );
      },
    },
  },
};
```

For context, this is the way Emotion worked in Frontity at first. This is the final commit, including a fix for the `Global` component: https://github.com/frontity/frontity/commit/e8c3430

After that, we removed `extractCritical` because both labels and source maps don't work with that approach. Now it's up to the `@frontity/amp` package add `extractCritical` again for AMP sites. This is where I removed that approach: https://github.com/frontity/frontity/commit/d5af653

Looking at the new docs it seems to me that we don't need to do a separate `hydrate()` on the ids anymore, as they are present in the `data-emotion-css` attribute of the `style` tag:

```js
<style data-emotion-css="${ids.join(' ')}">${css}</style>
```

More info about the `extractCritical` approach on https://emotion.sh/docs/ssr#advanced-approach

**Comment by cristianbote** [comment]
I started working on this but this is blocked by #557. The changes needs to happen in the AMP package not in core.

**Comment by SantosGuillamot** [comment]
As #557 was closed, I am unblocking this.
