### ISSUE TITLE
Change the render to be renderToStaticMarkup. [3pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#560]
This is part of the [AMP feature](https://community.frontity.org/t/amp-package/388/). For full context please check out the [final Implementation proposal](https://community.frontity.org/t/amp-package/388/10?u=santosguillamot).

---

The Google AMP framework doesn't need the custom `data-` attributes added by React, so instead of using `renderToString`, the `@frontity/amp` package needs to make Frontity use `renderToStaticMarkup`.

This can be done with a `beforeSSR` function. It'll be necessary to create a separate `server.js` file because we don't want to add `react-dom/server` to the client bundle.

```js
// packages/amp/src/server.js
import { renderToStaticMarkup } from "react-dom/server";

export default {
  actions: {
    amp: {
      beforeSSR: ({ libraries }) => {
        libraries.frontity.render = renderToStaticMarkup;
      },
    },
  },
};
```

It needs the `render` function to be exposed in `libraries.frontity`.

**Comment by luisherranz** [comment]
Blocked until #685 and #557 are finished.

**Comment by SantosGuillamot** [comment]
This issue wasn't closed automatically after merging the linked [Pull Request](https://github.com/frontity/frontity/pull/722) because we merged it in a branch different than `dev`, so I'm closing this manually.
