### ISSUE TITLE
URL class imported from `frontity` throws an error in Safari 13.1.2

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#565]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When you use the URL constructor exported by the `frontity` package (1.11.0), the expected behavior is that the constructor returns an URL instance at the same time it gives the following warning:

```
Importing `URL` from Frontity has been deprecated. Please use `new URL()` instead.

Visit https://community.frontity.org for help! 🙂
```

**Observed behavior**

It works just fine in Chrome and Node, but in Safari 13.1.2 (not tested in previous versions) if you run `new URL()` with valid URLs it throws an error with only the following message:

```
TypeError: Type error
```

This is the stack trace:

![Screen Shot 2020-09-10 at 10 43 05](https://user-images.githubusercontent.com/6917969/92704979-a425d780-f353-11ea-9d93-218453e96a8f.png)

Some updated packages that depend on `URL` were not published in the last release (e.g. `@frontity/wp-source`) so they will throw an error using the latest version of `frontity` (see [Mobile Error // Unhandled Promise Rejection - can’t read the WP REST API](https://community.frontity.org/t/mobile-error-unhandled-promise-rejection-cant-read-the-wp-rest-api/2830)).

**Steps involved to reproduce the problem**

1. Create any Frontity project using `npx frontity create`
2. Access the Frontity site from Safari (13.1.2)
3. As the `URL` constructor fails with a valid URL, you will see the following error in console (thrown in [this line](https://github.com/frontity/frontity/blob/4502e7d70e92e67ef9fbe99ee77da90beeeb0c33/packages/wp-source/src/actions.ts#L118)), which makes Frontity stop working completely:
   ```
   Rejection: Error: Add the URL of your WordPress REST API in state.source.api.
   ```

**Info about your system**

```
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
 - Memory: 637.44 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 12.13.1 - /usr/local/bin/node
 - npm: 6.12.1 - /usr/local/bin/npm
## Browsers:
 - Chrome: 85.0.4183.102
 - Edge: Not Found
 - Firefox: Not Found
 - Safari: 13.1.2
## npmPackages:
 - @babel/preset-react: ^7.9.4 => 7.10.4 
 - @babel/types: ^7.9.5 => 7.11.5 
 - @frontity/analytics: ^1.2.0 => 1.2.0 
 - @frontity/connect: ^1.1.3 => 1.1.3 
 - @frontity/core: ^1.7.3 => 1.8.0 
 - @frontity/google-ad-manager: ^0.1.0 => 0.1.0 
 - @frontity/google-analytics: ^1.2.0 => 1.2.0 
 - @frontity/google-tag-manager-analytics: ^1.0.0 => 1.0.0 
 - @frontity/head-tags: ^1.0.5 => 1.0.5 
 - @frontity/html2react: ^1.3.5 => 1.3.5 
 - @frontity/lazyload: ^1.0.12 => 1.0.12 
 - @frontity/now: ^1.2.0 => 1.2.0 
 - @frontity/tiny-router: ^1.2.1 => 1.2.1 
 - @frontity/twentytwenty-theme: ./packages/twentytwenty-theme => 1.1.1 
 - @frontity/wp-source: ^1.8.1 => 1.8.1 
 - @types/youtube: 0.0.39 => 0.0.39 
 - algoliasearch: ^4.4.0 => 4.4.0 
 - babel-plugin-macros: ^2.8.0 => 2.8.0 
 - babel-plugin-tailwind-components: ^0.5.10 => 0.5.10 
 - frontity: ^1.10.1 => 1.11.0 
 - frontity-contact-form-7: ^0.1.7 => 0.1.7 
 - react-elastic-carousel: ^0.6.7 => 0.6.7 
 - react-headroom: ^3.0.0 => 3.0.0 
 - react-id-swiper: ^4.0.0 => 4.0.0 
 - react-instantsearch: ^6.7.0 => 6.7.0 
 - react-instantsearch-dom: ^6.7.0 => 6.7.0 
 - react-intersection-observer: ^8.26.2 => 8.28.3 
 - react-mailchimp-subscribe: ^2.1.0 => 2.1.0 
 - react-reading-progress: ^0.3.0 => 0.3.0 
 - react-share: ^4.2.1 => 4.2.1 
 - react-spring: ^8.0.27 => 8.0.27 
 - react-youtube: ^7.11.2 => 7.12.0 
 - styled-components: ^5.1.1 => 5.2.0 (2.4.1)
 - styled-components/macro:  undefined ()
 - styled-components/native:  undefined ()
 - styled-components/primitives:  undefined ()
 - swiper: ^5.4.5 => 5.4.5 
 - tailwind.macro: ^1.0.0-alpha.10 => 1.0.0-alpha.10 
 - tailwindcss: ^1.4.6 => 1.8.6 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found
```

**Possible solution**

We can release all the updated packages that were using `URL` so they don't depend on the `URL` class exported by `frontity` anymore.

The problem would be with those developers that imports `URL` from `frontity` in their packages because it will fail in Safari instead of showing a deprecation notice, so maybe we have to fix the [`FrontityURL` implementation](https://github.com/frontity/frontity/blob/2bdf7dbe44fec3b0c08aae7175bee76d47811a41/packages/frontity/src/utils/url.ts) and make it work for that browser as well.

I don't know how that fix could be, though.

**Comment by luisherranz** [comment]
> maybe we have to fix the FrontityURL implementation and make it work for that browser as well.

Yes, that is what we have to do.

**Comment by luisherranz** [comment]
@SantosGuillamot, I've marked this as critical and I'll take care of the fix 👍

**Comment by DAreRodz** [comment]
I realized that if you call `new URL("http://some.url", undefined)` in Chrome and Node it works, but not in Safari:

![Screen Shot 2020-09-10 at 12 06 07](https://user-images.githubusercontent.com/6917969/92717069-f10fab00-f35f-11ea-9a45-fc223b3f4cf0.png)

That should be the reason our `FrontityURL` fails (in [this line](https://github.com/frontity/frontity/blob/2bdf7dbe44fec3b0c08aae7175bee76d47811a41/packages/frontity/src/utils/url.ts#L33))!

**Comment by luisherranz** [comment]
@DAreRodz has discovered the problem.

So instead of this:

```js
super(input, base);
```

We have to do this:

```js
base ? super(input, base) : super(input);
```

I'm going to do the PR and also add changesets for our packages that were still using the URL import from Frontity to avoid the warnings.
