### ISSUE TITLE
Actions Fetch Force Parameter Not Respected in wp-source Package

### ISSUE THREAD

**Issue by jonobr1** [frontity/frontity#577]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Setting the `force` parameter to `true` when fetching a post type should make it to be fetched again.

**Observed behavior**

The parameter seems to be ignored and the post is not fetched.

**Possible solution**

This [line](https://github.com/frontity/frontity/blob/114bd4bbe87c99d4384a5fb3eb338ae6d72b67a0/packages/wp-source/src/libraries/handlers/postType.ts#L52) in `postType.ts` doesn't take `force` into account when trying to fetch new data from a post or page. I discovered this in [this thread](https://community.frontity.org/t/how-to-render-password-and-then-protected-posts/2938/12?u=jonobr1) when trying to call `actions.source.fetch(url, { force: true });` on password protected pages.

I believe a simple fix could be amending line 52 to:
```javascript
if (!state.source.get(route).id || force) {
```
But, I don't know `wp-source` well enough to know if that would be the correct amendment. This is why I'm filing at as an issue instead of a PR.

**Comment by DAreRodz** [comment]
Hey, @jonobr1 :wave: 

You are right, this is actually a bug and the fix would be as simple as you mentioned. If you want, you can create a PR and link it to this issue. :blush:

EDIT: I've changed a bit the issue to match our bug template.

**Comment by luisherranz** [comment]
@jonobr1 this is our contribution guide https://docs.frontity.org/contributing/code-contribution-guide, but if you need help let us know! 🙂

**Comment by jonobr1** [comment]
Sweet, will do!

**Comment by jonobr1** [comment]
Thanks for offering to help @luisherranz. I think I need it, because changing that one line breaks the `"overwrites the data when fetched with { force: true }"` test in [post-type.tests.ts](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/__tests__/post-type.tests.ts#L223-L235). In my debugging what I've found is:

```jsx
// Fetch entities
await store.actions.source.fetch("/post-1");
await store.actions.source.fetch("/post-1", { force: true });
```
These two calls invoke `libraries.source.api.get` on [line 64](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/handlers/postType.ts#L64-L67) of `postType.ts`. While their arguments are identical, the resulting `response` objects are different. In the first `response` the api gets the post information and things move along fine, but the second time the `response` yields an attachment _not_ a post and so the test fails because both `store.action.source.fetch` calls expect `'/post-1'` to resolve as a post and not an attachment.

Maybe it's as simple as modifying how the mock data is populated in the test, but something tells me that perhaps there's something more problematic lurking.

**Comment by michalczaplinski** [comment]
Hi @jonobr1! I've just tried to apply your fix and to fix that test case quickly and it looks like that test case was incorrect previously and this is the reason that you've been seeing the failure! Thanks for pointing this out! 🙂 

I ll make a new PR with the fix

**Comment by jonobr1** [comment]
Awesome! Thanks and glad I could help 👍
