### ISSUE TITLE
Emotion support for autoLabel and sourceMaps

### ISSUE THREAD

**Issue by orballo** [frontity/frontity#58]
It should work by default according to [docs](https://emotion.sh/docs/@emotion/babel-preset-css-prop), but for some reason I can't make it work.

To check after the beta release.

**Comment by luisherranz** [comment]
Related: https://emotion.sh/docs/labels

Although this issue should solve the `autoLabel: true` feature, which, if I'm not mistaken, adds the name of the component at the end of the css class, like `1fpk7dx-Link`.

**Comment by luisherranz** [comment]
Source maps don't work either.

**Comment by luisherranz** [comment]
Fixed in https://github.com/frontity/frontity/pull/227
