### ISSUE TITLE
Remove /amp from link in actions.source.fetch and state.source.get [3pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#586]
This is part of the [AMP feature](https://community.frontity.org/t/amp-package/388/). For full context please check out the [final Implementation proposal](https://community.frontity.org/t/amp-package/388/10?u=santosguillamot).

---

There are three standard ways to use AMP. This package needs to support all of them.

1. Using a subdomain, like `https://amp.mydomain.com/some-post`.
2. Using a query parameter, like `https://www.mydomain.com/some-post?amp=true`.
3. Using an extra folder in the path, like `https://www.mydomain.com/some-post/amp`.

1 and 2 are fine because the slug used by `@frontity/wp-source` will be `some-post`, but 3 is not.

We need to make this action and derived state point to `/some-post/`:

```js
actions.source.fecth("/some-post/amp");
state.source.get("/some-post/amp");
```

Ideally, this should be done with hooks, but we don't have hooks yet and they seem too much to make them a dependency of this feature right now.

We've been searching for a workaround but the only thing that seems feasible right now is to hardcode a replacement in the normalize function and change it once we have hooks.

```js
export const normalize = (route: string): string => {
  route = route.replace(/\/amp$/, "");
  return paramsToRoute(routeToParams(route));
};
```

This will need to contain a bit more logic to avoid some known URLs that shouldn't be changed, like:

- A page called amp: `/amp`.
- A category/tag called amp: `/category/amp` or `/tag/amp`.

**Comment by luisherranz** [comment]
Blocked because this is finally going to be done in the `@frontity/amp` package so we have to wait until https://github.com/frontity/frontity/issues/685 is done.
