### ISSUE TITLE
`actions.source.fetch` fails with links with query params for certain handlers [5pt]

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#596]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

Let's say we have these two handlers, one for `movie` entities and another for `movie` attachments:
```ts
[
  {
    pattern: "/movie/:movieSlug/:slug",
    name: "movie attachment",
    func: () => { ... },
    priority: 10,
  },
  {
    pattern: "/movie/:slug",
    name: "movie",
    func: () => { ... },
    priority: 10,
  },
]
```

**Expected behavior**

When doing
```ts
actions.source.fetch("/movie/the-terminator/?query=string")
```

you may expect that the `movie` handler is the one that matches.

**Observed behavior**

It is not only that the `movie attachment` handler is matched but also the `getMatch()` call fails because the params that `getMatch()` returns are extracted from the pathname and not from the query, which [is being removed](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/get-match.ts#L20-L22) before getting those params, thus making the link not to match anymore with the matched pattern from `movie attachment` and throwing the following error in this line:
 and the following error is thrown (in [this line](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/get-match.ts#L24)):

```
TypeError: Cannot read property 'slice' of null
```
The data object for that link ends being:

```ts
{
  isFetching: true,
  isReady: false,
  link: "/movie/the-terminator/?query=string",
  page: 1,
  query: { query: "string" },
  route: "/movie/the-terminator/",
}
```

**Steps involved to reproduce the problem**

1. `npx frontity create`.
2. Add the handlers mentioned above to `libraries.source.handlers` in /packages/mars-theme/index.js
3. Add the link `"/movie/the-terminator/?query=string"` to the menu in /frontity.settings.js
4. `npx frontity dev` and click on that link.
4. In the console you will see `TypeError: Cannot read property 'slice' of null`.
5. The theme will just show the loading bar.

**Possible solution**

I'm not sure how to solve this, actually.

As a workaround, users just would have to add a trailing slash to their handler patterns.

**Comment by luisherranz** [comment]
Thanks David. This is the test to reproduce the issue:

```js
it("should match the correct handler and not be confused by the query", () => {
      expect(
        getMatch("/some-type/some-post/?query=string", [
          {
            pattern: "/some-type/:postSlug/:attachmentSlug",
            name: "some-type attachment",
            func: () => {},
            priority: 10,
          },
          {
            pattern: "/some-type/:slug",
            name: "some-type",
            func: () => {},
            priority: 10,
          },
        ]).name
      ).toBe("some-type");
    });
  })
```

Now that we have regexp patterns for queries maybe we could exclude the query from the `link` for patterns.

https://github.com/frontity/frontity/blob/7e99b9b4a7d1bb8d3e02d3b7bce587bb8f400bee/packages/wp-source/src/libraries/get-match.ts#L78

**Comment by luisherranz** [comment]
We have to use `link.replace(/\?.*/, "")` in this line

https://github.com/frontity/frontity/blob/7e99b9b4a7d1bb8d3e02d3b7bce587bb8f400bee/packages/wp-source/src/libraries/get-match.ts#L78

to match what we are doing in

https://github.com/frontity/frontity/blob/7e99b9b4a7d1bb8d3e02d3b7bce587bb8f400bee/packages/wp-source/src/libraries/get-match.ts#L19-L23

I think that would solve the issue. @darerodz, do you agree?

**Comment by DAreRodz** [comment]
Almost that, but we would have to remove the query only for those regexps generated by `pathToRegexp`.

https://github.com/frontity/frontity/blob/7e99b9b4a7d1bb8d3e02d3b7bce587bb8f400bee/packages/wp-source/src/libraries/get-match.ts#L75

Something like this:

```ts
.find(({ regexp, pattern }) =>
  pattern.startsWith("RegExp:")
    ? regexp.test(link)
    : regexp.test(link.replace(/\?.*/, ""))
);
```

We want the query to be evaluated for regular regexps, right?

Anyway, maybe we should refactor how `result` is computed and, instead of mapping over the whole list of handlers and generate all regexps first we could just generate and evaluate them one by one.

**Comment by luisherranz** [comment]
Absolutely. Thanks for the correction David!

**Comment by luisherranz** [comment]
I have been thinking a bit about this because we are also using the `"RegExp:"` pattern in the new 30x redirections and I think we should match the RegExp against `link` instead of `route`:

- Pattern: `/category/:slug` -> Match against `route` (without pagination).
- RegExp: `RegExp:\\/category\\/(?<slug>[^\\/])\\/page\\/(?<page>\\d+)` -> Match against the whole `link` inlucing the pagination.

The reason is that the _Pattern_ is our "Simple-to-use API" and the _RegExp_ is our "Hackable API", so we better pass it all the information, not just a part.

So I think that we should also make that change when we fix this bug.

Actually, we are now matching the _Pattern_ against `route` and `queryString`, which doesn't make much sense because we have the _RegExp_ for the queries:

```js
getMatch(`${route}${queryString}`, handlers);
```

So I would pass `route` and `link` to the `getMatch` function and just use `route` for patterns and `link` for regexps.
