### ISSUE TITLE
`data.isHome` is not working for front pages since wp-source@1.9.0

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#598]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When the [`state.source.homepage` option](https://docs.frontity.org/api-reference-1/wordpress-source#state-source-homepage) of the `wp-source` package is set, the `isHome` property of the homepage should be `true` as expected.

**Observed behavior**

It returns `undefined` instead.

**Steps involved to reproduce the problem**

Thread in the community describing the issue: https://community.frontity.org/t/data-ishome-is-not-working-since-update/3039

**Possible solution**

It's a bug that sneaked into the commit https://github.com/frontity/frontity/commit/bdfeaace7823507314e3782b48887cf837bd11a2#diff-b4f2e2daaa31ef8b04cffb39926c83c1L71, when we fixed `isHome` for handlers that use regex patterns. The variable `route` used to check if the page being fetched is the homepage is modified when the `homepage` option is set because it uses an internal redirection to trigger the `postTypeHandler` instead of the `postArchiveHandler`. Instead of using `route` directly, we should use `source.data[link].route` for that check.

**Comment by luisherranz** [comment]
Totally my fault. Thanks for the fix @DAreRodz!!
