### ISSUE TITLE
The search form doesn't work when using a static homepage

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#602]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

There is an on-going conversation in the community about this: https://community.frontity.org/t/bug-on-search-after-having-some-handlers/2921

**Expected behavior**

The search form should just work fine when setting a static homepage in `state.source.homepage`.

**Observed behavior**

It doesn't work, and searches only show the static homepage.

**Steps involved to reproduce the problem**

Described in the community: https://community.frontity.org/t/bug-on-search-after-having-some-handlers/2921

**Possible solution**

We could modify the `<SearchForm>` component in `/src/components/search/search-form.js` so it uses `state.source.postsPage` when building the link with the search query.

```ts
// Let's go search for blogs that match the search string
actions.router.set(
  `${state.source.postsPage || "/"}?s=${searchString.toLowerCase()}`
);
```

That way the handler executed is the one for the post archive, which already has the logic for searches.

---

That fix would work, but we should match the WordPress behavior anyway and support searches from the root link (`/`) as well. That would be a bit difficult right now because of redirections.

**Comment by luisherranz** [comment]
As part of the design principles we should avoid undefined settings. So I think we should populate `state.source.postPage` with `"/"` by default. That way people could simply use `state.source.postPage` when they refer to the post type archive in places like this:

```js
actions.router.set(`${state.source.postsPage}?s=${searchString.toLowerCase()}`);
```

> That fix would work, but we should match the WordPress behavior anyway and support searches from the root link (/) as well. That would be a bit difficult right now because of redirections.

Maybe we can solve it by adding a search handler for the `?s=` parameter?

```js
const searchHandler = {
  name: "search",
  pattern: "RegExp:(\\?|&)s=(?<search>[^&$]+)",
  priority: 5,
  // ...
};
```

**Comment by DAreRodz** [comment]
That would be ideal, but there is an unexpected tiny problem. :sweat_smile: 

The redirection system we implemented in `wp-source` is being used for static homepages, so, when `state.source.homepage` is set, and you want to match the homepage with the `searchHandler`, you have to use the page slug in its pattern, which is totally weird...

**Comment by DAreRodz** [comment]
OK, Luis and I had a conversation and we decided that the best solution here is not to modify `@frontity/twentytwenty-theme` but change the pattern we are adding for the "homepage" redirection in `@frontity/wp-source` by one that doesn't match if the search query param (`/?s=some+search`) is present.

This is the line we must change:

https://github.com/frontity/frontity/blob/a845b77479a3639d0e8baab0e819ff5469a207e3/packages/wp-source/src/actions.ts#L213

We can create a RegExp pattern for this.

**Comment by SantosGuillamot** [comment]
Thanks for the triage guys :slightly_smiling_face: Do you think we could consider this a `good-first-issue`? Would it make sense to ask the person having this problem for a contribution?

**Comment by luisherranz** [comment]
I think that understanding how those internal redirections work is kind of complex. I had to ask David several times to explain them to me 😆

**Comment by SantosGuillamot** [comment]
Oh okay! I thought it was just creating a proper RegExp :smile:

**Comment by SantosGuillamot** [comment]
Btw, is this affecting any theme with a search form?

**Comment by cristianbote** [comment]
Was looking into this one and tried to get deeper a bit into it.

If I understood the flow correctly, the _fetch_ is initiated at this level, with the url:
https://github.com/frontity/frontity/blob/a845b77479a3639d0e8baab0e819ff5469a207e3/packages/twentytwenty-theme/src/components/index.js#L22

Which calls the curried `.get` on the `wpSource` package to get the data:
https://github.com/frontity/frontity/blob/a845b77479a3639d0e8baab0e819ff5469a207e3/packages/wp-source/src/state.ts#L5

Which then calls `actions.source.fetch()`
https://github.com/frontity/frontity/blob/a845b77479a3639d0e8baab0e819ff5469a207e3/packages/wp-source/src/actions.ts#L78
and based on the redirection the `handler.func` is called and awaited.

So in my humble opinion, the fix is to pass the complete route, as we do to the actions handlers a few lines below.

```js
const redirection = getMatch(`${route}${queryString}`, redirections);
```

And then we could make the pattern match the root homepage.
```js
    if (homepage) {
      const pattern = `RegExp:^${concatLink(subdirectory)}$`;
      redirections.push({
        name: "homepage",
        priority: 10,
        pattern,
        func: () => concatLink(homepage),
      });
    }
```

What are your thoughts? 🤔

**Comment by luisherranz** [comment]
> If I understood the flow correctly, the fetch is initiated at this level, with the url:
> ...
> Which calls the curried .get on the wpSource package to get the data:
> ...
> Which then calls actions.source.fetch()

Not exactly, `state.source.get` doesn't initiate the `fetch` 🙂

We try to follow [Flux](https://facebook.github.io/flux/) as much as possible, so only actions can trigger state changes.

The initiator is `actions.router.set(link)`. The router has a setting called `state.router.autoFetch` (which is `true` by default) that calls `actions.source.fetch(link)` automatically. Something like this: 

![image](https://user-images.githubusercontent.com/3305402/105872367-a0d97280-5ffa-11eb-8226-94ace3a59e4c.png)


---

> So in my humble opinion, the fix is to pass the complete route, as we do to the actions handlers a few lines below.

Yes, that's right. And now that is better handled thanks to your last PR (https://github.com/frontity/frontity/pull/676) we can simply modify the `homepage` redirection and use a regular expression that doesn't match if the search query is present (`?s=`) 🙂
