### ISSUE TITLE
Frontity doesn't "recognize" the source of data if the route is NOT 100% lower case

### ISSUE THREAD

**Issue by nandotess** [frontity/frontity#604]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

If my request (Frontity) is **/book/ABC**, I expect to see the same result when I request **/book/abc**.

**Observed behavior**

A page not found is loaded. WordPress is loading the correct content, but the condition on line 83 of `node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts file` makes this fails (=== condition where the source is **/book/ABC** and the populated link is **/book/abc**.

**Steps involved to reproduce the problem**

Try to access any existing page/post on WordPress with upper case letters on the request/URL.

**Info about your system**

```
## System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
 - Memory: 33.72 GB / 64.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.0 - /usr/local/bin/node
 - npm: 6.14.4 - /usr/local/bin/npm
## Browsers:
 - Chrome: 86.0.4240.80
 - Edge: Not Found
 - Firefox: 81.0
 - Safari: 14.0
## npmPackages:
 - @frontity/core: ^1.9.0 => 1.9.0 
 - @frontity/html2react: ^1.4.0 => 1.4.0 
 - @frontity/mars-theme: ./packages/mars-theme => 1.4.3 
 - @frontity/tiny-router: ^1.2.1 => 1.2.1 
 - @frontity/wp-source: ^1.9.0 => 1.9.0 
 - frontity: ^1.12.0 => 1.12.0 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found
```

**Possible solution**

I had a long discussion with a community member where I explain the situation, show possible solutions, etc. Here is the link: https://community.frontity.org/t/how-make-slug-case-insensitive/3138

I've provided 2 suggestions. The first one I don't think is correct (it seems more a workaround), but the second one has a chance to be the solution:
1) https://community.frontity.org/t/how-make-slug-case-insensitive/3138/11
2) https://community.frontity.org/t/how-make-slug-case-insensitive/3138/14

Thank you so much.

**Comment by luisherranz** [comment]
Thanks for opening this issue @nandotess 🙂

**Comment by DAreRodz** [comment]
Hi @nandotess :wave: 

I like your idea about lowercasing links when they are standardized. I guess it would be relatively safe as WordPress does two things regarding links:

1. It is case-insensitive and returns the file that matches the link, whatever its capitalization.
2. It only allows defining lowercased permalinks (they are sanitized by the WordPress core).

The fix, in that case, would be to add `.toLowerCase()` either to `stringify` or `normalize` functions:

https://github.com/frontity/frontity/blob/ff9af973484cb532d1dde73470244fdec2e34bd2/packages/wp-source/src/libraries/route-utils.ts#L162-L171

https://github.com/frontity/frontity/blob/ff9af973484cb532d1dde73470244fdec2e34bd2/packages/wp-source/src/libraries/route-utils.ts#L173-L186

About adding an option in the `@frontity/wp-source` package to ignore or not the case of links, maybe that would be useful for users hacking their WordPress to have uppercased links?

I'm not sure if it is worth it, though. @luisherranz, any opinion?

**Comment by nandotess** [comment]
@DAreRodz thank you so much for replying to this ticket.

About your concern about the uppercased links... today I already can load a page with uppercase (standard WordPress):
- https://lawsocietytribunal.ca/mission-and-core-values/
- https://lawsocietytribunal.ca/MISSION-AND-CORE-VALUES/

**Comment by luisherranz** [comment]
> About adding an option in the @frontity/wp-source package to ignore or not the case of links, maybe that would be useful for users hacking their WordPress to have uppercased links?

I wouldn't add an option if that's something that is not possible in WordPress. It doesn't seem standard or even safe either.

I like your proposed solution David!

**Comment by DAreRodz** [comment]
> About your concern about the uppercased links... today I already can load a page with uppercase (standard WordPress):

Yeah, when I said _hacking WordPress_ I meant making links with uppercase letters to be the canonical one. By default, WordPress internally uses lowercased links, e.g. if you check the canonical tag for https://lawsocietytribunal.ca/MISSION-AND-CORE-VALUES/ you will see this:

```html
<link rel="canonical" href="https://lawsocietytribunal.ca/mission-and-core-values/">
```

That's like the official URL. :blush:

**Comment by SantosGuillamot** [comment]
Thanks for the triage guys! @nandotess Would you be wiling to contribute with a Pull Request to solve this? That would be awesome :slightly_smiling_face:

Maybe it's a good idea to add tests to check that it works with uppercase links, but we could help you with that.

**Comment by nandotess** [comment]
@SantosGuillamot thanks for the opportunity to contribute to the project.

I have created a PR but a test failed, and I can't understand why. Do you mind helping me with that?

Thank you!

- Pull-request: https://github.com/frontity/frontity/pull/606

_It seems to be related to other parts of the code that are failing..._

**Comment by SantosGuillamot** [comment]
Thanks a lot @nandotess ! We can keep the conversation in [the Pull Request](https://github.com/frontity/frontity/pull/606) :slightly_smiling_face:
