### ISSUE TITLE
Change ad ids for the SmartAds e2e tests to the use official sandbox [3pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#612]
When we developed the `@frontity/smart-adserver` package, we used a private account for the e2e tests. We asked the SmartAds team for a sandbox account and they have provided the information needed, so we should change them. This is what they shared:

```
<script type="application/javascript" src="https://ced.sascdn.com/tag/256/smart.js" async></script>
<div id="sas_8025"></div>
<script type="application/javascript">
    var sas = sas || {};
    sas.cmd = sas.cmd || [];
    sas.cmd.push(
        function () {
            sas.call(
                { siteId: 383739, pageId: 1326721, formatId: 8025, tagId: "sas_8025" },
                { networkId: 256, domain: "https://www3.smartadserver.com" /*, onNoad: function() {} */ }
            );
        }
    );
</script>
Los formatos tienen este ID:
728x90: Image -> 6467
300x100: Html5 -> 8025
300x250: Image -> 19809
300x600: Html5 -> 58374
```

**Comment by DAreRodz** [comment]
Hey @SantosGuillamot, I'm not sure but it looks like the data they shared is not working. A script is being rendered inside the ad container, nothing else.

This is with the current data:

![2020-12-01_15-56](https://user-images.githubusercontent.com/6917969/100756925-0a1f7980-33ee-11eb-9b8d-28067dc507e1.png)

This is with the previous one:

![2020-12-01_15-57](https://user-images.githubusercontent.com/6917969/100756949-13104b00-33ee-11eb-94c3-d8dc863b3f31.png)

**Comment by DAreRodz** [comment]
I've contacted the SmartAdserver team. I'm gonna mark this issue as blocked until they answer.

**Comment by DAreRodz** [comment]
The ad units show content now and work as expected.

![Screenshot from 2020-12-09 14-24-24](https://user-images.githubusercontent.com/6917969/101636574-d23ab680-3a2b-11eb-9159-26b72d6cbf09.png)

This issue is unblocked now.
