### ISSUE TITLE
iframe does not display

### ISSUE THREAD

**Issue by hugosbg** [frontity/frontity#613]
I created a standard app

In the Wordpress Post includes an iframe, but in Frontity the iframe is not displayed.

![image](https://user-images.githubusercontent.com/14058763/98268708-9fecf380-1f6b-11eb-8786-8278fb48fc27.png)

![image](https://user-images.githubusercontent.com/14058763/98269307-5355e800-1f6c-11eb-81ad-0e262671bcc3.png)

**UPDATE**
I'm sorry, guys.
There in Home, does not display because it is a preview of the post, when it opens the post page the iframe is displayed.

**Comment by luisherranz** [comment]
I am glad it is working now @hugosbg 🙂
