### ISSUE TITLE
`npx frontity create-package` should handle package names with special characters.

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/frontity#617]
**Steps involved to reproduce the problem**

Running `npx frontity create-package` and passing a namespace like `some-package` will create a package with a syntactically invalid `index.js` file.

**Expected behavior**

Frontity should create a package with a syntactically valid `index.js` file.

**Observed behavior**

The generated `index.js` file will contain: 

```js
export default {
  name: "some-package",
  roots: {
    some-package: Root
  },
  state: {
    some-package: {}
  },
  actions: {
    some-package: {}
  }
};
```
where `some-package` is not a valid key in a JS object.

**Possible solution**

Wrap the keys of the object with `""` or decide on a convention where we camelCase the package namespace.

**Comment by luisherranz** [comment]
> Wrap the keys of the object with "" or decide on a convention where we camelCase the package namespace.

I prefer camelCase because it's what we are using ourselves 🙂

**Comment by DAreRodz** [comment]
Uhm, I thought that case was covered... :thinking:

EDIT: OK, we are not covering that case. We can use the same function we wrote here to transform the package name into camelCase:

https://github.com/frontity/frontity/blob/251506f82db84b9db21f45ae1bbb277ce98680a4/packages/wp-source/src/libraries/handlers/utils/capitalize.ts#L1-L12

**Comment by DAreRodz** [comment]
I've checked the code a second time and that should not be happening. The namespace should take the value of the `namespace` argument of the `npx frontity create-package` command, not the package name. By default, if that argument is not provided, then `namespace` is `theme`.

The problem occurs when you provide an invalid namespace, as we are not sanitizing the input provided by users.

I guess we should throw an error message or fix the namespace in that case.

**Comment by DAreRodz** [comment]
Regarding a possible solution, I would do these two things when the namespace contains hyphens or other invalid characters:
- In interactive mode, show a warning and ask for a different namespace.
- When passing the namespace as a parameter, throw an error.

EDIT: @SantosGuillamot, you can assign priority now.

**Comment by cristianbote** [comment]
Managed to open a PR for this, see #656. Thank you so much @DAreRodz, @luisherranz and @michalczaplinski for a clear description and what's at fault here.

@DAreRodz regarding throwing an error for invalid format, I thought it would offer a smoother developer experience, if we would show a warning and format the `namespace` for the user. This is the log:
```
$ npx frontity create-package name-is-cool --namespace foo-bar-name-space
The namespace("foo-bar-name-space") contains invalid characters. It'll be converted to a valid format: "fooBarNameSpace"
✔ Adding package.json.
✔ Adding src/index.js.
✔ Installing package name-is-cool.
```

What are your thoughts after seeing this?

**Comment by luisherranz** [comment]
> What are your thoughts after seeing this?

I think the log message is fine. Up to you! 🙂
