### ISSUE TITLE
End to end tests for wp-source errors (404, 500...)

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#619]
It seems like the site that Michal created for the wp-source-errors is failing: https://ballistic-western-donkey.glitch.me/status/404?rest_route=/wp/v2/posts?_embed=true&page=1

This is the second time we see this problem. Previously it was with https://httpstatuses.com/ being down. Maybe we should not rely on external sources for our E2E tests.

@michalczaplinski, @DAreRodz: what do you think? Should move those tests to use the WordPress instance to generate the 404 and 500 errors now that we have that possibility?

**Comment by michalczaplinski** [comment]
By "move those tests to use the WordPress instance to generate the 404 and 500 errors" I think that you mean generating the error in PHP via e.g. "Code Snippets" plugin, correct? Then, we can load the plugin in the cypress task as usual.

I think this makes sense and is probably the simplest way to solve it 🙂

**Comment by DAreRodz** [comment]
Yeah, I think is a good idea too. :+1:

**Comment by luisherranz** [comment]
Yes, the 404 is simple and we can generate a server error using a code snippet 🙂

It seems like https://ballistic-western-donkey.glitch.me/status/404?rest_route=/wp/v2/posts?_embed=true&page=1 is working again.

What should we do? Should we change this now? Or should we wait until it fails again?

@santosguillamot, what do you think?

**Comment by SantosGuillamot** [comment]
I am not in favor of postponing maintenance issues like this one until it fails. If we already know this is something we have to change and it won't take too much, I would change it now to prevent future problems when it fails. I've included it in the sprint board.

**Comment by luisherranz** [comment]
Does it make sense to rename this to `wp-source` and use the same package/integration for other E2E tests related to `wp-source`?

**Comment by DAreRodz** [comment]
You mean rename the `wp-source-errors.spec.js` file to `wp-source.spec.js`, which is more general, and move `wp-source` related tests to it, right?

**Comment by luisherranz** [comment]
Yes, that's right. But let's keep it as it is, with more isolated tests 👍
