### ISSUE TITLE
wordpress.com sites not working with `state.source.url` [5pt]

### ISSUE THREAD

**Issue by mburridge** [frontity/frontity#622]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Using a wordpress.com address in `state.source.url` in `frontity.settings.js` should result in the data being fetched and the site behaving normally. 

**Observed behavior**

A 404 not found error occurs.

**Steps involved to reproduce the problem**

Straight after setting up a new site with `npx frontity create` change the `state.source.url` setting in `frontity.settings.js` to a URL pointing to a wordpress.com site.

**Info about your system**

**Possible solution**

In line 77 of `packages/wp-source/src/state.ts` it looks like the full `state.source.url` is being appended to the string `https://public-api.wordpress.com/wp/v2/sites/`, including the `https://` prefix, resulting in a URL something like:

```
https://public-api.wordpress.com/wp/v2/sites/https://my-site.wordpress.com
```

The `https://` prefix needs to be stripped out before `state.source.url` is appended.

**Comment by mburridge** [comment]
I made this change

![image](https://user-images.githubusercontent.com/20643925/99525219-6ff11780-2991-11eb-91ab-7533377be642.png)

i.e. I changed `${state.source.url}` to `${state.source.url.slice(8)}` on line 77 of `packages/wp-source/src/state.ts`

and now a wordpress.com site works.

But I ran `npm test` and the tests failed, so I won't do a PR.

![image](https://user-images.githubusercontent.com/20643925/99524927-0ec94400-2991-11eb-937c-7df1981644e2.png)

I think the test is expecting the invalid URL:

```
Expected: "https://public-api.wordpress.com/wp/v2/sites/https://domain.wordpress.com/"
@frontity/wp-source:     Received: "https://public-api.wordpress.com/wp/v2/sites/domain.wordpress.com/"
```

**Comment by mburridge** [comment]
A better fix starting at line 75:

```
if (/^https:\/\/(\w+\.)?wordpress\.com/.test(state.source.url)) {
      const url = new URL(state.source.url)
      const hostname = url.hostname
      return addFinalSlash(
          `https://public-api.wordpress.com/wp/v2/sites/${hostname}`
      );
}
```

**Comment by michalczaplinski** [comment]
Confirming this issue. I think the final solution should look something like the what @mburridge has posted above: https://github.com/frontity/frontity/issues/622#issuecomment-732139397

**Comment by mburridge** [comment]
Questions on this are starting to come up in the community forum: https://community.frontity.org/t/wordpress-com-data-fetching-error/3491
