### ISSUE TITLE
state.router.link mismatch when the URL is not the same in the server as in the client

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#623]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

`state.router.link` should have the URL of the client.

**Observed behavior**

`state.router.link` has the URL that was sent to the server.

**Steps involved to reproduce the problem**

Add this to the Frontity server:

```js
// Change a query in the server.
if (ctx.URL.searchParams.get("utm")) {
  ctx.URL.searchParams.set("utm", "SERVER");
}
```

And visit http://localhost:3000/?utm=client. `state.router.link` is http://localhost:3000/?utm=SERVER and the URL is also replaced in the browser bar.

**Possible solution**

I think the way to go would be to:

- Solve the problem of the canonical links not pointing to the same data object.
- Restore the `state.router.link` to the client URL in the hydration.

I have explained it in more detail here:

- Video: https://www.loom.com/share/707af27e0c0f4d7db7d4551c98d5f7f8
- Drawing: https://excalidraw.com/#json=5474711555276800,KVqzcQvObG8FHpK0kMujrg

A quick fix would be to remove this line to now replace the client URL with the `state.router.link` value that was sent to the server, but that would break the "Back" button of the browser:

https://github.com/frontity/frontity/blob/dev/packages/tiny-router/src/actions.ts#L90

- You visit `/?utm=client`
- The server receives `/?utm=SERVER`
  - `state.router.link` is `/?utm=SERVER`
  - The data object is for `/?utm=SERVER`
- The client still has `/?utm=client` in the browser bar, but `state.router.link` is `/?utm=SERVER`
- You go forward to some link
- You go back with the browser button to `/?utm=client`. There is no data object for that URL.

We could alleviate the problem by using the autoFetch in the `"pop"` method, here: https://github.com/frontity/frontity/blob/dev/packages/tiny-router/src/actions.ts#L50-L61. That way, at least the page (`/?utm=client`) will be fetched again.

Also, we would need to remove `state.router.link` from the `updateState` action that is going to be introduced with the infinite scroll hooks: https://github.com/frontity/frontity/blob/infinite-scroll-beta/packages/tiny-router/src/actions.ts#L96

**Comment by SantosGuillamot** [comment]
I'm not sure if I understood it correctly. With this proposal:
* Websites where the parameters aren't changed and `?utm=123` is the same in the client and the server, everything works as expected. This is the most common case, and it is working right now.
* In webs where the parameters are changed (frontity.org for example), with the quick fix, the only issue will be that if users go forward to some link and they go back with the browser button, is going to fetch the page again instead of doing CSR.
* This would be a patch until we work on adding the feature to point different links to the same data object.

Is this right? Is there something I am missing?

**Comment by luisherranz** [comment]
Yes, you are right, except for one thing:

> In webs where the parameters are changed (frontity.org for example), with the quick fix, the only issue will be that if users go forward to some link and they go back with the browser button, is going to fetch the page again instead of doing CSR.

The scroll restoration is also broken because instead of going back to the same scroll point where the user was, the app goes to the `isFetching` state and back to the top of the screen. So the user needs to scroll down again.

**Comment by SantosGuillamot** [comment]
I've marked this as `critical` as websites with this problem, like ours, are not able to track their marketing efforts. I feel that with the quick fix you suggested would be enough for the moment.
