### ISSUE TITLE
Update React and Emotion and update Babel to use the new JSX transform [13pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#631]
Feature: [Update to React 17 and Emotion 11](https://community.frontity.org/t/update-to-react-17-and-emotion-11/3225/).

This feature affects the issue to [Move all the CSS to the `<head>`](https://github.com/frontity/frontity/issues/559), so we should take this into account or even address both at the same time.

[Sprint Card](https://github.com/orgs/frontity/projects/12#card-50175547)

**Comment by luisherranz** [comment]
We should've done two different issues for this 😄
