### ISSUE TITLE
The local self-signed SSL certificate doesn't work on Chrome

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#657]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

The self-signed SSL certificate used to test the site with locally SSL should work in all browsers, even though it is not valid for public use.

**Observed behavior**

Right now, as reported by @orballo, it doesn't work in Chrome because it is missing a param that is required in the latest versions of Chrome.

It is explained here: https://stackoverflow.com/questions/43665243/invalid-self-signed-ssl-cert-subject-alternative-name-missing

**Possible solution**

Generate a new certificate again using `-sha256 -extfile` as explained here: https://stackoverflow.com/questions/43665243/invalid-self-signed-ssl-cert-subject-alternative-name-missing

**Comment by luisherranz** [comment]
@orballo I have updated to the latest version of Chrome and the certificate that we have is invalid (which is expected) but it still works:

<img width="669" alt="Screenshot 2021-01-08 at 16 32 13" src="https://user-images.githubusercontent.com/3305402/104032883-1528af00-51cf-11eb-9e6e-f0ea7f617180.png">

How can we reproduce the problem?

**Comment by orballo** [comment]
@luisherranz Yes, it works when you use `https://localhost:3000`. However, in my case, I modified `/etc/hosts` to point `127.0.0.1` to `local.aleteia.org` and that's the moment the certificate starts to fail, without the possibility of forcing Chrome to accept it even though I marked it as allowed in the system.

Actually, I just tried setting the alias to `local.example.com` and it works, so I'm not really sure why it is failing.

Some screenshots:
<img width="318" alt="Screenshot 2021-01-08 at 17 42 07" src="https://user-images.githubusercontent.com/13615057/104042151-625e4e00-51da-11eb-84b4-73c6432de620.png">
<img width="662" alt="Screenshot 2021-01-08 at 17 42 12" src="https://user-images.githubusercontent.com/13615057/104042153-64281180-51da-11eb-8eb2-bcbe5010c58b.png">
<img width="486" alt="Screenshot 2021-01-08 at 17 47 04" src="https://user-images.githubusercontent.com/13615057/104042158-65593e80-51da-11eb-927c-6f7c55e6abee.png">


EDIT: I had this same aliases in my previous laptop, and I could always accept the certificate. Not sure if the version of Chrome changed. Will check.

**Comment by luisherranz** [comment]
Ok, let us know what you find out.

By the why, does it work if you use a non-existent domain, like https://example.local?

**Comment by orballo** [comment]
Ok, this is the version from my old laptop:
`Version 87.0.4280.141 (Official Build) (x86_64)`
And this is the version from the new one:
`Version 87.0.4280.141 (Official Build) (arm64)`

Maybe it is a problem with the arm build. I'll try to run the x86_64 and see what happens.

EDIT: The error persists on `Version 87.0.4280.141 (Official Build) (x86_64 translated)`

**Comment by orballo** [comment]
It looks like an issue with the domain I'm using. I tried to use that domain with Local, which is issuing a complete certificate with the values that the browser was complaining about before, and it doesn't work either. No idea though why it works on the other machine.

EDIT: I just wanted to add that is not an issue with using an existent domain, as `local.example.com` works and `example.com` is an existing domain.

**Comment by luisherranz** [comment]
@orballo do you have more information regarding this problem? (I've assigned you the triage)

**Comment by orballo** [comment]
@luisherranz No, I ended up using domains ending in `.local`. I'd say it is a Chrome's issue in M1.

EDIT: What am I supposed to do with the triage? 😅

**Comment by luisherranz** [comment]
Haha, only figuring out where the problem was coming from 🙂 

Can we close this then, as it seems like a Chrome problem instead of a Frontity one?

**Comment by orballo** [comment]
Yes, indeed. We can.

**Comment by luisherranz** [comment]
Ok, thanks Edu!
