### ISSUE TITLE
Cypress e2e tests get stuck

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#659]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

The e2e tests should be reliable and pass or fail and not get stuck.

**Observed behavior**

They often get stuck so it prevents and they don't return an error, so we are not able to check if tests are passing or not. It seems it isn't related to any specific test, because it gets stuck on different ones.

**Possible solution**

Not sure if this will be helpful but there are other users complaining about this in the [Cypress repo](https://github.com/cypress-io/cypress/). Some fixes they mention:
- Add `options: --shm-size 2gb` as explained in [this comment](https://github.com/cypress-io/cypress/issues/6695#issuecomment-627363078) and the following ones.
- Use `--disable-dev-shm-usage` as a flag rather than trying to set the `--shm-size` as explained in [this comment](https://github.com/cypress-io/cypress/issues/8206#issuecomment-712458749).
- Pass tests one at a time seems to help as explained in [this comment](https://github.com/cypress-io/cypress/issues/8206#issuecomment-682721485) and [here](https://github.com/cypress-io/cypress/issues/8206#issuecomment-745117472).
- Not using chrome as explained in [this comment](https://github.com/cypress-io/cypress/issues/8206#issuecomment-675663487), although the [next one](https://github.com/cypress-io/cypress/issues/8206#issuecomment-676588332) says it didn't work for them.

**Comment by luisherranz** [comment]
Things we can try: 

- Update Cypress to v6.
- Check if we can increase the memory of the container.
- Run specs one by one. First without docker. And try to figure out where at which point it gets stuck.

**Comment by michalczaplinski** [comment]
@luisherranz I believe this is the issue that Mario mentioned that I could take a look :) Will update the issue if I had the time to do that.

**Comment by DAreRodz** [comment]
@michalczaplinski, I don't think so! I'm currently working on this issue. :sweat_smile:

EDIT: I still have to open a PR, the brach is this one: https://github.com/frontity/frontity/tree/fix-e2e-tests

**Comment by michalczaplinski** [comment]
Oh, my bad in that case 😅

**Comment by luisherranz** [comment]
@DAreRodz I ran the e2e tests locally for the React 17 branch and it seems like some snapshots are missing for yoast and aiseop specs. Those should be committed, shouldn't they?
