### ISSUE TITLE
Fix webpack output colors [1pt]

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#662]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Webpack should output colors in the terminal.

**Observed behavior**

It outputs `<i>` text instead, like this:

<img width="552" alt="101485589-ab14b400-395b-11eb-97ff-baab362fe8de" src="https://user-images.githubusercontent.com/3305402/104337243-8df07980-54f5-11eb-8c32-ab98d4ed232e.png">

**Possible solution**

This is due to a problem with the latest version of `webpack-dev-middleware` but they are working on a fix: https://github.com/webpack/webpack-dev-middleware/issues/782

We should update its version once they have fixed it.

**Comment by SantosGuillamot** [comment]
It seems [the issue](https://github.com/webpack/webpack-dev-middleware/issues/782) you linked has already been closed. Should we consider this unblocked?
