### ISSUE TITLE
The `Link` component tries to fetch links that start with `mailto:`

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#667]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When the Link component is rendered with an `href` value that starts with `mailto:`, the browser should open a window to send an email if you click it and nothing else.

**Observed behavior**

If you set `state.theme.autoPrefetch` to `all`, `in-view` or `hover`, an error in the console will appear as soon as Frontity tries to fetch the email link ("no handler was found for the given link").  

**Possible solution**

The check to know if the link should be fetched or not is done in this line:

https://github.com/frontity/frontity/blob/94772c1217b4c48d67bcac742ecd9c93739c73ac/packages/components/link/index.tsx#L81-L83

We should change it to return also for links that start with `mailto`, `tel` and `sms`, e.g. changing the way `isExternal` is computed:

https://github.com/frontity/frontity/blob/94772c1217b4c48d67bcac742ecd9c93739c73ac/packages/components/link/index.tsx#L69

**Comment by nicholasio** [comment]
We should probably move those checks to a utility function as these checks are becoming more complex.
