### ISSUE TITLE
Remove old React imports from the themes

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#668]
Now that we have upgraded to React 17 and the new JSX runtime, we should not use the old React imports anymore:

```js
import React from "react";
```

**Possible solution**

We could use a search-and-replace.

We have to be careful because sometimes we are using `React.FC` or `React.useEffect`. In those cases, we can either switch to `import { FC, useEffect } from "react"` or keep the `import React from "react"`. I think both solutions are fine.

I would modify all our packages, not just the themes.

**Additional notes**

This is going to trigger lots of Eslint errors, but I have already agreed with the DevRel team that we are not going to invest time in adding TSDocs for all the theme files right now. We will ignore those Eslint errors in that PR and we will continue adding TSDocs to our codebase whenever we modify a file as we have done until now.

**Comment by luisherranz** [comment]
This is not a bug, but I have assigned it to you so you can think about when to add this to our roadmap. Feel free to unassign yourself after that 🙂

**Comment by nicholasio** [comment]
There's a codemod built by the react core team

```
npx react-codemod update-react-imports <path>
```

not sure if it works with typescript though

**Comment by luisherranz** [comment]
I wonder why this has not been closed automatically if the PR was linked and merged... Anyway, closing this now.

Thanks @nicholasio!! 🎉😄

**Comment by SantosGuillamot** [comment]
Thanks @nicholasio !

>I wonder why this has not been closed automatically if the PR was linked and merged... Anyway, closing this now.

It seems the PR was linked after being merged, I guess that's the reason.

**Comment by cristianbote** [comment]
Yup 😃 I linked it afterwards.
