### ISSUE TITLE
[Components] The `Link` component doesn't remove the WordPress subdirectory

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#691]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org
- 
I think I've found a bug while triaging this issue: #665 

**Expected behavior**

Using a WordPress multisite setup, the `Link` component should transform links that points to a WordPress site, removing the subdirectory from the link.

**Observed behavior**

The final link maintains the WordPress subdirectory. When a link is clicked, 404 is returned.

**Steps involved to reproduce the problem**

- Create a WordPress multisite (subdirectories) with Local: https://www.youtube.com/watch?v=9AZapIsjCTo
- Add a new site.
- Add a link to any page (e.g. in "Sample Page", to "Hello World").
- Create a Frontity project and change `state.source.url` to point to the site added before.
- Visit the page with the link and click it.

**Possible solution**

I'm pretty sure the problem is in this line of code:

https://github.com/frontity/frontity/blob/c139094e956d3119f9fd1ea2342717e29e187f2f/packages/components/link/utils.ts#L139

There, I think we should remove the WordPress subdirectory from `linkUrl.pathname`. We could get the WordPress subdirectory from `state.source.url` easily.

**Comment by luisherranz** [comment]
I'm not sure I get the issue. Is it when WordPress is in a subfolder but Frontity is not?

- `https://backend.com/subfolder/some-post`
- `https://domain.com/some-post`

If so, shouldn't the link be fixed in the entity link (`post.link`...)?  If not, that fix will need to be replicated everywhere. For example, the share buttons also need the correct final link.

**Comment by DAreRodz** [comment]
I think the entity link is right, the link that the `removeSourceUrl()` function receives is the one rendered in the content (`rawLink`), i.e. the WP one.

https://github.com/frontity/frontity/blob/c139094e956d3119f9fd1ea2342717e29e187f2f/packages/components/link/index.tsx#L72

**Comment by luisherranz** [comment]
Ok, got it. Thanks David.
