### ISSUE TITLE
Make @frontity/google-tag-manager package AMP-aware [8pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#710]
This is needed for [AMP feature](https://community.frontity.org/t/amp-package/388/). For full context please check out the [final Implementation proposal](https://community.frontity.org/t/amp-package/388/10?u=santosguillamot).

---

The AMP framework uses a special syntax for the [analytics](https://amp.dev/documentation/components/amp-analytics/), so we have to make this package AMP-aware to load the correct content if the AMP package is active.

**Comment by DAreRodz** [comment]
Blocked as per https://github.com/frontity/frontity/pull/766#issuecomment-816778174

All the work is done, that issue is just preveting the e2e tests to pass.
