### ISSUE TITLE
Make @frontity/google-analytics AMP-aware [8pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#711]
This is needed for [AMP feature](https://community.frontity.org/t/amp-package/388/). For full context please check out the [final Implementation proposal](https://community.frontity.org/t/amp-package/388/10?u=santosguillamot).

---

The AMP framework uses a special syntax for the [analytics](https://amp.dev/documentation/components/amp-analytics/), so we have to make this package AMP-aware to load the correct content if the AMP package is active.

**Comment by cristianbote** [comment]
@SantosGuillamot since we're gonna release a major version of `@frontity/google-analytics` to support GA4, does this mean that we would have to add AMP support for the `@frontity/google-analytics@1.x` and the new version as well?

**Comment by SantosGuillamot** [comment]
In my opinion it would be enough to add AMP support from the new version we are planning to release. At some point, users should migrate to the new `@frontity/google-analytics` version because Google is pushing this new way of tracking. What do you think?
