### ISSUE TITLE
Derived state does not have access to `actions` or `libraries`, only to `state`

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/frontity#716]
**Expected behavior**

Derived state should have access to `state`, `actions` and `libraries` inside of the callback.

It **seems** that when using derived state, you can access `state` `actions` and `libraries`:

https://github.com/frontity/frontity/blob/a569db247e11195a0ef341ebf0b62ab87df7318d/packages/types/src/derived.ts#L10-L15

The TS types also seem to indicate that this is possible: 

https://user-images.githubusercontent.com/5417266/107553538-deb1cb80-6ba2-11eb-84d6-6b93568b3fc4.mov

**Observed behavior**

Only `state` is passed to the derived state callback in `@fronity/connect`:

https://github.com/frontity/frontity/blob/107d3543ce5463186809b7e6f50ca31ffbdc107d/packages/connect/src/handlers.js#L23-L24

**Steps involved to reproduce the problem**

Create any derived state and try to access `libraries` or `actions` in the callback. E.g: 

```js
state = {
  myPackage: {
    test: ({ state, libraries, actions }) => {
      // libraries is undefined !!!
      libraries.source.parse('hello');
      
	  // actions is undefined too.
      actions.amp.init();
    }
  }
}
```

**Possible solution**

We should be clear that `actions` and `libraries` are available in derived state.

OR

We should make `actions` and `libraries` available in derived state.

**Comment by luisherranz** [comment]
In [Flux](https://facebook.github.io/flux/), only actions can trigger state mutations or side effects, so passing `actions` would be an antipattern. If it is stated in the types or the docs it is a typo and should be fixed.

I agree on passing `libraries` though 🙂

**Comment by SantosGuillamot** [comment]
Are you aware of any use cases where this is needed right now?

**Comment by michalczaplinski** [comment]
@SantosGuillamot Nope, I just discovered it accidentally while working on [Removing the `/amp` from links](https://github.com/frontity/frontity/pull/686). 🙂 

As far as I know, no user has reported it and it's not even documented. E.g.: https://docs.frontity.org/learning-frontity/state only mentions using `state`.

**Comment by DAreRodz** [comment]
Hey, I'm gonna work on this issue. From the conversation above (https://github.com/frontity/frontity/issues/716#issuecomment-777340627), I understand that the steps we should follow here are:

1. Pass `libraries` to derived state
2. Remove `actions` from `Derived` type
3. Update TSDocs

Is that correct?

cc: @luisherranz @michalczaplinski

**Comment by luisherranz** [comment]
> Is that correct?

Yes it is!
