### ISSUE TITLE
@frontity/google-analytics package doesn't work with Google Analytics 4 [5pt] 

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#719]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Google Analytics released a new way of using the tool, [Google Analytics 4](https://support.google.com/analytics/answer/10089681?hl=en), and `@frontity/google-analytics` package should work with it as it is the new default and recommended way.

**Observed behavior**

The package doesn't work with Google Analytics 4 because it has changed the library used to track pageviews and events.

**Steps involved to reproduce the problem**

Create a new property in Google Analytics and try to use `@frontity/google-analytics` package.

**Possible solution**

Google Analytics use now `gtag.js` instead of `analytics.js` so we have to adapt our package following [this guide](https://developers.google.com/analytics/devguides/collection/upgrade/analyticsjs#:~:text=Measure%20pageviews,-analytics.&text=js%20uses%20trackers%20to%20send,specified%20in%20a%20config%20command.). It seems that old properties not using Google Analytics 4 are also compatible with `gtag.js`, so this change should be backwards compatible.

As far as I understood what we have to do is:

**1. Change the `<Head>` script**

Right now -> https://github.com/frontity/frontity/blob/dev/packages/google-analytics/src/components/index.tsx#L29-L38
According to [this article](https://developers.google.com/analytics/devguides/collection/ga4), it should be something like:

```
<script
    async
    src={`https://www.googletagmanager.com/gtag/js?id=MEASUREMENT_ID`}
 />
<script>
    {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
   
    gtag('config', 'MEASUREMENT_ID');
    gtag('config', 'MEASUREMENT_ID_2');
    `}
</script>
```

**2. Change the way we send pageviews**
Right now -> https://github.com/frontity/frontity/blob/dev/packages/google-analytics/src/index.ts#L33-L51
According to [this](https://developers.google.com/analytics/devguides/collection/upgrade/analyticsjs#measure_pageviews_with_specified_trackers), we should do something like:

```js
ids.forEach((id) =>
    window.gtag("event", "page_view", { send_to: id })
);
```

**3. Change the way we send events**
Right now -> https://github.com/frontity/frontity/blob/dev/packages/google-analytics/src/index.ts#L52-L77
According to [this](https://developers.google.com/analytics/devguides/collection/upgrade/analyticsjs#measure_pageviews_with_specified_trackers), we should do something like:

```js
window.gtag("event", name, {
    event_action: name,
    event_category: category,
    event_label: label,
    value: value,
    ...rest,
});
```

**Comment by luisherranz** [comment]
Two questions:

- Should we consider this a breaking change?

  I know some users have overwritten the `actions.googleAnalytics.pageview` action and they use `window.ga` internally.

  ```js
  ids.forEach((id) =>
    window.ga(`${getTrackerName(id)}.send`, {
      hitType: "pageview",
      page: link,
      title,
      ...customDimensions,
    })
  );
  ```

  If I'm not mistaken, this will break that code, right?

- Can we mark this as a `good-first-issue`? What do you think? 🙂

**Comment by SantosGuillamot** [comment]
>Should we consider this a breaking change?

Yes, you are right. I was just thinking that the old tags will work, but I wasn't considering the possibility of users written their own pageviews. If we change the `<script>` and we don't load `analytics.js`, `window.ga` won't work as you say. I assume it doesn't make sense to make it backward compatible for these cases right?

>Can we mark this as a good-first-issue? What do you think? slightly_smiling_face

Yes, I have just done it :slightly_smiling_face: I was able to make it work during my tests so it shouldn't be difficult.
