### ISSUE TITLE
Webpack builds are now slower than they used to be

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#723]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Webpack rebuilds are fast.

**Observed behavior**

Webpack rebuilds are slow. Or at least slower than before.

**Steps involved to reproduce the problem**

- Start the project in `e2e/project` running `npx frontity dev`.
- Wait until Webpack starts.
- Make a change to a file of that project, for example to `e2e/packages/ads/src/index.tsx`.
- It should take a couple of seconds to rebuild the entire project, but now it takes like 30 seconds.

**Possible solution**

I've been triaging this and the regression was clearly introduced in #640. 

There are many changes in that PR. I am not sure right one which one is causing the problem.

At first, I thought it could be the changes of babel, but reverting those didn't solve the problem. So maybe it's related to an updated package.

I'll keep triaging this until I find the exact problem 🙂

**Comment by luisherranz** [comment]
@cristianbote, can you please finish the triage of this bug?

I suspect this problem was introduced by one of the many package updates we did in #640 but I'm not 100% sure.

Thanks!!

**Comment by luisherranz** [comment]
EDIT: I am 100% sure that it was the #640 PR, but not which of the changes we did there (babel, dependency updates...)

**Comment by cristianbote** [comment]
Ok. Will pick this up @luisherranz.

**Comment by cristianbote** [comment]
The slowness seems to come from `webpack-dev-middleware@4.x.x` -- don't ask me how long it took to figure it out 😰 ... opening up a PR.
