### ISSUE TITLE
Frontity default state.source don’t fetch all items once in loop

### ISSUE THREAD

**Issue by jsonpreet** [frontity/frontity#726]
Frontity default state.source don’t fetch all items inside loop. I am trying to fetch posts from custom api route which return id, link, type, slug in json. When i console.log custom route it returns all 5 items. but when i fetch data with state.source[item.type][item.id] it fetch only first 1 from json output. If i tried to return all posts data in custom route and show post title, post link direct in component and click on link it move to 404 page.

please help, if i can’t solve this issue i can’t run site with frontity

```
const FrontPage = ({state, actions}) => {

    useEffect(() => {
        actions.source.fetch("getFeaturedPosts");
        FeaturedPostSection.preload();
    }, []);

//   const data = state.source.get(state.router.link);

//   const [firstThreePosts, othersPosts] = splitPosts(state, data.items);

    const data = state.source.get("getFeaturedPosts");

    const [firstThreePosts, othersPosts] = splitPosts(state, data.items);

    return data.isReady ?  (
        <>
            <FrontPageContainer>
                <FeaturedPostSection data={firstThreePosts.map(post => formatPostData(state, post))} />
           </FrontPageContainer>
        </>

    ) : null;
};
export default connect(FrontPage);

export function splitPosts(state, routeData) {
  const firstThreePosts = [];
  const otherPosts = [];
  routeData.forEach((item, idx) => {
    console.log(item.id);
    const itemData = state.source[item.type][item.id];
    if (idx < 3) firstThreePosts.push(itemData);
    else otherPosts.push(itemData);
  });

  return [firstThreePosts, otherPosts];
}
![Screenshot_2](https://user-images.githubusercontent.com/26606638/108876932-c4590280-7624-11eb-9af8-a61462cfd911.png)

```

**Comment by cristianbote** [comment]
Hi @harpreet9629,

Thank you so much for opening this issue. At a first glance, this doesn't look like an issue with the framework but rather a _how to_ question. For these kind of questions we encourage you to post it to our community forum https://community.frontity.org/. You will get all the help you need in there.

Have a great one!

**Comment by juanmaguitar** [comment]
For more context on this issue, this question was also in the Community Forum
https://community.frontity.org/t/frontity-default-state-source-dont-fetch-all-items-once-in-loop/4096

**Comment by cristianbote** [comment]
Awesome 😃  Thanks @juanmaguitar for giving more context.
