### ISSUE TITLE
hot reload not working

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [frontity/frontity#732]
I was folllowing the tutorial, first time styles not working, after investigations I fixed it.

but now hot reload not working

**Comment by luisherranz** [comment]
Hey @MoatazAbdAlmageed, could you please open the bug again and this time follow the bug template? (https://raw.githubusercontent.com/frontity/frontity/dev/.github/ISSUE_TEMPLATE/bug_report.md) 

We need to be able to reproduce the issue to fix it 🙂

Thanks!!
