### ISSUE TITLE
JS modules with `<link rel="preload">` are requested twice

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#740]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

This bug was noticed by @SantosGuillamot.

**Expected behavior**

A preloaded module should be requested once.

**Observed behavior**

It's requested twice: one from the `<link rel="preload">` tag and another from the `<script>` tag.

![Screenshot from 2021-03-08 12-04-21](https://user-images.githubusercontent.com/6917969/110367041-7510ca00-8047-11eb-8a33-c9b0fe960f7d.png)

For each script, the following warning is shown in the console:

```
A preload for '/static/mars-theme.module.eaa9243fd3abc5a42c99.js' is found, but is not used because the script type does not match.
```

**Steps involved to reproduce the problem**

It should happen with any production build. Tested with https://mars.frontity.org in the following browsers (Ubuntu 20.10):
 - Chrome: 89.0.4389.72
 - Firefox: 86.0

**Possible solution**

It turns out that we should use [`rel="modulepreload"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/modulepreload) instead of `rel="preload"` for js modules.

For doing so, we could add a `.replace()` call to the output of `extractor.getLinkTags()` in this line (`extractor` is an instance of `ChunkExtractor`, from the `@loadable/server` library):

https://github.com/frontity/frontity/blob/a9ee85ffbb851dc819d2c693385bbd8b6f1d4b1b/packages/core/src/server/middlewares/server-side-rendering.ts#L59-L60

It could be something like:

```ts
// Push the link tags.
    output.head.push(
      extractor
        .getLinkTags(crossorigin)
        .replace(
          /( rel=")preload(" as="script" href="\S+\.module\.[\da-f]+\.js")/g,
          "$1modulepreload$2"
        )
    );
```

The regexp is a bit weird because I wanted to ensure that only preloaded modules are matched. I don't know if that's really needed, tho.

This kind of "hackaround" is already proposed by the Loadable team for a different issue: https://github.com/gregberge/loadable-components/issues/653#issuecomment-726667065

**Comment by cristianbote** [comment]
Hey @DAreRodz was looking for a way to have it more imperative, but the regex is as good as it gets 😄 .

Precisely since we own the `ChunkExtractor` instance we could overwrite the `getLinkTags` with our own, but that would lead to monkeypatch a piece of the library that we don't really own. On the downside loadable components, does offer the _extraProps_ functionalities but it's not overwriting the already defined ones, but rather appends. So, maybe we could propose a solution against lodable components? Either handle the `modulepreload` for script type module or allow an chunk transformer.

Also we could intercept the original `getPreAssets` and modify the `linkType` maybe? 🤔 

```js

const isModule = moduleStats && es5Stats;

extractor.getPreAssets = () => {
    const mainAssets = this.getMainAssets()
    const chunks = [...this.entrypoints, ...this.chunks]
    const preloadAssets = this.getChunkChildAssets(chunks, isModule ? 'modulepreload' : 'preload')
    const prefetchAssets = this.getChunkChildAssets(chunks, 'prefetch')
    return [...mainAssets, ...preloadAssets, ...prefetchAssets].sort(a =>
      a.scriptType === 'style' ? -1 : 0,
    )
};

```

might be too much? 🤔

**Comment by cristianbote** [comment]
Turns out that this might be a bug introduced in Chrome 88 and using `modulepreload` will work _only_ for Chrome. The rest fo the browser will still double preload the resources.

I will investigate more and have a clear solution.

**Comment by luisherranz** [comment]
Thanks for looking into this Cris! 👍

> So, maybe we could propose a solution against lodable components? Either handle the modulepreload for script type module or allow an chunk transformer.

I asked about official `module` support a while ago https://github.com/gregberge/loadable-components/pull/239#issuecomment-482501467 but it doesn't seem like there has been any movement yet in that regard.

**Comment by cristianbote** [comment]
Here's my investigation summary.

* Chrome 87 works fine
* Chrome 89 double preloads

![Screenshot 2021-03-17 at 10 52 32](https://user-images.githubusercontent.com/3405161/111440702-4661b600-870f-11eb-9ae4-21dee8fd5711.png)

Here's a video as well https://www.loom.com/share/98a0bc210e964f55910b837a84146473

**Comment by SantosGuillamot** [comment]
Thanks for the explanation Cristian :slightly_smiling_face: 

In case it is useful, the same is happening in Firefox 86.0. It stops happening in Firefox 84.0.

![Screenshot from 2021-03-17 13-55-23](https://user-images.githubusercontent.com/34552881/111470880-9731d880-8728-11eb-8b5f-5f13986249a4.png)

**Comment by SantosGuillamot** [comment]
Another thing I notices is that it seems it only happens in the production build, not when I run `npx frontity dev`:

Running **`npx frontity build && npx frontity serve`**:
![Screenshot from 2021-03-17 14-31-57](https://user-images.githubusercontent.com/34552881/111476001-fc3bfd00-872d-11eb-8ab7-48124ae395bf.png)

Running **`npx frontity dev`**:

![Screenshot from 2021-03-17 14-32-52](https://user-images.githubusercontent.com/34552881/111476077-1249bd80-872e-11eb-9b80-9c1c5ec2154a.png)

**Comment by cristianbote** [comment]
This is definitely a Chrome issue. More details in here https://bugs.chromium.org/p/chromium/issues/detail?id=1178198

**Comment by cristianbote** [comment]
@SantosGuillamot yup. Apparently this _should_ be the way forward for module but it's not adopted yet by everyone.

Reading the above linked thread seems that Safari does not pick-up the `modulepreload`. The base behaviour seems to be that every browser, regardless of module of script, should/could respect the `rel="preload"`. That way we won't get the double preload anymore, but we can opt-in for `modulepreload` for `*.module.*` once the adoption is there.

A solution to solve this for now, would be user-agent based serving of the `link` tags. Such that for _chromium_ based browsers, we would modify on the fly the link tags.

**Comment by luisherranz** [comment]
> A solution to solve this for now, would be user-agent based serving of the link tags. Such that for chromium based browsers, we would modify on the fly the link tags.

That's a good approach. The problem is that the cache/CDN also needs to support caching different HTML files per each user agent, which as far as I know it is not common.

From Mario's experiments, it seems like Firefox already supports `modulepreload`, doesn't it?

So if we follow our design principle of "Prioritize for modern" browsers, what should we do? I guess we should start using `modulepreload`, shouldn't we?

--- 

By the way Cris, you can use http://live.browserstack.com/ to test Chrome 88. If you need details about how to login send me a message over Slack 🙂

**Comment by SantosGuillamot** [comment]
> From Mario's experiments, it seems like Firefox already supports modulepreload, doesn't it?

What I've seen is that after Firefox 84 the scripts appear twice and using `modulepreload` solves the problem. But I don't know how to test if the preload is actually working. Any ideas?

I've been trying to understand the preload better and I found a couple this article interesting. It's from 2017, but it explains the issue we are having and the reason behind `modulepreload` -> https://developers.google.com/web/updates/2017/12/modulepreload

**Comment by michalczaplinski** [comment]
It's already been triaged so removing the label

**Comment by luisherranz** [comment]
So, what is our final decision here? Use `modulepreload` to prioritize modern browsers (and LightHouse score)?

@javiersefer we'd love your input here as well 🙂

**Comment by SantosGuillamot** [comment]
In my opinion we should go with `modulepreload`, although I think it is still not working in Firefox and Safari. These are my thoughts:
* It fixes the issue of the duplicated request for all the browsers, even the ones where `modulepreload` is not supported yet.
* It is already supported by 71% of the browsers usage and it's supposed to be the way of doing it in the future.
* LightHouse, that could complain of not using `preload`, runs in Chrome that supports `modulepreload`, so it shouldn't affect it.

**Comment by cristianbote** [comment]
Good points all around. I agree, sounds like `modulepreload` should be used, based on our principles as well:

[Performance](url)

Prioritize for Modern Browsers
  * Don’t sacrifice size and perf of modern browsers
  * Look only for usability in older browsers, not feature parity

Prioritize in this order
   * Final user experience
   * Performance
   * Developer experience
   * Core implementation complexity

**Comment by luisherranz** [comment]
Ok, thanks guys. Let's do it then 🙂
