### ISSUE TITLE
Infinite loop with 404 redirections in Embedded mode in some hostings [13pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#743]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

While using the [redirects feature](https://community.frontity.org/t/301-redirects-stored-in-wordpress-database/3032), with the 404 option enabled and the Embedded mode, it should work as normal.

**Observed behavior**

Some hostings are changing the HEAD methods and use GET instead, and this is causing an infinite loop if you are using the Embedded mode and you visit a page that doesn't exist.

**Possible solution**

Right now, the most appealing solution seems to be to send a query from the Embedded mode (`frontity_embedded=true` for example), that allows Frontity to populate a setting in the state to know if the app is running in Embedded mode and, if it is, don't try the redirections at all in SSR, because using the Embedded mode it will be redirected directly by WordPress.

We discussed this issue and the possible solutions in this video:

https://www.youtube.com/watch?v=ZQekma-77VY

**Comment by luisherranz** [comment]
Thanks for opening the bug Mario 🙂

I think the best way to handle this would be to return `false` in both the `isEagerRedirection` and `is404Redirection` checks if `state.frontity.options.embedded` is `true`.

https://github.com/frontity/frontity/blob/373de97da5ec882c4e4717775bc2a7ddb67e79be/packages/wp-source/src/utils.ts#L142-L186

---

We also need another issue in https://github.com/frontity/frontity-embedded to add the `?frontity_embedded=true` query to the request. Are you going to open it Mario?

**Comment by SantosGuillamot** [comment]
>We also need another issue in https://github.com/frontity/frontity-embedded to add the ?frontity_embedded=true query to the request. Are you going to open it Mario?

You're totally right. I've just opened it -> https://github.com/frontity/frontity-embedded/issues/10

**Comment by SantosGuillamot** [comment]
I guess we should consider this `blocked` until the other issue is closed right?

**Comment by luisherranz** [comment]
No, we can work on this independently. It's only a matter of adding the `?frontity_embedded=true` query to the e2e tests or `state.frontity.options.embedded: true` to the state.

**Comment by cristianbote** [comment]
Hey @luisherranz, I've picked this up and started looking at it. A couple of questions:

When you said:
> It's only a matter of adding the ?frontity_embedded=true query to the e2e tests or state.frontity.options.embedded: true to the state.

Which tests were you referring to? I assume those tests are testing this functionality? Just wanna make sure I can verify the implementation with a test case.

**Comment by luisherranz** [comment]
Yes, what I meant is that we don't need to use a WordPress instance with the Embedded mode plugin installed to test this. We can just use `http://localhost:3001?frontity_embedded=true` to simulate the Embedded mode 🙂

I wasn't referring to any specific test. I guess we will have to add new ones to test this out, won't we?
