### ISSUE TITLE
Frontity stops working when visiting a link without a trailing slash

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#744]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

This was reported first in the community: https://community.frontity.org/t/error-when-opening-urls-that-don-t-finish-with/4184

**Expected behavior**

If you go to **any link without a trailing** slash (e.g. https://mars.frontity.org/2016/the-beauties-of-gullfoss) everything should work as usual.

**Observed behavior**

SSR works fine, but images are not loaded and links reload the whole document. That happens because Frontity has thrown an exception and stopped working.

This is the exception:

![Screenshot from 2021-03-10 18-56-20](https://user-images.githubusercontent.com/6917969/110674664-66a2e980-81d2-11eb-8c5b-3ec1a6f7d2f1.png)

**Possible solution**

The issue is located here:

https://github.com/frontity/frontity/blob/3a962aac3f926c43b42713f130694c4455c2ea72/packages/tiny-router/src/actions.ts#L201-L216

In those lines, when `state.frontity.initialLink` doesn't have the trailing slash, `link` is always different than `state.frontity.initialLink` because it's the same link but normalized, i.e. with the trailing slash.

What happens then is that both links (w/ and w/o trailing slash) already point to the same data object, and when the derived `initialDataObject` prop is resolved, it creates an infinite loop.

The problem is, `link` (normalized) is compared with `state.frontity.initialLink` (not normalized), so it should be enough if we compare both before normalizing `link`.

**Comment by DAreRodz** [comment]
@SantosGuillamot I guess this issue has critical priority so I've already created a PR instead of waiting for any decision. :slightly_smiling_face:

**Comment by SantosGuillamot** [comment]
Great, thanks David :slightly_smiling_face:
