### ISSUE TITLE
`className` attribute in WordPress content overwrites the `class`.

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/frontity#747]
**Observed behavior**

When a user has an element with a `className` attribute in their content, this attribute will be passed as `className` to the final react component created with `Html2React`.

Additionally, when a user has an element with both a `className` and `class` attribute in the WordPress content, that `className` will overwrite the `class`.

**Steps involved to reproduce the problem**

I've created a test case to show the behavior in #746 

**Possible solution**

I think that we should either a) ignore the `className` attribute in the user content; or b) Merge the content from `class` and `className` attributes.

Personally, I think that a) is a more reasonable solution and leads to less surprising behavior.

**Comment by SantosGuillamot** [comment]
Are there any known cases where we are going to get className from WordPress content?

**Comment by michalczaplinski** [comment]
> Are there any known cases where we are going to get className from WordPress content?

Nope, I don't know of any cases at the moment. It's only that it's possible to happen.

**Comment by cristianbote** [comment]
Was reading through this and it hit me, that `className` is a property of a DOM node, not an attribute. So, even if it exists on the html coming from WP I think it needs to be simply ignored.

That means we need to skip it when we find it. Pushed a change on that PR @michalczaplinski. Let me know what you think.

**Comment by michalczaplinski** [comment]
Yup, I think that this is the reasonable behaviour I was expecting :)
