### ISSUE TITLE
Infinite Scroll loads the same post twice when there are queries in the url

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#748]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When I visit a url with a query, like `?utm_campaign`, in a site where the Infinite Scroll is implemented, it should load the next post the same way it does when a query doesn't exist.

**Observed behavior**

When there is a query in a post and you scroll, it loads the same post but without the query.

**Steps involved to reproduce the problem**

* Go to https://frontity.org/blog/monthly-roundup-february-2021/?random_query=1234
* Start scrolling until it fetch the next post.

You will see it is the same one.

**Possible solution**

I guess that, at some point when loading the next post, we will need to check the `route` instead of the `link.

Here is where we are checking if the link is included in the archive or not:
https://github.com/frontity/frontity/blob/dev/packages/hooks/use-post-type-infinite-scroll/utils.ts#L52-L54

That firstLink we are passing as a parameter could be the `route` instead, without the query params.

**Comment by luisherranz** [comment]
This problem keeps beating us. We really need to have this fixed in a way that there is a way to tell Frontity what queries it should ignore and what queries it should preserve.

Related: https://community.frontity.org/t/wpsource-define-a-map-of-allowedqueries-to-only-preserve-them-in-data-references-links/3501
