### ISSUE TITLE
`npm install` fails after cloning a repo

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/frontity#780]
**Expected behavior**

`npm install` should succeed

**Observed behavior**

npm fails with the following error:

<img width="726" alt="Screen Shot 2021-04-12 at 11 05 35" src="https://user-images.githubusercontent.com/5417266/114425769-03182d00-9b7f-11eb-982b-b7214fcecafc.png">

**Steps involved to reproduce the problem**

```sh
git clone git@github.com:frontity/frontity.git
cd frontity
npm install
```

**Info about your system**

node version 15
npm version 7.6.0

**Possible solution**

not yet clear

**Comment by michalczaplinski** [comment]
Running the contents of the `build` script of the `@frontity/frontity` package before running `npm i` at the root fixes the issue. Details:

Using the globally installed `typescript` I can run `tsc --project ./tsconfig.build.json && cp -a templates dist/templates`. Then, running `npm i` at the root succeeds. 

The problem seems to be that lerna seems to try to run `frontity` somewhere before the `@frontity/frontity` package is built thus running into "no such file or directory" error.

**Comment by michalczaplinski** [comment]
After some more investigation, this is a bug in `npm`: https://github.com/npm/cli/issues/3065

When npm tries to symlink the `bin` of the `@frontity/frontity` package it runs into this problem because the `prepublish` script was not run and thus the file does not exist.

---

Interestingly, the problem is a bit deeper than that. I can change the `prepublish` scripts in our packages to `prepare` and it still fails, albeit with a different error: 

<img width="727" alt="Screen Shot 2021-04-12 at 15 25 55" src="https://user-images.githubusercontent.com/5417266/114457212-62883400-9ba3-11eb-9283-e5267f3aac8c.png">

This would suggest that npm is still broken because it tries to run the `prepublish` script of `@frontity/core` before ensuring that all of its dependencies (in this case `@frontity/file-settings` have been built first.

I wasn't able to make a clean reproduction of this in a new repo to report to the npm team though. I might try again later on.

---

The simplest **workaround** for all of this for now would be to opt out of npm workspaces altogether by just deleting the:

```
"workspaces": [
  "packages/*"
]
```

in our root `package.json`. I've tested it and it seems to work fine. 

@luisherranz You have added the npm workspaces to our main package.json file - is there some reason that I don't see for using them?

**Comment by luisherranz** [comment]
> You have added the npm workspaces to our main package.json file - is there some reason that I don't see for using them?

I added them so `npx changeset` suggestions are only shown for the packages that can be released. 

Changesets don't support lerna: https://github.com/atlassian/changesets/issues/130.

<img width="200" alt="Screenshot 2021-04-13 at 08 31 45" src="https://user-images.githubusercontent.com/3305402/114507267-2ef4ea80-9c33-11eb-8922-9ad7c15cf968.png">


Without it, it makes suggestions for all `package.json` found: 

<img width="200" alt="Screenshot 2021-04-13 at 08 33 59" src="https://user-images.githubusercontent.com/3305402/114507273-32887180-9c33-11eb-9d4c-0000dbf3952b.png">


So it is not really required. We can remove it for now. I'll make a PR 🙂

**Comment by michalczaplinski** [comment]
ok nice! I think that `changesets` *should* support lerna now. They [switched](https://github.com/atlassian/changesets/blob/main/packages/cli/src/run.ts#L39) to using `@manypkg/get-packages` which [has support for lerna](https://github.com/Thinkmill/manypkg/pull/63).

**Comment by luisherranz** [comment]
Good to know 👍 🙂
