### ISSUE TITLE
HMR loads the data object that was used in SSR rather than re-using the data object for the current link

### ISSUE THREAD

**Issue by mburridge** [frontity/frontity#782]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Upon making an edit to a theme file when you save the file the live server should re-render the page that is currently displayed in the browser.

**Observed behavior**
Instead, it renders the page that was used in the SSR.

**Steps involved to reproduce the problem**

Run `npx frontity dev` from a new project.

Navigate to a page other than the home page.

Make an edit to any theme file, a file within the `packages` directory that will cause the live server to re-render the page in the browser.

* See this question in the community: https://community.frontity.org/t/on-saved-changes-the-page-reloads-always-the-homepage/4383

**Info about your system**

## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 1.55 GB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
 - npm: 7.5.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
## Browsers:
 - Chrome: 89.0.4389.114
 - Edge: Not Found
 - Firefox: 87.0
 - Safari: 14.0.3
## npmPackages:
 - @frontity/core: ^1.11.1 => 1.11.1 
 - @frontity/html2react: ^1.6.2 => 1.6.2 
 - @frontity/mars-theme: ./packages/mars-theme => 1.5.0 
 - @frontity/tiny-router: ^1.4.1 => 1.4.1 
 - @frontity/wp-source: ^1.11.2 => 1.11.2 
 - frontity: ^1.14.3 => 1.14.3 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

**Comment by michalczaplinski** [comment]
We've reproduced it together with @mburridge in the mars theme. It can be reproduced easily by running the mars-theme in `projects/mars-theme`. 

I'm investigating it - I *think* it might be related to Frontity changing the link in the `init()` of the `tiny-router`: https://github.com/frontity/frontity/blob/a2495512f587fd4d00f8949f0cbf4c42be227329/packages/tiny-router/src/actions.ts#L179-L225

**Comment by michalczaplinski** [comment]
Found the problem.

If I comment those lines out, the issue goes away:
https://github.com/frontity/frontity/blob/a2495512f587fd4d00f8949f0cbf4c42be227329/packages/tiny-router/src/actions.ts#L216-L218

For a clearer explanation:

https://www.loom.com/share/f056ddd03a244bac974ef064fd7c36e5

**Comment by michalczaplinski** [comment]
I think that it's not a bug per se; rather the issue is that we should not be running the `init()` actions on the client after an HMR!

@luisherranz Am I correct in saying this?

**Comment by luisherranz** [comment]
> @luisherranz Am I correct in saying this?

I'm not entirely sure. Could be.

We can also disable that change if it's a HMR cycle?

Maybe something like this:

```js
if (!module.hot && browserLink !== state.frontity.initialLink) {
  // Run only once.
}
```

I'll a test later!

**Comment by luisherranz** [comment]
It seems like the `init()` functions still need to be executed. 

I have proposed a solution for this exposing a `state.frontity.hmr` flag here: https://github.com/frontity/frontity/pull/783
