### ISSUE TITLE
Links in wp-source should have the correct domain

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#79]
I've explained it here with images:
https://community.frontity.org/t/the-source-api/65/27

**Comment by luisherranz** [comment]
It looks like the preferred solution would be to strip out the domain and leave only paths.

**Comment by DAreRodz** [comment]
What happens if a WP site is hosted in a subpage, e.g. https://my-site.com/my-wp-blog?

How should paths be generated in this case?

**Comment by luisherranz** [comment]
You're right. WpSource needs to know the url of `state.frontity.url` to work around that case.
