### ISSUE TITLE
Static files with double slash returns 400 errors

### ISSUE THREAD

**Issue by javiersefer** [frontity/frontity#80]
Hello! I just ran 

$ npx frontity build
and then
$ npx frontity serve

When I open the browser it returns errors:

Failed to load resource: the server responded with a status of 400 (Bad Request)
:3000/static//list.module.67c883e8f30bc21bdfe3.js:1 
Failed to load resource: the server responded with a status of 400 (Bad Request)
:3000/static//list.module.67c883e8f30bc21bdfe3.js

Is trying to load static folder with double slash. If I remove one slash it load correctly.

**Comment by javiersefer** [comment]
I fixed this changing the publicPath variable on /my-app/node_modules/@frontity/core/dist/config/webpack/output.js:40

**Comment by luisherranz** [comment]
Hey @javiersefer, thanks for opening this issue.

I noticed this bug and I think it is fixed by this release:
https://github.com/frontity/frontity/releases/tag/%40frontity%2Fcore%400.3.6

Can you update to @frontity/core@0.3.6 and confirm that your issue has been fixed?

**Comment by javiersefer** [comment]
I created a new project and now it loads correctly with no errors! thanks!!

**Comment by luisherranz** [comment]
Awesome :)

You can update `frontity` and `@frontity/core` with a `npm update` command.
