### ISSUE TITLE
state.frontity.url has no effect

### ISSUE THREAD

**Issue by siddjain** [frontity/frontity#803]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Frontity should prefix requests for all resources with `state.frontity.url`. E.g., if my `state.frontity.url` is set to `https://mywebsite.com/videos` and I am running on localhost and open `http://localhost:3000` the XHR request to `/static/myapp.module.js` should be prefixed with `state.frontity.url` resulting in a complete URL that is `https://mywebsite.com/videos/static/myapp.module.js`

**Observed behavior**

`state.frontity.url` has no effect whatsoever and Frontity prefixes requests for resources with the domain name used in HTTP request. In above case, the XHR URL observed is `http://localhost:3000/static/myapp.module.js`

**Steps involved to reproduce the problem**

**Info about your system**

```
## System:
 - OS: Linux 4.9 Alpine Linux
 - CPU: (6) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 242.97 MB / 1.95 GB
 - Shell: 1.31.1 - /bin/ash
## Binaries:
 - Node: 12.18.0 - /usr/local/bin/node
 - npm: 6.14.4 - /usr/local/bin/npm
## Browsers:
 - Chrome: Not Found
 - Firefox: Not Found
## npmPackages:
 - @frontity/core: ^1.11.1 => 1.11.1
 - @frontity/html2react: ^1.6.2 => 1.6.2
 - @frontity/tiny-router: ^1.4.1 => 1.4.1
 - @frontity/twentytwenty-theme: ./packages/twentytwenty-theme => 1.3.0
 - @frontity/wp-source: ^1.11.2 => 1.11.2
 - frontity: ^1.14.3 => 1.14.3
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found


  System info copied in the clipboard!
  You can now paste it in the Frontity Community or GitHub issue.


(node:68) UnhandledPromiseRejectionWarning: Error: Couldn't find the `xsel` binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel
    at makeError (/home/node/node_modules/clipboardy/lib/linux.js:14:11)
    at xselWithFallbackSync (/home/node/node_modules/clipboardy/lib/linux.js:43:10)
    at Object.copySync (/home/node/node_modules/clipboardy/lib/linux.js:53:3)
    at Object.exports.writeSync (/home/node/node_modules/clipboardy/index.js:45:14)
    at Command.info (/home/node/node_modules/frontity/dist/src/cli/info.js:19:18)
(node:68) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:68) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Possible solution**

**Comment by luisherranz** [comment]
I think you are looking for the `--public-path` option. It can be used with both `npx frontity dev` and `npx frontity build`. Docs are here: https://api.frontity.org/frontity-cli/build-commands/build#the-public-path-option

Next time, ask the question in the community: https://community.frontity.org. Thanks!
