### ISSUE TITLE
Need  latest WordPress & Reactjs  update?

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [frontity/frontity#817]
Need update to latest WordPress v5.7.1 and latest Reactjs version v17.0.2?

**Comment by michalczaplinski** [comment]
Hi @ayoubkhan558 !

We use the community forum: https://community.frontity.org for questions like this one as is explained in the issue template. 

Please ask your question there and provide more context. It's not clear why you think that you need to update to the latest WordPress / React versions? Have you come across any other issues?

**Comment by ayoubkhan558-zz** [comment]
I did have any issues, I was just saying that updating fortify to latest version of WordPress & Reactjs  will be a god idea, So it will be more stable, more efficient.
