### ISSUE TITLE
wp-source should support common settings for permalinks by default

### ISSUE THREAD

**Issue by DAreRodz** [frontity/frontity#82]
We need to change the [wp-org](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/patterns/wp-org.ts) patterns to match all the permalink structures below (except for the custom one).

Currently, we support the custom one (as appears in the image), and the others don't. 😟

![Screenshot from 2019-05-20 11-40-26](https://user-images.githubusercontent.com/6917969/58012234-53ea8c80-7af4-11e9-9261-7813fd3281b1.png)

**Comment by adovgun** [comment]
yes, Today I tested your build and ran into a problem when the API data was not displayed due to the fact that I had selected the wrong type of permalinks that you use by default.

Most often POST NAME is used - an option without dates, which is significantly more acceptable for SEO indexing.

**Comment by DAreRodz** [comment]
As I wrote in #83, support for "plain" permalink was not implemented as our current `resolver` implementation cannot differentiate URLs based on the search query params.

I do not think it's a problem right now since that URL scheme is not widely used.

**Comment by luisherranz** [comment]
@adovgun this has been release in `@frontity/wp-source@0.1.7`. Could you please try it out and let us know if it is fixed?

You can update using:
```
npm install @frontity/wp-source@latest
```

**Comment by adovgun** [comment]
@luisherranz Many thanks will do QA as soon as possible, and reporting you about result.
