### ISSUE TITLE
Transpile `frontity.config.js` files

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#835]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

The `frontity.config.js` files should be transpiled on the fly.

**Observed behavior**

Right now they are transpiled only if the package is in the local folder, but as soon as you publish the package in npm and install it in `node_modules`, you are forced to use `commonjs` for them:

```js
module.exports = {
  webpack: ({ config }) => {
    // ...
  },
};
```

Instead of:

```js
export const webpack = ({ config }) => {
  // ...
};
```

**Steps involved to reproduce the problem**

Create a package in the `node_modules` folder (using `npm link` for example) and add a `frontity.config.js` file.

**Possible solution**

I'm not sure why they are not transpiled if they are in `node_modules`. I'll try to triage the problem and add more information.

**Comment by nicholasio** [comment]
For testing, you can also just try to install `npm i @10up/frontity-build-config@0.1.0` which isn't commonjs.

**Comment by luisherranz** [comment]
This should do it: https://github.com/frontity/frontity/pull/837
