### ISSUE TITLE
Can't login to Frontity Community Forum

### ISSUE THREAD

**Issue by kdong007** [frontity/frontity#856]
![Screen Shot 2021-06-30 at 4 20 06 PM](https://user-images.githubusercontent.com/26269173/124043126-3e2c3e80-d9bf-11eb-96c5-9b0276faaaed.png)

Can't find the "site's administrator" either...

**Comment by DAreRodz** [comment]
Hi @kdong007, this is an issue that happens from time to time, and it seems to be a Discourse problem (which is the engine we use for our community). Restarting the computer or clearing browser’s history seems to do the trick. Let us know if that solves the issue.

**Comment by DAreRodz** [comment]
I'm closing this as it is not code-related, but feel free to continue the conversation. :slightly_smiling_face:
