### ISSUE TITLE
Error when creating new project in China due to the failure on downloading favicon.ico

### ISSUE THREAD

**Issue by yiheyang** [frontity/frontity#861]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

**Observed behavior**

**Steps involved to reproduce the problem**

Just using `npx frontity create`

then throw `Error: request to https://favicon.frontity.org/ failed, reason: connect ECONNREFUSED 76.76.21.21:443`

because `https://favicon.frontity.org/` is not accessible in China.

After setting up a proxy in Terminal using `http_proxy` and `https_proxy`, it's still not working.

![image](https://user-images.githubusercontent.com/8202550/128267610-f2cd173f-3f0a-4597-ad7c-1648725b9f8c.png)

**Info about your system**

## System:
 - OS: macOS 11.4
 - CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
 - Memory: 10.25 GB / 64.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.17.0 - /usr/local/bin/node
 - npm: 7.19.1 - /usr/local/bin/npm
## Browsers:
 - Chrome: 92.0.4515.107
 - Edge: Not Found
 - Firefox: Not Found
 - Safari: 14.1.1
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

I could see `https://favicon.frontity.org/` is deployed on Vercel, there are four solutions:

1. Change the site provider which is accessible in China.
2. Provide an option in CLI to skip the favicon downloading.
3. Make the inner request module use `http_proxy` and `https_proxy` like `curl` does.
4. Directly put favicon.ico in the git.

**Comment by Ecostack** [comment]
Quite interested in this too! Bump!
