### ISSUE TITLE
I want to include custom scripts and styles files which is comes with third party library

### ISSUE THREAD

**Issue by gandhihitesh9** [frontity/frontity#886]
Hello peoples,

I need your help.

Thanks in advanced.

I want to include owl carousel into my theme.

So they are providing styles and scripts like below.

```
<link rel="stylesheet" href="owlcarousel/owl.carousel.min.css">
<link rel="stylesheet" href="owlcarousel/owl.theme.default.min.css">
```

```
<script src="jquery.min.js"></script>
<script src="owlcarousel/owl.carousel.min.js"></script>
```

So my question is how to include these styles and scripts into project?

I have included styles using this global way. but its not optimized way whenever anything changed into page that styles rendering again and again.  [9. Styles - Frontity Docs](https://docs.frontity.org/learning-frontity/styles#external-css-files)

Please help me on this.

**Comment by luisherranz** [comment]
Please, ask in the [Community Forum](https://community.frontity.org/)! Thanks 🙂
