### ISSUE TITLE
npm severe security vulnerabilities with frontity

### ISSUE THREAD

**Issue by pac96** [frontity/frontity#889]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org/t/npm-audit-high-severity-vulnerabilities/5444. no one has responded to the relevant question yet!

**Motivation:** I'd like to build and deploy a site for a client using Frontity to facilitate Wordpress usage as a CMS so I can use React. This seems to be the easiest way, but I'm uncomfortable doing so with the security vulnerabilities present. This has persisted for months, so I figured I'd post here since I couldn't find the issue on Github.

**Expected behavior**

When running `npm i`, there should be no security vulnerabilities listed.

**Observed behavior**

Running `npm i` in the root frontity directory reveals 9 high security vulnerabilities for frontity dependencies. I tried this using the sample frontity project in the tutorial.

Here's the audit report:

up to date, audited 913 packages in 2s

55 packages are looking for funding
  run `npm fund` for details

-- npm audit report --

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`

Will install @frontity/core@1.9.1, which is a breaking change
node_modules/watchpack-chokidar2/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/watchpack-chokidar2/node_modules/chokidar
    
    watchpack-chokidar2  *
    Depends on vulnerable versions of chokidar
    node_modules/watchpack-chokidar2
      watchpack  1.7.2 - 1.7.5
      Depends on vulnerable versions of watchpack-chokidar2
      node_modules/watchpack
        webpack  4.44.0 - 4.46.0
        Depends on vulnerable versions of watchpack
        node_modules/webpack
          @frontity/core  >=1.10.0
          Depends on vulnerable versions of webpack
          node_modules/@frontity/core
            frontity  >=1.14.2
            Depends on vulnerable versions of @frontity/core
            Depends on vulnerable versions of node-fetch
            node_modules/frontity
              @frontity/wp-source  >=1.11.6
              Depends on vulnerable versions of frontity
              node_modules/@frontity/wp-source

node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix --force`
Will install frontity@1.17.0, which is a breaking change

node_modules/node-fetch
  frontity  >=1.14.2
  Depends on vulnerable versions of @frontity/core
  Depends on vulnerable versions of node-fetch
  node_modules/frontity
    @frontity/wp-source  >=1.11.6
    Depends on vulnerable versions of frontity
    node_modules/@frontity/wp-source

9 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

**Steps involved to reproduce the problem**

1. Run `npx frontity create <project_name>`. For example, I ran `npx frontity create frontity-vulnerability`.
2. Press enter when prompted for a theme to start with (I used the recommended Mars theme)
3. When the installation is finished, navigate to the frontity project (`cd frontity-vulnerability` in my case) and run `npm install`.
4. Observe the npm security vulnerability warnings 

[Link to repo with minimum amount of code that presents this problem](https://github.com/pac96/frontity-vulnerability) 

**Info about your system**

## System:
 - OS: macOS 11.0.1
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 76.85 MB / 8.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
 - npm: 8.3.2 - ~/.nvm/versions/node/v17.4.0/bin/npm
## Browsers:
 - Chrome: 97.0.4692.99
 - Edge: Not Found
 - Firefox: 80.0
 - Safari: 14.0.1
## npmPackages:
 - @frontity/core: ^1.14.3 => 1.14.3 
 - @frontity/html2react: ^1.7.0 => 1.7.0 
 - @frontity/mars-theme: ./packages/mars-theme => 1.6.2 
 - @frontity/tiny-router: ^1.4.4 => 1.4.4 
 - @frontity/wp-source: ^1.11.7 => 1.11.7 
 - dayjs: ^1.10.7 => 1.10.7 
 - frontity: ^1.17.1 => 1.17.1 
 - my-first-theme: file:packages/my-first-theme => 1.0.0 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

I _think_ we need to perhaps manually update the packages mentioned in the audit report, and merge those changes in to update the package.json. It seems as though there may be some breaking changes. For some reason, running `npm audit fix --force` takes forever to complete, and just hangs. When I do it, all I see are warnings like:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: hello-frontity@1.0.0
npm WARN Found: @frontity/core@1.9.1
npm WARN node_modules/@frontity/core
npm WARN   @frontity/core@"1.9.1" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @frontity/core@"^1.10.1" from frontity@1.17.0
npm WARN node_modules/frontity
npm WARN   frontity@"1.17.0" from the root project
npm WARN   8 more (@frontity/components, @frontity/hooks, ...)
```

**Comment by luisherranz** [comment]
Hey @pac96, can you open a PR with the updated `package.json` and `package-lock.json` files?

**Comment by qant** [comment]
> Hey @pac96, can you open a PR with the updated `package.json` and `package-lock.json` files?

found 56 vulnerabilities (18 moderate, 38 high) i think its not about just change the package.json... imo

**Comment by luisherranz** [comment]
I've updated [the ones suggested by GitHub dependabot](https://github.com/frontity/frontity/pulls?q=is%3Apr+is%3Aclosed) in the latest release, but you don't depend on Frontity doing so: you should always [keep your `package-lock.json` up to date](https://itnext.io/fixing-security-vulnerabilities-in-npm-dependencies-in-less-than-3-mins-a53af735261d).

I'm going to close this for now. If you want Frontity itself to be updated, please open a PR with the updated `package-lock.json`. Thanks 🙂
