### ISSUE TITLE
The public directory path of imported assets are not being loaded correctly

### ISSUE THREAD

**Issue by husseincak** [frontity/frontity#908]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions
- I've searched for existing issues:
-- https://community.frontity.org/t/frontity-release-dynamic-public-path/5790/2
-- https://community.frontity.org/t/imported-image-src-not-being-prepended-with-public-directory-path/5783

**Expected behavior**

Import an static file like an image and load it directly on the code.

**Observed behavior**

 The problem is on the SSR. On the server side rendering the path of the images is the relative path of the current url, so for example:
- If we have the image **/resources/imgs/logo.png**
- on a page that have this slug **/about-page/**

The link to the image on SSR is

- **/about-page/images/logo.png** instead of being **/static/images/logo.png**

**Steps involved to reproduce the problem**

1. Create or update a frontity installation with the latest update
2. Try to import any static file, like an image
```
import Logo from "../images/logo.png";

const Header = ({ state }) => {
  return ( 
    <> 
       <img src={Logo} />
    </>
  );
};
```
3. The image will not load if you refresh the page or access via SSR

Link to the repository: 
https://github.com/husseincak/testfrontity/

**Comment by AsadZahed** [comment]
Have you found the solution or is it being solved?

**Comment by luisherranz** [comment]
I've opened a PR with a possible fix: https://github.com/frontity/frontity/pull/909
