### ISSUE TITLE
Cannot return a custom `robots.txt` file for each site using `afterSSR`

### ISSUE THREAD

**Issue by orballo** [frontity/frontity#912]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

If I create a handler for `/robots.txt` that handler should run as any other, i.e. `/sitemap.xml`. Then I should be able to modify the response in the `afterSSR` action to send a dynamic value for my `robots.txt`.

**Observed behavior**

The server is intercepting the `/robots.txt` route before it reaches the server side rendering and any other Frontity actions, so I never have the opportunity to return my value in this route, and I get a default value hardcoded in Frontity.

**Possible solution**

In the absence of a `robots.txt` file in the root directory, do not hardcode the response body and let the process continue so I can handle the route from Frontity.

**Comment by luisherranz** [comment]
Ideally, this should be handled by server extensibility: https://community.frontity.org/t/server-extensibility/2810/23?u=luisherranz

```js
// packages/my-package/src/server.js
import myPackage from "./client";
import { get } from "koa-route"; 

export default {
  ...myPackage,
  server: {
    serveRobotsTxT: get("/robots.txt", async ({ ctx, next, state }) => {
      ctx.type = "text/plain";
      ctx.body = "...";
    }),
  },
};
```

**Comment by orballo** [comment]
Now that server extensibility has been released, this issue can be closed.
